<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import * as echarts from 'echarts'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ApiError } from '@/api/http'
import { cancelMoney, createMoney, getFinanceSummary, getFinanceTrend, getGoodsReport, getMoney, getPartnerSummary, listAccounts, listMoney, payMoney, saveAccount, type FinanceAccount, type FinanceSummary, type GoodsReport, type Money, type MoneyDetail, type PartnerSummary, type TrendPoint } from '@/api/finance'

const loading=ref(false),active=ref('money'),money=ref<Money[]>([]),accounts=ref<FinanceAccount[]>([]),summary=ref<FinanceSummary>(),trend=ref<TrendPoint[]>([]),partners=ref<PartnerSummary[]>([]),report=ref<GoodsReport[]>([])
const month=ref(new Date().toISOString().slice(0,7)),direction=ref(''),state=ref(''),q=ref(''),partnerDirection=ref('INCOME'),reportType=ref<'stockin'|'stockout'>('stockin')
const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1),reportDates=ref<[Date,Date]>([first,now])
const chartEl=ref<HTMLElement>(),drawer=ref(false),detail=ref<MoneyDetail>(),moneyDialog=ref(false),payDialog=ref(false),accountDialog=ref(false)
let chart:echarts.ECharts|undefined
const moneyForm=reactive({direction:'INCOME',feeType:'SALE',relatedOrderCode:'',partnerCode:'',payType:'BANK',amount:0,accountingDate:new Date().toISOString().slice(0,10),remark:''})
const payForm=reactive({amount:0,accountId:undefined as number|undefined,referenceUser:'',partComplete:false,remark:''})
const accountForm=reactive({id:undefined as number|undefined,organ:'',name:'',accountNo:'',status:'ENABLED',remark:''})
const fmt=(v:number)=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})
const stateText:Record<string,string>={DRAFT:'草稿',PROCESSING:'进行中',COMPLETED:'已结清',PART_COMPLETED:'部分完结',CANCELLED:'已取消'}
const canPay=computed(()=>detail.value&&['DRAFT','PROCESSING'].includes(detail.value.money.state))

async function loadAll(){loading.value=true;try{const [m,a,s,t]=await Promise.all([listMoney({direction:direction.value,state:state.value,q:q.value}),listAccounts(),getFinanceSummary(month.value),getFinanceTrend()]);money.value=m;accounts.value=a;summary.value=s;trend.value=t;await nextTick();draw()}catch(e){error(e)}finally{loading.value=false}}
function draw(){if(!chartEl.value)return;chart??=echarts.init(chartEl.value);chart.setOption({tooltip:{trigger:'axis'},legend:{data:['应收','实收','应付','实付']},grid:{left:48,right:24,bottom:32,top:42},xAxis:{type:'category',data:trend.value.map(x=>x.month)},yAxis:{type:'value'},series:[{name:'应收',type:'bar',data:trend.value.map(x=>x.incomeAmount)},{name:'实收',type:'line',smooth:true,data:trend.value.map(x=>x.incomePaid)},{name:'应付',type:'bar',data:trend.value.map(x=>x.outcomeAmount)},{name:'实付',type:'line',smooth:true,data:trend.value.map(x=>x.outcomePaid)}]})}
async function openDetail(row:Money){detail.value=await getMoney(row.id);drawer.value=true}
async function submitMoney(){if(moneyForm.amount<=0)return void ElMessage.warning('金额必须大于0');try{const d=await createMoney({...moneyForm,idempotencyKey:crypto.randomUUID()});moneyDialog.value=false;detail.value=d;drawer.value=true;ElMessage.success('费用单已创建');await loadAll()}catch(e){error(e)}}
function openPay(){if(!detail.value)return;payForm.amount=detail.value.money.outstandingAmount;payForm.accountId=undefined;payForm.referenceUser='';payForm.partComplete=false;payForm.remark='';payDialog.value=true}
async function submitPay(){if(!detail.value)return;try{detail.value=await payMoney(detail.value.money.id,{...payForm,idempotencyKey:crypto.randomUUID()});payDialog.value=false;ElMessage.success('收付款流水已登记');await loadAll()}catch(e){error(e)}}
async function cancelCurrent(){if(!detail.value)return;try{await ElMessageBox.confirm('确定取消这张费用单吗？','取消费用单',{type:'warning'});detail.value=await cancelMoney(detail.value.money.id,{remark:'用户取消'});await loadAll()}catch(e){if(e!=='cancel')error(e)}}
function newAccount(row?:FinanceAccount){Object.assign(accountForm,row?{id:row.id,organ:row.organ,name:row.name,accountNo:row.accountNo,status:row.status,remark:row.remark??''}:{id:undefined,organ:'',name:'',accountNo:'',status:'ENABLED',remark:''});accountDialog.value=true}
async function submitAccount(){try{await saveAccount(accountForm.id,{...accountForm});accountDialog.value=false;accounts.value=await listAccounts();ElMessage.success('账户已保存')}catch(e){error(e)}}
async function loadPartners(){partners.value=await getPartnerSummary(partnerDirection.value)}
async function loadReport(){const [a,b]=reportDates.value;report.value=await getGoodsReport(reportType.value,a.toLocaleDateString('sv-SE'),b.toLocaleDateString('sv-SE'))}
async function tabChanged(name:string|number){if(name==='partners')await loadPartners();if(name==='report')await loadReport();if(name==='trend'){await nextTick();draw();chart?.resize()}}
function error(e:unknown){ElMessage.error(e instanceof ApiError?e.message:e instanceof Error?e.message:'操作失败')}
function resize(){chart?.resize()}
onMounted(()=>{void loadAll();window.addEventListener('resize',resize)})
onBeforeUnmount(()=>{window.removeEventListener('resize',resize);chart?.dispose()})
</script>

<template>
  <div class="page-stack">
    <section class="page-heading"><div><p class="eyebrow">FINANCE & ANALYTICS</p><h1>财务统计</h1><p>应收应付、收付款流水与仓储经营统计统一在当前业务范围内核算。</p></div><el-button type="primary" :loading="loading" @click="loadAll">刷新数据</el-button></section>
    <section v-if="summary" class="metric-grid finance-metrics">
      <article><span>本月应收</span><strong>¥ {{ fmt(summary.incomeAmount) }}</strong><small>未收 ¥ {{ fmt(summary.incomeOutstanding) }}</small></article>
      <article><span>本月实收</span><strong>¥ {{ fmt(summary.incomePaid) }}</strong><small>{{ summary.month }} 收款流水</small></article>
      <article><span>本月应付 / 实付</span><strong>¥ {{ fmt(summary.outcomeAmount) }}</strong><small>已付 ¥ {{ fmt(summary.outcomePaid) }}</small></article>
      <article :class="{warning:summary.grossProfit<0}"><span>本月现金毛利</span><strong>¥ {{ fmt(summary.grossProfit) }}</strong><small>实收减实付</small></article>
    </section>
    <section class="panel finance-panel">
      <el-tabs v-model="active" @tab-change="tabChanged">
        <el-tab-pane label="费用明细" name="money">
          <div class="toolbar"><el-input v-model="q" clearable placeholder="费用单号 / 关联单号 / 合作伙伴" style="width:300px" @keyup.enter="loadAll"/><el-select v-model="direction" clearable placeholder="全部收支" style="width:130px"><el-option label="收入 / 应收" value="INCOME"/><el-option label="支出 / 应付" value="OUTCOME"/></el-select><el-select v-model="state" clearable placeholder="全部状态" style="width:140px"><el-option v-for="(label,key) in stateText" :key="key" :label="label" :value="key"/></el-select><el-button @click="loadAll">查询</el-button><span class="grow"/><el-button type="primary" @click="moneyDialog=true">新增费用</el-button></div>
          <el-table :data="money" v-loading="loading" height="460" @row-dblclick="openDetail"><el-table-column prop="moneyCode" label="费用单号" width="130"/><el-table-column label="收支" width="90"><template #default="{row}"><el-tag :type="row.direction==='INCOME'?'success':'danger'">{{ row.direction==='INCOME'?'应收':'应付' }}</el-tag></template></el-table-column><el-table-column prop="feeType" label="费用类型" width="120"/><el-table-column prop="relatedOrderCode" label="关联单号" width="140"/><el-table-column prop="partnerName" label="合作伙伴" min-width="130"/><el-table-column label="总额" width="110" align="right"><template #default="{row}">{{ fmt(row.amount) }}</template></el-table-column><el-table-column label="实额" width="110" align="right"><template #default="{row}">{{ fmt(row.paidAmount) }}</template></el-table-column><el-table-column label="未结" width="110" align="right"><template #default="{row}">{{ fmt(row.outstandingAmount) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}">{{ stateText[row.state]??row.state }}</template></el-table-column><el-table-column prop="accountingDate" label="记账日" width="110"/><el-table-column fixed="right" label="操作" width="80"><template #default="{row}"><el-button link type="primary" @click="openDetail(row)">详情</el-button></template></el-table-column></el-table>
        </el-tab-pane>
        <el-tab-pane label="月度趋势" name="trend"><div class="chart-toolbar"><el-date-picker v-model="month" type="month" value-format="YYYY-MM" @change="loadAll"/><span>最近 12 个月应收、实收、应付、实付</span></div><div ref="chartEl" class="finance-chart"/></el-tab-pane>
        <el-tab-pane label="客户汇总" name="partners"><div class="toolbar"><el-radio-group v-model="partnerDirection" @change="loadPartners"><el-radio-button value="INCOME">应收汇总</el-radio-button><el-radio-button value="OUTCOME">应付汇总</el-radio-button></el-radio-group></div><el-table :data="partners" height="450"><el-table-column prop="partnerCode" label="合作伙伴码"/><el-table-column prop="partnerName" label="合作伙伴"/><el-table-column label="总额" align="right"><template #default="{row}">{{ fmt(row.amount) }}</template></el-table-column><el-table-column label="实额" align="right"><template #default="{row}">{{ fmt(row.paidAmount) }}</template></el-table-column><el-table-column label="余额" align="right"><template #default="{row}">{{ fmt(row.outstandingAmount) }}</template></el-table-column></el-table></el-tab-pane>
        <el-tab-pane label="出入库统计" name="report"><div class="toolbar"><el-radio-group v-model="reportType"><el-radio-button value="stockin">入库统计</el-radio-button><el-radio-button value="stockout">出库统计</el-radio-button></el-radio-group><el-date-picker v-model="reportDates" type="daterange" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期"/><el-button type="primary" @click="loadReport">统计</el-button></div><el-table :data="report" height="450"><el-table-column prop="goodCode" label="货品码"/><el-table-column prop="goodName" label="货品名称"/><el-table-column prop="supplierCode" label="供应商"/><el-table-column prop="qualityType" label="质量" width="80"/><el-table-column prop="plannedQty" label="计划数量" align="right"/><el-table-column prop="actualQty" :label="reportType==='stockin'?'实收数量':'发运数量'" align="right"/><el-table-column label="金额" align="right"><template #default="{row}">{{ fmt(row.amount) }}</template></el-table-column></el-table></el-tab-pane>
        <el-tab-pane label="收付款账户" name="accounts"><div class="toolbar"><span class="grow"/><el-button type="primary" @click="newAccount()">新增账户</el-button></div><el-table :data="accounts" height="450"><el-table-column prop="organ" label="开户机构"/><el-table-column prop="name" label="账户名称"/><el-table-column prop="accountNo" label="账号"/><el-table-column prop="longName" label="账户全称"/><el-table-column prop="status" label="状态" width="100"/><el-table-column label="操作" width="80"><template #default="{row}"><el-button link type="primary" @click="newAccount(row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane>
      </el-tabs>
    </section>

    <el-dialog v-model="moneyDialog" title="新增费用单" width="660px"><el-form label-position="top"><div class="form-grid"><el-form-item label="收支方向"><el-select v-model="moneyForm.direction"><el-option label="收入 / 应收" value="INCOME"/><el-option label="支出 / 应付" value="OUTCOME"/></el-select></el-form-item><el-form-item label="费用类型"><el-input v-model="moneyForm.feeType" placeholder="SALE / PURCHASE / EXPRESS / OTHER"/></el-form-item><el-form-item label="金额"><el-input-number v-model="moneyForm.amount" :min="0" :precision="2" style="width:100%"/></el-form-item><el-form-item label="记账日"><el-date-picker v-model="moneyForm.accountingDate" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item><el-form-item label="关联单号"><el-input v-model="moneyForm.relatedOrderCode"/></el-form-item><el-form-item label="合作伙伴码"><el-input v-model="moneyForm.partnerCode"/></el-form-item><el-form-item label="收付方式"><el-input v-model="moneyForm.payType"/></el-form-item><el-form-item label="备注"><el-input v-model="moneyForm.remark"/></el-form-item></div></el-form><template #footer><el-button @click="moneyDialog=false">取消</el-button><el-button type="primary" @click="submitMoney">创建</el-button></template></el-dialog>
    <el-drawer v-model="drawer" title="费用单详情" size="720px"><template v-if="detail"><el-descriptions :column="2" border><el-descriptions-item label="费用单号">{{ detail.money.moneyCode }}</el-descriptions-item><el-descriptions-item label="状态">{{ stateText[detail.money.state] }}</el-descriptions-item><el-descriptions-item label="总额">¥ {{ fmt(detail.money.amount) }}</el-descriptions-item><el-descriptions-item label="未结">¥ {{ fmt(detail.money.outstandingAmount) }}</el-descriptions-item><el-descriptions-item label="合作伙伴">{{ detail.money.partnerName||'-' }}</el-descriptions-item><el-descriptions-item label="关联单号">{{ detail.money.relatedOrderCode||'-' }}</el-descriptions-item></el-descriptions><div class="drawer-actions"><el-button v-if="canPay" type="primary" @click="openPay">登记收付款</el-button><el-button v-if="detail.money.state==='DRAFT'" type="danger" plain @click="cancelCurrent">取消费用单</el-button></div><h3>收付款流水</h3><el-table :data="detail.transactions"><el-table-column prop="transactionCode" label="流水号"/><el-table-column prop="amount" label="金额"/><el-table-column prop="accountLongName" label="账户"/><el-table-column prop="operatorName" label="操作人"/><el-table-column prop="createdAt" label="时间" width="190"/></el-table></template></el-drawer>
    <el-dialog v-model="payDialog" title="登记收付款流水" width="520px"><el-form label-position="top"><el-form-item label="本次金额"><el-input-number v-model="payForm.amount" :min="0.01" :max="detail?.money.outstandingAmount" :precision="2" style="width:100%"/></el-form-item><el-form-item label="收付款账户"><el-select v-model="payForm.accountId" clearable style="width:100%"><el-option v-for="a in accounts.filter(x=>x.status==='ENABLED')" :key="a.id" :label="a.longName" :value="a.id"/></el-select></el-form-item><el-form-item label="经手人"><el-input v-model="payForm.referenceUser"/></el-form-item><el-form-item><el-checkbox v-model="payForm.partComplete">本次部分收付后完结，剩余金额记为坏账</el-checkbox></el-form-item><el-form-item label="备注"><el-input v-model="payForm.remark"/></el-form-item></el-form><template #footer><el-button @click="payDialog=false">取消</el-button><el-button type="primary" @click="submitPay">确认登记</el-button></template></el-dialog>
    <el-dialog v-model="accountDialog" title="收付款账户" width="560px"><el-form label-position="top"><div class="form-grid"><el-form-item label="开户机构"><el-input v-model="accountForm.organ"/></el-form-item><el-form-item label="账户名称"><el-input v-model="accountForm.name"/></el-form-item><el-form-item label="账号"><el-input v-model="accountForm.accountNo"/></el-form-item><el-form-item label="状态"><el-select v-model="accountForm.status"><el-option label="启用" value="ENABLED"/><el-option label="停用" value="DISABLED"/></el-select></el-form-item></div><el-form-item label="备注"><el-input v-model="accountForm.remark"/></el-form-item></el-form><template #footer><el-button @click="accountDialog=false">取消</el-button><el-button type="primary" @click="submitAccount">保存</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.finance-metrics strong{font-size:24px}.finance-panel{padding-top:6px;overflow:hidden}.finance-panel :deep(.el-tabs__header){padding:0 14px}.toolbar{display:flex;align-items:center;gap:10px;margin:10px 0 16px}.grow{flex:1}.finance-chart{height:440px}.chart-toolbar{display:flex;align-items:center;gap:20px;color:var(--wms-text-secondary);margin:10px 0}.drawer-actions{display:flex;gap:10px;margin:18px 0}h3{margin-top:28px}
</style>
