<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ApiError } from '@/api/http'
import { listMasterData, type MasterItem } from '@/api/masterData'
import { useAuthStore } from '@/stores/auth'
import {
  allocateStockout, allocateStockoutWave, cancelAllocation, cancelStockout, completeStockout,
  createStockoutOrder, createStockoutWave, getStockoutOrder, listStockoutAllocations, listStockoutEvents,
  listStockoutOrders, listStockoutPackages, listStockoutWaves, packStockout, pickAllStockout,
  pickStockout, pickStockoutWave, reverseStockout, shipStockout,
  type StockoutAllocation, type StockoutEvent, type StockoutLine, type StockoutOrderDetail,
  type StockoutOrderSummary, type StockoutPackage, type StockoutWave,
} from '@/api/stockout'

const auth=useAuthStore()
const orders=ref<StockoutOrderSummary[]>([]),waves=ref<StockoutWave[]>([]),goods=ref<MasterItem[]>([]),partners=ref<MasterItem[]>([])
const allocations=ref<StockoutAllocation[]>([]),events=ref<StockoutEvent[]>([]),packages=ref<StockoutPackage[]>([]),selected=ref<StockoutOrderDetail|null>(null)
const loading=ref(false),saving=ref(false),activeView=ref('orders'),drawer=ref(false),drawerTab=ref('lines'),createDialog=ref(false),pickDialog=ref(false),packDialog=ref(false)
const pickingLine=ref<StockoutLine|null>(null),selectedRows=ref<StockoutOrderSummary[]>([])
const typeOptions=[['SALE','销售出库'],['PRODUCE','生产出库'],['NORMAL','普通出库'],['RETURN','采购退货'],['COOP','协作出库'],['MATERIAL_PICK','领料出库'],['FIX','维修出库'],['SCRAP','报废出库'],['BORROW','借用出库'],['TRANSFER','调拨出库'],['CONSIGN','寄售出库'],['CUSTOM','自定义出库']]
const typeText=Object.fromEntries(typeOptions),stateText:Record<string,string>={DRAFT:'待分配',PROCESSING:'作业中',COMPLETED:'已完成',CANCELLED:'已取消'},progressText:Record<string,string>={NO:'未开始',PARTIAL:'部分',FULL:'完成'}
type DraftLine={goodCode:string;plannedQty:number;supplierCode:string;qualityType:string;batchCode:string;unitPrice:number;remark:string}
const createForm=reactive<{outboundType:string;source:string;externalOrderCode:string;relatedOrderCode:string;partnerCode:string;plannedDate:string;receiverName:string;receiverPhone:string;receiverAddress:string;carrierCode:string;trackingCode:string;targetWarehouseCode:string;targetOwnerCode:string;remark:string;lines:DraftLine[]}>({outboundType:'SALE',source:'CUSTOM',externalOrderCode:'',relatedOrderCode:'',partnerCode:'',plannedDate:'',receiverName:'',receiverPhone:'',receiverAddress:'',carrierCode:'',trackingCode:'',targetWarehouseCode:'',targetOwnerCode:'',remark:'',lines:[]})
const pickForm=reactive({quantity:1,barcode:'',serialText:'',remark:''})
const packForm=reactive<{carrierCode:string;trackingCode:string;remark:string;lines:{lineId:number;goodCode:string;quantity:number;max:number}[]}>({carrierCode:'',trackingCode:'',remark:'',lines:[]})
const pendingCount=computed(()=>orders.value.filter(x=>['DRAFT','PROCESSING'].includes(x.state)).length),completedCount=computed(()=>orders.value.filter(x=>x.state==='COMPLETED').length),shippedTotal=computed(()=>orders.value.reduce((n,x)=>n+Number(x.shippedQty),0))
const warehouseOptions=computed(()=>auth.user?.tenant.warehouses??[]),ownerOptions=computed(()=>auth.user?.tenant.owners??[])

function key(){return globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`}
function fail(reason:unknown,fallback:string){ElMessage.error(reason instanceof ApiError?reason.message:fallback)}
function qty(v:number){return Number(v).toLocaleString('zh-CN',{maximumFractionDigits:3})}
function money(v:number){return Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function time(v?:string){return v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-'}
function percent(row:StockoutOrderSummary){return Number(row.plannedQty)>0?Math.min(100,Math.round(Number(row.shippedQty)*100/Number(row.plannedQty))):0}
function serials(v:string){return v.split(/[\s,，;；]+/).map(x=>x.trim()).filter(Boolean)}
async function load(){loading.value=true;try{[orders.value,waves.value,goods.value,partners.value]=await Promise.all([listStockoutOrders(),listStockoutWaves(),listMasterData('goods'),listMasterData('partners')])}catch(e){fail(e,'出库数据加载失败')}finally{loading.value=false}}
async function openDetail(id:number){try{[selected.value,allocations.value,events.value,packages.value]=await Promise.all([getStockoutOrder(id),listStockoutAllocations(id),listStockoutEvents(id),listStockoutPackages(id)]);drawerTab.value='lines';drawer.value=true}catch(e){fail(e,'出库单详情加载失败')}}
function rowDblclick(row:StockoutOrderSummary){void openDetail(row.id)}
function blankLine():DraftLine{return{goodCode:goods.value[0]?.code??'',plannedQty:1,supplierCode:'',qualityType:'ZP',batchCode:'',unitPrice:0,remark:''}}
function openCreate(){Object.assign(createForm,{outboundType:'SALE',source:'CUSTOM',externalOrderCode:'',relatedOrderCode:'',partnerCode:'',plannedDate:'',receiverName:'',receiverPhone:'',receiverAddress:'',carrierCode:'',trackingCode:'',targetWarehouseCode:auth.user?.tenant.currentWarehouse.code??'',targetOwnerCode:auth.user?.tenant.currentOwner.code??'',remark:'',lines:[blankLine()]});createDialog.value=true}
async function submitCreate(){if(!createForm.lines.length)return void ElMessage.warning('至少添加一条出库明细');saving.value=true;try{const order=await createStockoutOrder({...createForm,plannedDate:createForm.plannedDate||null,idempotencyKey:key()});ElMessage.success(`出库单已创建：${order.orderCode}`);createDialog.value=false;await load();await openDetail(order.id)}catch(e){fail(e,'出库单创建失败')}finally{saving.value=false}}
async function refreshDetail(){if(selected.value){await load();await openDetail(selected.value.id)}}
async function allocate(){if(!selected.value)return;try{const allow=await ElMessageBox.confirm('库存不足时是否允许部分分配？','自动分配',{confirmButtonText:'允许部分分配',cancelButtonText:'必须全部分配',distinguishCancelAndClose:true,type:'info'}).then(()=>true).catch(x=>{if(x==='cancel')return false;throw x});saving.value=true;const result=await allocateStockout(selected.value.id,{allowPartial:allow,idempotencyKey:key(),remark:'页面自动分配'});ElMessage.success(`分配成功：${result.operationCode}`);await refreshDetail()}catch(e){if(e!=='close')fail(e,'库存分配失败')}finally{saving.value=false}}
async function pickAll(){if(!selected.value)return;saving.value=true;try{const result=await pickAllStockout(selected.value.id,{idempotencyKey:key(),remark:'整单快速拣货'});ElMessage.success(`拣货成功：${result.operationCode}`);await refreshDetail()}catch(e){fail(e,'快速拣货失败')}finally{saving.value=false}}
function openPick(line:StockoutLine){pickingLine.value=line;Object.assign(pickForm,{quantity:Number(line.unpickedQty),barcode:line.barcode,serialText:'',remark:''});pickDialog.value=true}
async function submitPick(){if(!selected.value||!pickingLine.value)return;saving.value=true;try{const result=await pickStockout(selected.value.id,{idempotencyKey:key(),lines:[{lineId:pickingLine.value.id,barcode:pickForm.barcode,quantity:pickForm.quantity,serialCodes:serials(pickForm.serialText),remark:pickForm.remark}]});ElMessage.success(`扫码拣货成功：${result.operationCode}`);pickDialog.value=false;await refreshDetail()}catch(e){fail(e,'扫码拣货失败')}finally{saving.value=false}}
function openPack(){if(!selected.value)return;packForm.carrierCode=selected.value.carrierCode??'';packForm.trackingCode=selected.value.trackingCode??'';packForm.remark='';packForm.lines.splice(0,packForm.lines.length,...selected.value.lines.filter(x=>Number(x.unshippedQty)>0).map(x=>({lineId:x.id,goodCode:x.goodCode,quantity:Number(x.unshippedQty),max:Number(x.unshippedQty)})));packDialog.value=true}
async function submitPack(){if(!selected.value)return;saving.value=true;try{const pkg=await packStockout(selected.value.id,{carrierCode:packForm.carrierCode,trackingCode:packForm.trackingCode,remark:packForm.remark,idempotencyKey:key(),lines:packForm.lines.filter(x=>x.quantity>0).map(x=>({lineId:x.lineId,quantity:x.quantity}))});ElMessage.success(`装箱完成：${pkg.packageCode}`);packDialog.value=false;await refreshDetail()}catch(e){fail(e,'装箱失败')}finally{saving.value=false}}
async function ship(packageId:number|null=null){if(!selected.value)return;try{await ElMessageBox.confirm(packageId?'确认发运该包裹？':'确认发运全部已拣未发数量？','确认发运',{type:'warning'});saving.value=true;const result=await shipStockout(selected.value.id,{packageId,idempotencyKey:key(),remark:'页面确认发运'});ElMessage.success(`发运成功：${result.operationCode}`);await refreshDetail()}catch(e){if(e!=='cancel')fail(e,'发运失败')}finally{saving.value=false}}
async function cancelAlloc(){if(!selected.value)return;try{await ElMessageBox.confirm('未发运的已分配库存将全部归还可用库存。','取消分配',{type:'warning'});await cancelAllocation(selected.value.id,{idempotencyKey:key(),remark:'页面取消分配'});ElMessage.success('分配已取消');await refreshDetail()}catch(e){if(e!=='cancel')fail(e,'取消分配失败')}}
async function cancelOrder(){if(!selected.value)return;try{await ElMessageBox.confirm('确认取消该出库单？未发运库存将自动释放。','取消出库单',{type:'warning'});await cancelStockout(selected.value.id,{idempotencyKey:key(),remark:'页面取消'});ElMessage.success('出库单已取消');await refreshDetail()}catch(e){if(e!=='cancel')fail(e,'取消出库单失败')}}
async function forceComplete(){if(!selected.value)return;try{await ElMessageBox.confirm('已拣数量将发运，未拣分配将释放，然后关闭订单。','强制完成',{type:'warning'});await completeStockout(selected.value.id,{idempotencyKey:key(),remark:'页面强制完成'});ElMessage.success('出库单已完成');await refreshDetail()}catch(e){if(e!=='cancel')fail(e,'强制完成失败')}}
async function reverse(){if(!selected.value)return;try{const code=await reverseStockout(selected.value.id,{idempotencyKey:key(),remark:`出库反单 ${selected.value.orderCode}`});ElMessage.success(`已生成退库入库单：${code}`);await refreshDetail()}catch(e){fail(e,'生成退库单失败')}}
function selectionChange(rows:StockoutOrderSummary[]){selectedRows.value=rows}
async function createWave(){const ids=selectedRows.value.filter(x=>x.state==='DRAFT'&&x.allocationState==='NO').map(x=>x.id);if(ids.length<2)return void ElMessage.warning('请选择至少两张未分配草稿出库单');try{const wave=await createStockoutWave({orderIds:ids,remark:'页面创建波次',idempotencyKey:key()});ElMessage.success(`波次已创建：${wave.waveCode}`);activeView.value='waves';await load()}catch(e){fail(e,'创建波次失败')}}
async function waveAllocate(wave:StockoutWave){try{await allocateStockoutWave(wave.id,{allowPartial:false,idempotencyKey:key(),remark:'波次整单分配'});ElMessage.success('波次分配完成');await load()}catch(e){fail(e,'波次分配失败')}}
async function wavePick(wave:StockoutWave){try{await pickStockoutWave(wave.id,{idempotencyKey:key(),remark:'波次快速拣货'});ElMessage.success('波次拣货完成');await load()}catch(e){fail(e,'波次拣货失败')}}
onMounted(load)
</script>

<template>
  <div class="page-stack">
    <header class="page-heading"><div><p class="eyebrow">OUTBOUND OPERATIONS</p><h1>出库管理</h1><p>从库存分配、扫码拣货、装箱到发运扣账的完整出库链路。</p></div><div class="heading-actions"><el-button @click="load">刷新</el-button><el-button :disabled="selectedRows.length<2" @click="createWave">创建波次</el-button><el-button type="primary" @click="openCreate">新建出库单</el-button></div></header>
    <section class="out-stats"><div><span>出库单数</span><strong>{{ orders.length }}</strong></div><div><span>待处理</span><strong class="warning">{{ pendingCount }}</strong></div><div><span>已完成</span><strong>{{ completedCount }}</strong></div><div><span>累计发运</span><strong>{{ qty(shippedTotal) }}</strong></div></section>
    <el-tabs v-model="activeView"><el-tab-pane :label="`出库单 ${orders.length}`" name="orders" /><el-tab-pane :label="`波次 ${waves.length}`" name="waves" /></el-tabs>
    <section v-if="activeView==='orders'" class="panel"><el-table v-loading="loading" :data="orders" stripe @selection-change="selectionChange" @row-dblclick="rowDblclick"><el-table-column type="selection" width="46" /><el-table-column prop="orderCode" label="出库单号" min-width="135" /><el-table-column prop="externalOrderCode" label="外部单号" min-width="120"><template #default="s">{{ s.row.externalOrderCode||'-' }}</template></el-table-column><el-table-column label="类型" min-width="110"><template #default="s">{{ typeText[s.row.outboundType]||s.row.outboundType }}</template></el-table-column><el-table-column prop="partnerName" label="客户/伙伴" min-width="125"><template #default="s">{{ s.row.partnerName||'-' }}</template></el-table-column><el-table-column label="发运进度" min-width="160"><template #default="s"><el-progress :percentage="percent(s.row)" :status="s.row.state==='COMPLETED'?'success':undefined" /></template></el-table-column><el-table-column label="计划/发运" width="115" align="right"><template #default="s">{{ qty(s.row.plannedQty) }} / {{ qty(s.row.shippedQty) }}</template></el-table-column><el-table-column label="分配/拣货" width="130"><template #default="s">{{ progressText[s.row.allocationState] }} / {{ progressText[s.row.pickState] }}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.state==='COMPLETED'?'success':s.row.state==='CANCELLED'?'info':s.row.state==='PROCESSING'?'warning':'primary'">{{ stateText[s.row.state] }}</el-tag></template></el-table-column><el-table-column label="创建时间" min-width="160"><template #default="s">{{ time(s.row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="80" fixed="right"><template #default="s"><el-button link type="primary" @click="openDetail(s.row.id)">详情</el-button></template></el-table-column></el-table></section>
    <section v-else class="panel"><el-table :data="waves" stripe><el-table-column prop="waveCode" label="波次号" min-width="140" /><el-table-column prop="orderCount" label="订单数" /><el-table-column label="包含订单" min-width="300"><template #default="s">{{ s.row.orderCodes.join('、') }}</template></el-table-column><el-table-column prop="state" label="状态" /><el-table-column prop="remark" label="备注" /><el-table-column label="创建时间" min-width="160"><template #default="s">{{ time(s.row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="180"><template #default="s"><el-button v-if="s.row.state==='DRAFT'" link type="primary" @click="waveAllocate(s.row)">整波分配</el-button><el-button v-if="s.row.state==='ALLOCATED'" link type="success" @click="wavePick(s.row)">整波拣货</el-button></template></el-table-column></el-table></section>

    <el-drawer v-model="drawer" :title="selected?`出库单 ${selected.orderCode}`:'出库单详情'" size="80%"><template v-if="selected"><div class="detail-head"><div><span>订单状态</span><strong>{{ stateText[selected.state] }}</strong></div><div><span>分配 / 拣货 / 发运</span><strong>{{ progressText[selected.allocationState] }} / {{ progressText[selected.pickState] }} / {{ progressText[selected.shipState] }}</strong></div><div><span>计划数量</span><strong>{{ qty(selected.plannedQty) }}</strong></div><div><span>已发数量</span><strong>{{ qty(selected.shippedQty) }}</strong></div></div><el-alert v-if="selected.transferInOrderCode" :title="`已关联调拨入库单：${selected.transferInOrderCode}`" type="info" :closable="false" show-icon /><div class="drawer-actions"><el-button v-if="['DRAFT','PROCESSING'].includes(selected.state)&&selected.allocationState!=='FULL'" type="primary" plain @click="allocate">自动分配</el-button><el-button v-if="['PARTIAL','FULL'].includes(selected.allocationState)&&selected.pickState!=='FULL'" type="success" plain @click="pickAll">快速拣货</el-button><el-button v-if="Number(selected.pickedQty)>Number(selected.shippedQty)" @click="openPack">装箱</el-button><el-button v-if="Number(selected.pickedQty)>Number(selected.shippedQty)" type="success" @click="ship(null)">发运已拣货品</el-button><el-button v-if="selected.allocationState!=='NO'&&selected.shipState==='NO'" type="warning" plain @click="cancelAlloc">取消分配</el-button><el-button v-if="['DRAFT','PROCESSING'].includes(selected.state)" type="warning" plain @click="forceComplete">强制完成</el-button><el-button v-if="['DRAFT','PROCESSING'].includes(selected.state)" type="danger" plain @click="cancelOrder">取消订单</el-button><el-button v-if="selected.state==='COMPLETED'" type="primary" plain @click="reverse">生成退库单</el-button></div>
      <el-tabs v-model="drawerTab"><el-tab-pane :label="`出库明细 ${selected.lines.length}`" name="lines" /><el-tab-pane :label="`分配明细 ${allocations.length}`" name="allocations" /><el-tab-pane :label="`包裹 ${packages.length}`" name="packages" /><el-tab-pane :label="`作业流水 ${events.length}`" name="events" /></el-tabs>
      <el-table v-if="drawerTab==='lines'" :data="selected.lines" stripe><el-table-column prop="lineNo" label="行" width="55" /><el-table-column prop="goodCode" label="货品编码" /><el-table-column prop="goodName" label="货品名称" min-width="140" /><el-table-column label="计划" align="right"><template #default="s">{{ qty(s.row.plannedQty) }}</template></el-table-column><el-table-column label="已分配" align="right"><template #default="s">{{ qty(s.row.allocatedQty) }}</template></el-table-column><el-table-column label="已拣" align="right"><template #default="s">{{ qty(s.row.pickedQty) }}</template></el-table-column><el-table-column label="已发" align="right"><template #default="s">{{ qty(s.row.shippedQty) }}</template></el-table-column><el-table-column prop="batchCode" label="指定批次" /><el-table-column label="操作" width="90"><template #default="s"><el-button v-if="Number(s.row.unpickedQty)>0" link type="primary" @click="openPick(s.row)">扫码拣货</el-button></template></el-table-column></el-table>
      <el-table v-else-if="drawerTab==='allocations'" :data="allocations" stripe><el-table-column prop="goodCode" label="货品" /><el-table-column prop="locationCode" label="来源库位" /><el-table-column prop="batchCode" label="批次" /><el-table-column prop="lpn" label="LPN" /><el-table-column prop="allocatedQty" label="分配" /><el-table-column prop="pickedQty" label="拣货" /><el-table-column prop="shippedQty" label="发运" /><el-table-column prop="state" label="状态" /></el-table>
      <el-table v-else-if="drawerTab==='packages'" :data="packages" stripe><el-table-column prop="packageCode" label="包裹号" /><el-table-column prop="carrierCode" label="承运商" /><el-table-column prop="trackingCode" label="运单号" /><el-table-column label="货品明细" min-width="220"><template #default="s">{{ s.row.lines.map((x:any)=>`${x.goodCode}×${qty(x.quantity)}`).join('、') }}</template></el-table-column><el-table-column prop="state" label="状态" /><el-table-column label="操作" width="80"><template #default="s"><el-button v-if="s.row.state==='OPEN'" link type="success" @click="ship(s.row.id)">发运</el-button></template></el-table-column></el-table>
      <el-table v-else :data="events" stripe><el-table-column prop="eventType" label="动作" /><el-table-column prop="operationCode" label="操作单号" /><el-table-column prop="goodCode" label="货品" /><el-table-column prop="locationCode" label="库位" /><el-table-column prop="quantity" label="数量" /><el-table-column prop="operatorName" label="操作人" /><el-table-column label="时间" min-width="160"><template #default="s">{{ time(s.row.createdAt) }}</template></el-table-column></el-table>
    </template></el-drawer>

    <el-dialog v-model="createDialog" title="新建出库单" width="940px"><el-form label-position="top"><div class="form-grid three"><el-form-item label="出库类型"><el-select v-model="createForm.outboundType" style="width:100%"><el-option v-for="x in typeOptions" :key="x[0]" :label="x[1]" :value="x[0]" /></el-select></el-form-item><el-form-item label="外部单号"><el-input v-model="createForm.externalOrderCode" /></el-form-item><el-form-item label="计划日期"><el-date-picker v-model="createForm.plannedDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></div><div class="form-grid three"><el-form-item label="客户/合作伙伴"><el-select v-model="createForm.partnerCode" clearable filterable style="width:100%"><el-option v-for="x in partners" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select></el-form-item><el-form-item label="收货人"><el-input v-model="createForm.receiverName" /></el-form-item><el-form-item label="联系电话"><el-input v-model="createForm.receiverPhone" /></el-form-item></div><el-form-item label="收货地址"><el-input v-model="createForm.receiverAddress" /></el-form-item><div v-if="createForm.outboundType==='TRANSFER'" class="form-grid"><el-form-item label="目标仓库"><el-select v-model="createForm.targetWarehouseCode" style="width:100%"><el-option v-for="x in warehouseOptions" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select></el-form-item><el-form-item label="目标货主"><el-select v-model="createForm.targetOwnerCode" style="width:100%"><el-option v-for="x in ownerOptions" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select></el-form-item></div><div class="line-title"><strong>出库明细</strong><el-button link type="primary" @click="createForm.lines.push(blankLine())">＋ 添加明细</el-button></div><div v-for="(line,index) in createForm.lines" :key="index" class="draft-line"><el-select v-model="line.goodCode" filterable placeholder="货品"><el-option v-for="x in goods" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select><el-input-number v-model="line.plannedQty" :min="0.001" :precision="3" /><el-input v-model="line.batchCode" placeholder="指定批次（可选）" /><el-input v-model="line.supplierCode" placeholder="指定供应商（可选）" /><el-input-number v-model="line.unitPrice" :min="0" :precision="4" /><el-button link type="danger" :disabled="createForm.lines.length===1" @click="createForm.lines.splice(index,1)">删除</el-button></div><el-form-item label="备注"><el-input v-model="createForm.remark" /></el-form-item></el-form><template #footer><el-button @click="createDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitCreate">创建出库单</el-button></template></el-dialog>

    <el-dialog v-model="pickDialog" title="扫码 / RFID 拣货" width="620px"><p v-if="pickingLine" class="context-box">{{ pickingLine.goodCode }} · {{ pickingLine.goodName }} / 已分配未拣 {{ qty(pickingLine.unpickedQty) }}</p><el-form label-position="top"><div class="form-grid"><el-form-item label="货品条码"><el-input v-model="pickForm.barcode" /></el-form-item><el-form-item label="拣货数量"><el-input-number v-model="pickForm.quantity" :min="0.001" :max="Number(pickingLine?.unpickedQty??0)" :precision="3" style="width:100%" /></el-form-item></div><el-form-item label="RFID/唯一标签"><el-input v-model="pickForm.serialText" type="textarea" :rows="3" placeholder="可选，多个标签用换行或逗号分隔" /></el-form-item><el-form-item label="备注"><el-input v-model="pickForm.remark" /></el-form-item></el-form><template #footer><el-button @click="pickDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitPick">确认拣货</el-button></template></el-dialog>

    <el-dialog v-model="packDialog" title="创建包裹" width="680px"><el-form label-position="top"><div class="form-grid"><el-form-item label="承运商代码"><el-input v-model="packForm.carrierCode" /></el-form-item><el-form-item label="运单号"><el-input v-model="packForm.trackingCode" /></el-form-item></div><div v-for="line in packForm.lines" :key="line.lineId" class="pack-line"><span>{{ line.goodCode }}</span><el-input-number v-model="line.quantity" :min="0" :max="line.max" :precision="3" /></div><el-form-item label="备注"><el-input v-model="packForm.remark" /></el-form-item></el-form><template #footer><el-button @click="packDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitPack">确认装箱</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.heading-actions{display:flex;gap:10px}.out-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.out-stats>div{background:var(--el-bg-color);border:1px solid var(--el-border-color-lighter);border-radius:12px;padding:17px 20px;display:flex;align-items:center;justify-content:space-between}.out-stats span{color:var(--el-text-color-secondary);font-size:13px}.out-stats strong{font-size:24px;color:#183c65}.out-stats .warning{color:#d77a16}.detail-head{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.detail-head>div{background:#f2f6fa;padding:13px;border-radius:9px}.detail-head span{display:block;color:#708399;font-size:12px;margin-bottom:4px}.drawer-actions{display:flex;justify-content:flex-end;flex-wrap:wrap;gap:8px;margin:12px 0}.form-grid.three{grid-template-columns:repeat(3,1fr)}.line-title{display:flex;align-items:center;justify-content:space-between;margin:4px 0 12px}.draft-line{display:grid;grid-template-columns:1.5fr 1fr 1fr 1fr 1fr auto;gap:9px;margin-bottom:10px}.context-box{background:#f2f6fa;color:#45627f;border-radius:8px;padding:12px 14px}.pack-line{display:flex;align-items:center;justify-content:space-between;background:#f6f8fa;border-radius:8px;padding:9px 12px;margin-bottom:8px}@media(max-width:900px){.out-stats,.detail-head{grid-template-columns:repeat(2,1fr)}.draft-line{grid-template-columns:1fr 1fr}}
</style>
