<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ApiError } from '@/api/http'
import { listMasterData, type MasterItem } from '@/api/masterData'
import { cancelStockin, completeStockin, createStockinOrder, getStockinOrder, listStockinOrders, listStockinReceipts, quickStockin, receiveStockin, type StockinLine, type StockinOrderDetail, type StockinOrderSummary, type StockinReceipt } from '@/api/stockin'

const orders=ref<StockinOrderSummary[]>([]),goods=ref<MasterItem[]>([]),locations=ref<MasterItem[]>([]),partners=ref<MasterItem[]>([]),receipts=ref<StockinReceipt[]>([])
const loading=ref(false),saving=ref(false),createDialog=ref(false),quickDialog=ref(false),receiveDialog=ref(false),drawer=ref(false),drawerTab=ref('lines')
const selected=ref<StockinOrderDetail|null>(null),receivingLine=ref<StockinLine|null>(null)
const typeOptions=[['PURCHASE','采购入库'],['RETURN','退货入库'],['TRANSFER','调拨入库'],['PRODUCE','生产入库'],['MATERIAL_RETURN','退料入库'],['FIX','维修入库'],['BORROW_RETURN','借用归还'],['NORMAL','普通入库'],['CONSIGN','寄售入库'],['CUSTOM','自定义入库'],['COOP_RETURN','协作退还'],['PRODUCE_RETURN','生产配料退回']]
const stateText:Record<string,string>={DRAFT:'待收货',RECEIVING:'收货中',COMPLETED:'已完成',CANCELLED:'已取消'}
const typeText=Object.fromEntries(typeOptions)
type DraftLine={goodCode:string;plannedQty:number;preferredLocationCode:string;supplierCode:string;qualityType:string;batchCode:string;unitPrice:number;remark:string}
const createForm=reactive<{inboundType:string;source:string;externalOrderCode:string;partnerCode:string;plannedDate:string;remark:string;lines:DraftLine[]}>({inboundType:'PURCHASE',source:'CUSTOM',externalOrderCode:'',partnerCode:'',plannedDate:'',remark:'',lines:[]})
const receiveForm=reactive({quantity:1,locationCode:'STAGE',lpn:'',serialText:'',allowOverReceipt:false,remark:''})
const quickForm=reactive({inboundType:'NORMAL',goodCode:'',quantity:1,locationCode:'STAGE',partnerCode:'',supplierCode:'',qualityType:'ZP',batchCode:'',lpn:'',unitPrice:0,serialText:'',remark:''})
const pendingCount=computed(()=>orders.value.filter(x=>['DRAFT','RECEIVING'].includes(x.state)).length)
const completedCount=computed(()=>orders.value.filter(x=>x.state==='COMPLETED').length)
const receivedTotal=computed(()=>orders.value.reduce((sum,x)=>sum+Number(x.receivedQty),0))

function key(){return globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`}
function fail(reason:unknown,fallback:string){ElMessage.error(reason instanceof ApiError?reason.message:fallback)}
function qty(value:number){return Number(value).toLocaleString('zh-CN',{maximumFractionDigits:3})}
function money(value:number){return Number(value).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function time(value?:string){return value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'-'}
function progress(row:StockinOrderSummary){return Number(row.plannedQty)>0?Math.min(100,Math.round(Number(row.receivedQty)*100/Number(row.plannedQty))):0}
function serials(value:string){return value.split(/[\s,，;；]+/).map(x=>x.trim()).filter(Boolean)}
async function load(){loading.value=true;try{[orders.value,goods.value,locations.value,partners.value]=await Promise.all([listStockinOrders(),listMasterData('goods'),listMasterData('locations'),listMasterData('partners')])}catch(e){fail(e,'入库数据加载失败')}finally{loading.value=false}}
function blankLine():DraftLine{return{goodCode:goods.value[0]?.code??'',plannedQty:1,preferredLocationCode:'STAGE',supplierCode:'',qualityType:'ZP',batchCode:'',unitPrice:0,remark:''}}
function openCreate(){Object.assign(createForm,{inboundType:'PURCHASE',source:'CUSTOM',externalOrderCode:'',partnerCode:'',plannedDate:'',remark:'',lines:[blankLine()]});createDialog.value=true}
function addLine(){createForm.lines.push(blankLine())}
async function submitCreate(){if(!createForm.lines.length)return void ElMessage.warning('至少添加一条入库明细');saving.value=true;try{const order=await createStockinOrder({...createForm,plannedDate:createForm.plannedDate||null,idempotencyKey:key()});ElMessage.success(`入库单已创建：${order.orderCode}`);createDialog.value=false;await load();await openDetail(order.id)}catch(e){fail(e,'入库单创建失败')}finally{saving.value=false}}
async function openDetail(id:number){try{[selected.value,receipts.value]=await Promise.all([getStockinOrder(id),listStockinReceipts(id)]);drawerTab.value='lines';drawer.value=true}catch(e){fail(e,'入库单详情加载失败')}}
function rowDblclick(row:StockinOrderSummary){void openDetail(row.id)}
function openReceive(line:StockinLine){receivingLine.value=line;Object.assign(receiveForm,{quantity:Math.max(0.001,Number(line.remainingQty)),locationCode:line.preferredLocationCode||'STAGE',lpn:'',serialText:'',allowOverReceipt:false,remark:''});receiveDialog.value=true}
async function submitReceive(){if(!selected.value||!receivingLine.value)return;saving.value=true;try{const result=await receiveStockin(selected.value.id,{idempotencyKey:key(),allowOverReceipt:receiveForm.allowOverReceipt,lines:[{lineId:receivingLine.value.id,quantity:receiveForm.quantity,locationCode:receiveForm.locationCode,lpn:receiveForm.lpn,serialCodes:serials(receiveForm.serialText),remark:receiveForm.remark}]});ElMessage.success(`收货成功：${result.operationCode}`);receiveDialog.value=false;await load();await openDetail(result.order.id)}catch(e){fail(e,'收货失败')}finally{saving.value=false}}
function openQuick(){Object.assign(quickForm,{inboundType:'NORMAL',goodCode:goods.value[0]?.code??'',quantity:1,locationCode:'STAGE',partnerCode:'',supplierCode:'',qualityType:'ZP',batchCode:'',lpn:'',unitPrice:0,serialText:'',remark:''});quickDialog.value=true}
async function submitQuick(){saving.value=true;try{const result=await quickStockin({...quickForm,serialCodes:serials(quickForm.serialText),idempotencyKey:key()});ElMessage.success(`快捷入库完成：${result.order.orderCode}`);quickDialog.value=false;await load()}catch(e){fail(e,'快捷入库失败')}finally{saving.value=false}}
async function forceComplete(){if(!selected.value)return;try{await ElMessageBox.confirm('将保留已收数量并关闭剩余未收数量，确认完成？','强制完成',{type:'warning'});selected.value=await completeStockin(selected.value.id,{idempotencyKey:key(),remark:'手动完成'});ElMessage.success('入库单已完成');await load()}catch(e){if(e!=='cancel')fail(e,'完成入库单失败')}}
async function cancelOrder(){if(!selected.value)return;try{await ElMessageBox.confirm('取消后不再允许收货，已收库存保留。','取消入库单',{type:'warning'});selected.value=await cancelStockin(selected.value.id,{idempotencyKey:key(),remark:'手动取消'});ElMessage.success('入库单已取消');await load()}catch(e){if(e!=='cancel')fail(e,'取消入库单失败')}}
onMounted(load)
</script>

<template>
  <div class="page-stack">
    <header class="page-heading"><div><p class="eyebrow">INBOUND OPERATIONS</p><h1>入库管理</h1><p>从预期到货、分批收货到库存入账的完整入库链路。</p></div><div class="heading-actions"><el-button @click="load">刷新</el-button><el-button @click="openQuick">快捷入库</el-button><el-button type="primary" @click="openCreate">新建入库单</el-button></div></header>
    <section class="stockin-stats"><div><span>入库单数</span><strong>{{ orders.length }}</strong></div><div><span>待处理</span><strong class="warning">{{ pendingCount }}</strong></div><div><span>已完成</span><strong>{{ completedCount }}</strong></div><div><span>累计实收</span><strong>{{ qty(receivedTotal) }}</strong></div></section>
    <section class="panel"><el-table v-loading="loading" :data="orders" stripe @row-dblclick="rowDblclick"><el-table-column prop="orderCode" label="入库单号" min-width="145" /><el-table-column prop="externalOrderCode" label="外部单号" min-width="125"><template #default="s">{{ s.row.externalOrderCode||'-' }}</template></el-table-column><el-table-column label="类型" min-width="115"><template #default="s">{{ typeText[s.row.inboundType]||s.row.inboundType }}</template></el-table-column><el-table-column prop="partnerName" label="供应商/合作伙伴" min-width="145"><template #default="s">{{ s.row.partnerName||'-' }}</template></el-table-column><el-table-column label="收货进度" min-width="180"><template #default="s"><el-progress :percentage="progress(s.row)" :status="s.row.state==='COMPLETED'?'success':undefined" /></template></el-table-column><el-table-column label="计划/实收" width="120" align="right"><template #default="s">{{ qty(s.row.plannedQty) }} / {{ qty(s.row.receivedQty) }}</template></el-table-column><el-table-column label="金额" width="110" align="right"><template #default="s">¥{{ money(s.row.totalAmount) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.state==='COMPLETED'?'success':s.row.state==='CANCELLED'?'info':s.row.state==='RECEIVING'?'warning':'primary'">{{ stateText[s.row.state]||s.row.state }}</el-tag></template></el-table-column><el-table-column label="创建时间" min-width="165"><template #default="s">{{ time(s.row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="s"><el-button link type="primary" @click="openDetail(s.row.id)">详情</el-button></template></el-table-column></el-table></section>

    <el-drawer v-model="drawer" :title="selected?`入库单 ${selected.orderCode}`:'入库单详情'" size="76%"><template v-if="selected"><div class="detail-head"><div><span>类型</span><strong>{{ typeText[selected.inboundType] }}</strong></div><div><span>状态</span><strong>{{ stateText[selected.state] }}</strong></div><div><span>计划数量</span><strong>{{ qty(selected.plannedQty) }}</strong></div><div><span>实收数量</span><strong>{{ qty(selected.receivedQty) }}</strong></div></div><div v-if="['DRAFT','RECEIVING'].includes(selected.state)" class="drawer-actions"><el-button type="warning" plain @click="forceComplete">强制完成</el-button><el-button type="danger" plain @click="cancelOrder">取消入库单</el-button></div><el-tabs v-model="drawerTab"><el-tab-pane :label="`入库明细 ${selected.lines.length}`" name="lines" /><el-tab-pane :label="`收货记录 ${receipts.length}`" name="receipts" /></el-tabs><el-table v-if="drawerTab==='lines'" :data="selected.lines" stripe><el-table-column prop="lineNo" label="行号" width="70" /><el-table-column prop="goodCode" label="货品编码" min-width="115" /><el-table-column prop="goodName" label="货品名称" min-width="150" /><el-table-column prop="batchCode" label="批次" min-width="100" /><el-table-column prop="preferredLocationCode" label="预收库位" min-width="100" /><el-table-column label="计划" align="right"><template #default="s">{{ qty(s.row.plannedQty) }}</template></el-table-column><el-table-column label="已收" align="right"><template #default="s">{{ qty(s.row.receivedQty) }}</template></el-table-column><el-table-column label="未收" align="right"><template #default="s"><strong>{{ qty(s.row.remainingQty) }}</strong></template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button v-if="['DRAFT','RECEIVING'].includes(selected.state)" link type="primary" @click="openReceive(s.row)">收货</el-button></template></el-table-column></el-table><el-table v-else :data="receipts" stripe><el-table-column prop="operationCode" label="收货单号" min-width="135" /><el-table-column prop="goodCode" label="货品" /><el-table-column prop="locationCode" label="库位" /><el-table-column label="数量" align="right"><template #default="s">{{ qty(s.row.quantity) }}</template></el-table-column><el-table-column prop="batchCode" label="批次" /><el-table-column prop="serialCount" label="标签数" /><el-table-column prop="operatorName" label="操作人" /><el-table-column label="时间" min-width="165"><template #default="s">{{ time(s.row.createdAt) }}</template></el-table-column></el-table></template></el-drawer>

    <el-dialog v-model="createDialog" title="新建入库单" width="900px"><el-form label-position="top"><div class="form-grid three"><el-form-item label="入库类型"><el-select v-model="createForm.inboundType" style="width:100%"><el-option v-for="x in typeOptions" :key="x[0]" :label="x[1]" :value="x[0]" /></el-select></el-form-item><el-form-item label="外部单号"><el-input v-model="createForm.externalOrderCode" placeholder="可选，同一业务范围不可重复" /></el-form-item><el-form-item label="预计到货"><el-date-picker v-model="createForm.plannedDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></div><div class="form-grid"><el-form-item label="供应商/合作伙伴"><el-select v-model="createForm.partnerCode" clearable filterable style="width:100%"><el-option v-for="x in partners" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select></el-form-item><el-form-item label="备注"><el-input v-model="createForm.remark" /></el-form-item></div><div class="line-title"><strong>入库明细</strong><el-button link type="primary" @click="addLine">＋ 添加明细</el-button></div><div v-for="(line,index) in createForm.lines" :key="index" class="draft-line"><el-select v-model="line.goodCode" filterable placeholder="货品"><el-option v-for="x in goods" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select><el-input-number v-model="line.plannedQty" :min="0.001" :precision="3" placeholder="数量" /><el-select v-model="line.preferredLocationCode" filterable placeholder="预收库位"><el-option v-for="x in locations" :key="x.id" :label="x.code" :value="x.code" /></el-select><el-input v-model="line.batchCode" placeholder="批次（可选）" /><el-input-number v-model="line.unitPrice" :min="0" :precision="4" placeholder="单价" /><el-button link type="danger" :disabled="createForm.lines.length===1" @click="createForm.lines.splice(index,1)">删除</el-button></div></el-form><template #footer><el-button @click="createDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitCreate">创建入库单</el-button></template></el-dialog>

    <el-dialog v-model="receiveDialog" title="入库收货" width="620px"><p v-if="receivingLine" class="context-box">{{ receivingLine.goodCode }} · {{ receivingLine.goodName }} / 未收 {{ qty(receivingLine.remainingQty) }}</p><el-form label-position="top"><div class="form-grid"><el-form-item label="本次收货数量"><el-input-number v-model="receiveForm.quantity" :min="0.001" :precision="3" style="width:100%" /></el-form-item><el-form-item label="收货库位"><el-select v-model="receiveForm.locationCode" filterable style="width:100%"><el-option v-for="x in locations" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select></el-form-item></div><el-form-item label="LPN/容器号"><el-input v-model="receiveForm.lpn" /></el-form-item><el-form-item label="RFID/唯一标签"><el-input v-model="receiveForm.serialText" type="textarea" :rows="3" placeholder="可选，多个标签用换行或逗号分隔" /></el-form-item><div class="form-grid"><el-form-item label="备注"><el-input v-model="receiveForm.remark" /></el-form-item><el-form-item label="收货策略"><el-checkbox v-model="receiveForm.allowOverReceipt">允许超收</el-checkbox></el-form-item></div></el-form><template #footer><el-button @click="receiveDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitReceive">确认收货</el-button></template></el-dialog>

    <el-dialog v-model="quickDialog" title="快捷入库" width="680px"><el-alert title="快捷入库会自动创建并完成一张入库单。" type="info" :closable="false" show-icon /><el-form label-position="top" class="quick-form"><div class="form-grid"><el-form-item label="入库类型"><el-select v-model="quickForm.inboundType" style="width:100%"><el-option v-for="x in typeOptions" :key="x[0]" :label="x[1]" :value="x[0]" /></el-select></el-form-item><el-form-item label="货品"><el-select v-model="quickForm.goodCode" filterable style="width:100%"><el-option v-for="x in goods" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select></el-form-item></div><div class="form-grid"><el-form-item label="数量"><el-input-number v-model="quickForm.quantity" :min="0.001" :precision="3" style="width:100%" /></el-form-item><el-form-item label="库位"><el-select v-model="quickForm.locationCode" filterable style="width:100%"><el-option v-for="x in locations" :key="x.id" :label="`${x.code} · ${x.name}`" :value="x.code" /></el-select></el-form-item></div><div class="form-grid"><el-form-item label="批次"><el-input v-model="quickForm.batchCode" /></el-form-item><el-form-item label="LPN/容器号"><el-input v-model="quickForm.lpn" /></el-form-item></div><el-form-item label="RFID/唯一标签"><el-input v-model="quickForm.serialText" type="textarea" :rows="3" placeholder="可选，多个标签用换行或逗号分隔" /></el-form-item><el-form-item label="备注"><el-input v-model="quickForm.remark" /></el-form-item></el-form><template #footer><el-button @click="quickDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitQuick">确认快捷入库</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.heading-actions{display:flex;gap:10px}.stockin-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.stockin-stats>div{background:var(--el-bg-color);border:1px solid var(--el-border-color-lighter);border-radius:12px;padding:17px 20px;display:flex;align-items:center;justify-content:space-between}.stockin-stats span{color:var(--el-text-color-secondary);font-size:13px}.stockin-stats strong{font-size:24px;color:#183c65}.stockin-stats .warning{color:#d77a16}.detail-head{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.detail-head>div{background:#f2f6fa;padding:13px;border-radius:9px}.detail-head span{display:block;color:#708399;font-size:12px;margin-bottom:4px}.drawer-actions{display:flex;justify-content:flex-end;margin-bottom:10px}.form-grid.three{grid-template-columns:repeat(3,1fr)}.line-title{display:flex;align-items:center;justify-content:space-between;margin:4px 0 12px}.draft-line{display:grid;grid-template-columns:1.5fr 1fr 1.1fr 1fr 1fr auto;gap:9px;margin-bottom:10px}.context-box{background:#f2f6fa;color:#45627f;border-radius:8px;padding:12px 14px}.quick-form{margin-top:18px}@media(max-width:900px){.stockin-stats,.detail-head{grid-template-columns:repeat(2,1fr)}.draft-line{grid-template-columns:1fr 1fr}}
</style>
