-- 第五幕共享库影子迁移（REQ-051～062/073/074）。
create table e_cost_record_act5 (
  id                 bigint(20)    not null auto_increment comment '主键',
  object_type        varchar(16)   not null                comment '对象类型（area/equipment/system）',
  object_id          bigint(20)    default null            comment '对象ID',
  normalized_object_id bigint(20)  generated always as (ifnull(object_id, 0)) stored comment '唯一键对象ID（system空ID归一为0）',
  stat_month         char(7)       not null                comment '统计月份（YYYY-MM）',
  energy_type_code   varchar(32)   not null                comment '能源类型',
  cost_version       int(6)        not null default 1      comment '成本版本（接口展示为v1/v2）',
  is_current         tinyint(1)    not null default 1      comment '是否当前版本（0否 1是）',
  current_guard      varchar(160)  generated always as (case when is_current = 1 then concat(object_type, ':', ifnull(object_id, 0), ':', stat_month, ':', energy_type_code) else null end) stored comment '仅current行生成的业务唯一键',
  usage_qty          decimal(20,4) default 0               comment '合格用量',
  peak_qty           decimal(20,4) default 0               comment '峰段用量',
  flat_qty           decimal(20,4) default 0               comment '平段用量',
  valley_qty         decimal(20,4) default 0               comment '谷段用量',
  peak_cost          decimal(20,4) default 0               comment '峰段成本',
  flat_cost          decimal(20,4) default 0               comment '平段成本',
  valley_cost        decimal(20,4) default 0               comment '谷段成本',
  total_cost         decimal(20,4) default 0               comment '总成本',
  tariff_version_no  varchar(64)   default null            comment '单价版本快照（多档拼接便于追溯）',
  alloc_rule_version_no varchar(64) default null           comment '分摊规则版本快照',
  formula_version    varchar(64)   not null                comment '成本计算公式版本',
  tariff_snapshot_json longtext    not null                comment '实际参与计算的单价冻结快照（json）',
  alloc_rule_snapshot_json longtext not null               comment '实际参与计算的分摊规则冻结快照（json）',
  source_stat_snapshot_json longtext not null              comment '来源统计版本与质量冻结快照（json）',
  status             varchar(16)   default 'draft'         comment '状态（draft测算/pendingReview待复核/reviewed已复核/frozen已冻结/pendingRecompute重算待复核/void已作废）',
  reviewed_at        datetime      default null            comment '复核时间',
  signature          varchar(96)   not null                comment '完整版本化成本签名（COST-SHA256-V1:<64hex>，REQ-062）',
  computed_by        varchar(64)   not null                comment '计算账号/任务标识',
  computed_at        datetime      default null            comment '计算时间',
  frozen_at          datetime      default null            comment '冻结时间',
  primary key (id),
  unique key uk_cost_version (object_type, normalized_object_id, stat_month, energy_type_code, cost_version),
  unique key uk_cost_current (current_guard),
  key idx_month_status (stat_month, status)
) engine=innodb auto_increment=1 comment = '月度成本版本记录';

create table e_cost_recompute_record (
  recompute_id       bigint(20)    not null auto_increment comment '成本重算记录ID',
  period_key         varchar(64)   not null                comment '重算周期业务键',
  stat_month         char(7)       not null                comment '统计月份（YYYY-MM）',
  energy_type_code   varchar(32)   not null                comment '能源类型',
  scope              varchar(64)   not null                comment '完整重算范围',
  old_cost_version   int(6)        not null                comment '旧成本版本',
  new_cost_version   int(6)        not null                comment '新成本版本',
  trigger_reason     varchar(255)  not null                comment '重算触发原因',
  trigger_type       varchar(32)   not null                comment '触发类型',
  triggered_by       varchar(64)   not null                comment '发起账号',
  triggered_at       datetime      not null                comment '发起时间',
  tariff_snapshot_json longtext    not null                comment '重算实际采用的单价冻结快照（json）',
  alloc_rule_snapshot_json longtext not null               comment '重算实际采用的分摊规则冻结快照（json）',
  diff_summary_json  longtext      not null                comment '按对象冻结的版本差异（json）',
  review_status      varchar(16)   not null default 'pending' comment '复核状态（pending/approved/rejected）',
  reviewed_by        varchar(64)   default null            comment '复核账号',
  reviewed_at        datetime      default null            comment '复核时间',
  review_remark      varchar(255)  default null            comment '复核意见',
  primary key (recompute_id),
  key idx_recompute_period (stat_month, energy_type_code, review_status)
) engine=innodb auto_increment=1 comment = '成本重算版本差异记录';

create table e_report_archive (
  archive_id         bigint(20)    not null auto_increment comment '报表归档ID',
  template_code      varchar(64)   not null                comment '报表模板编码',
  template_version   varchar(32)   not null                comment '报表模板版本',
  period_start       date          not null                comment '报告周期起',
  period_end         date          not null                comment '报告周期止',
  filters_snapshot_json longtext   not null                comment '规范化查询条件冻结快照（json）',
  payload_snapshot_json longtext   not null                comment '完整 canonical report payload（json）',
  version_snapshots_json longtext  not null                comment '实际参与的业务版本冻结快照（json）',
  full_signature     varchar(96)   not null                comment '完整报表签名（REPORT-SHA256-V1:<64hex>，REQ-062）',
  generated_at       datetime      not null                comment '系统统计时钟生成时间',
  archived_by        varchar(64)   not null                comment '归档账号',
  archived_at        datetime      not null                comment '归档时间',
  primary key (archive_id),
  key idx_report_archive_period (template_code, period_start, period_end)
) engine=innodb auto_increment=1 comment = '报表快照归档';
