// 交付治理控制台：展示真实运行状态、外部依赖、权限设计、审批、操作审计和审计包。
const DELIVERY_PAGES=new Set(['external-api','iam','dictionaries','approvals','audit-logs','audit-package','service-ops']);
state.delivery={status:null,readiness:null,capabilities:[],auditLogs:[],health:null,loading:false,error:'',requestSeq:0,demoRole:'设备工程师'};

// Demo阶段通过请求头给审计日志补充操作者和角色；生产环境应由统一认证网关注入可信身份。
const deliveryRoleCodes={'系统管理员':'system-admin','设备管理员':'asset-admin','设备工程师':'device-engineer','维修技师':'maintenance-technician','数据管理员':'data-admin','审计员':'auditor'};
const baseApiRequestDelivery=apiRequest;
apiRequest=function(path,options={}){const headers={...(options.headers||{}),'X-EHM-Operator':'demo-user','X-EHM-Role':deliveryRoleCodes[state.delivery?.demoRole]||'device-engineer'};return baseApiRequestDelivery(path,{...options,headers});};

async function loadDeliveryConsole(showMessage=false){
  const seq=++state.delivery.requestSeq;state.delivery.loading=true;state.delivery.error='';if(DELIVERY_PAGES.has(state.page))renderPage();
  try{
    const [status,readiness,capabilities,auditLogs,health]=await Promise.all([
      apiRequest('/system/status'),apiRequest('/system/delivery-readiness'),apiRequest('/system/capabilities'),
      apiRequest('/system/audit-logs?limit=100'),fetch(location.protocol==='file:'?'http://localhost:8080/health/ready':'/api/ehm/health/ready',{headers:{Accept:'application/json'}}).then(response=>response.json())]);
    if(seq!==state.delivery.requestSeq)return;Object.assign(state.delivery,{status,readiness,capabilities:capabilities||[],auditLogs:auditLogs||[],health,loading:false,error:''});
    if(DELIVERY_PAGES.has(state.page))renderPage();if(showMessage)toast('运行、依赖与审计信息已刷新。');
  }catch(error){if(seq!==state.delivery.requestSeq)return;state.delivery.loading=false;state.delivery.error=error.message;if(DELIVERY_PAGES.has(state.page))renderPage();if(showMessage)toast('交付状态读取失败：'+error.message);}
}

function deliveryTabs(){const items=[['service-ops','运行与交付'],['external-api','外部接口'],['iam','用户与权限'],['dictionaries','参数字典'],['approvals','审批中心'],['audit-logs','操作日志'],['audit-package','审计证据包']];return `<div class="delivery-tabs">${items.map(item=>`<button type="button" class="${state.page===item[0]?'active':''}" data-goto="${item[0]}">${item[1]}</button>`).join('')}</div>`;}
function deliveryStatusBadge(status){const cls=String(status||'').toLowerCase();const label={ACTIVE:'已运行',RESERVED:'已预留',BLOCKED:'上线阻断',DISABLED:'未启用'}[status]||status;return `<span class="delivery-badge ${cls}">${esc(label)}</span>`;}
function deliveryPending(){const d=state.delivery;if(d.loading)return '<div class="empty-state"><b>正在读取运行状态、依赖能力和审计日志…</b></div>';if(d.error)return `<div class="callout warning"><h3>交付状态暂不可用</h3><p>${esc(d.error)}</p>${button('重新加载','reloadDelivery')}</div>`;return '';}
function deliveryPageTitle(){return ({'service-ops':['运行与交付检查','集中核对服务、数据库、配置、接口契约和生产上线阻断项。'],'external-api':['外部接口与依赖','明确区分已运行、已预留、未启用和上线阻断，避免把预选技术栈写成已接入。'],iam:['用户、角色与数据权限','展示交付版权限基线；当前角色切换只影响Demo审计标识，不代表生产鉴权已启用。'],dictionaries:['参数与字典配置','统一告警等级、工单状态、设备状态和治理状态的业务含义。'],approvals:['审批中心','汇总需要设备主管确认的工单和高风险操作，审批后才进入执行。'],'audit-logs':['操作与接口审计','自动记录所有POST、PUT、PATCH和DELETE请求的操作者、角色、路径、结果和追踪号。'],'audit-package':['审计证据包','把当前配置、能力状态、数据规模、操作日志和上线阻断项汇总为可下载JSON证据包。']}[state.page]||['交付治理','交付版运行与治理控制台']);}
function renderDeliveryConsole(){const title=deliveryPageTitle();const pending=deliveryPending();return `<div class="page">${pageHead(title[0],title[1],`${button('刷新','reloadDelivery')}${state.page==='audit-package'?button('下载证据包','downloadAuditPackage','primary'):''}`)}${deliveryTabs()}<div class="notice-bar"><strong>${state.delivery.readiness?.demoDeliverable?'演示交付检查通过':'交付检查待处理'}</strong><span>“演示可交付”只表示本地全栈闭环可运行；生产上线仍以身份、TLS、现场接口和基础设施联调为准。</span>${tag(state.delivery.readiness?.productionReady?'生产可上线':'非生产版',state.delivery.readiness?.productionReady?'good':'warn')}</div>${pending||`${deliverySummary()}${renderDeliveryBody()}`}</div>`;}
function deliverySummary(){const d=state.delivery;return `<div class="grid cols-4 mb-12">${metric('服务状态',d.health?.status||'未知','',d.health?.component||d.status?.storageAdapter||'openGauss待检查',d.health?.status==='UP'?'good':'risk')}${metric('已运行依赖',String(d.capabilities.filter(item=>item.status==='ACTIVE').length),'项',`共${d.capabilities.length}项能力`,'good')}${metric('操作审计',String(d.auditLogs.length),'条','最近100条自动采集')}${metric('生产阻断',String(d.readiness?.productionBlockers?.length||0),'项','交付前必须由责任方关闭','risk')}</div>`;}
function renderDeliveryBody(){if(state.page==='external-api')return renderCapabilities();if(state.page==='iam')return renderIam();if(state.page==='dictionaries')return renderDictionaries();if(state.page==='approvals')return renderApprovals();if(state.page==='audit-logs')return renderAuditLogs();if(state.page==='audit-package')return renderAuditPackage();return renderServiceOps();}

function renderServiceOps(){const d=state.delivery;const completed=(d.readiness?.completedScope||[]).map(item=>`<div class="delivery-check"><i>✓</i><div><b>${esc(item)}</b><small>已纳入当前全栈Demo和接口验收</small></div>${tag('已完成','good')}</div>`).join('');const blockers=(d.readiness?.productionBlockers||[]).map(item=>`<div class="delivery-check blocked"><i>!</i><div><b>${esc(item)}</b><small>需甲方、统一平台或现场厂家提供条件后完成联调</small></div>${tag('阻断生产','severe')}</div>`).join('');return `<div class="grid cols-2"><section class="panel"><div class="panel-head"><div><h2>交付范围检查</h2><p>版本 ${esc(d.readiness?.edition||'—')}</p></div>${tag(d.readiness?.demoDeliverable?'演示可交付':'未通过',d.readiness?.demoDeliverable?'good':'severe')}</div><div class="panel-body delivery-checks">${completed}</div></section><section class="panel"><div class="panel-head"><div><h2>生产上线阻断项</h2><p>系统主动暴露未完成条件，不把预留接口计为上线能力。</p></div><span class="mini-badge">${d.readiness?.productionBlockers?.length||0}项</span></div><div class="panel-body delivery-checks">${blockers}</div></section></div><section class="panel mt-12"><div class="panel-head"><h2>服务端点与配置</h2><span class="mini-badge">架构 ${esc(d.status?.architecture||'—')}</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>检查项</th><th>当前值</th><th>端点 / 来源</th><th>结果</th></tr></thead><tbody><tr><td>存活检查</td><td>${esc(d.health?.status||'—')}</td><td><span class="service-endpoint">GET /health/live</span></td><td>${tag('可访问','good')}</td></tr><tr><td>就绪检查</td><td>${esc(d.health?.component||d.status?.storageAdapter||'数据库')} · ${esc(d.health?.adapter||'UP')}</td><td><span class="service-endpoint">GET /health/ready</span></td><td>${tag(d.health?.status==='UP'?'通过':'失败',d.health?.status==='UP'?'good':'severe')}</td></tr><tr><td>业务存储</td><td>${esc(d.status?.storageAdapter||'—')}</td><td><span class="service-endpoint">服务器配置档</span></td><td>${tag('已装配','good')}</td></tr><tr><td>时序存储</td><td>${esc(d.status?.telemetryAdapter||'未启用')}</td><td><span class="service-endpoint">GET /telemetry/points/{pointCode}/samples</span></td><td>${tag(d.status?.telemetryAdapter==='openGemini'?'已接入':'本地档','good')}</td></tr><tr><td>API契约</td><td>OpenAPI 1.8.0</td><td><span class="service-endpoint">GET /openapi/ehm-v1.yaml</span></td><td>${tag('随应用发布','good')}</td></tr><tr><td>统一配置</td><td>${esc(d.status?.config?.configVersion||'—')} · ${esc(d.status?.config?.environment||'—')}</td><td><span class="service-endpoint">服务器只读配置文件</span></td><td>${tag(d.status?.config?.loaded?'已加载':'未加载',d.status?.config?.loaded?'good':'warn')}</td></tr></tbody></table></div></section>`;}

function renderCapabilities(){const cards=state.delivery.capabilities.map(item=>`<article class="capability-card ${String(item.status).toLowerCase()}"><div><b>${esc(item.name)}</b><small>${esc(item.scope)}</small></div>${deliveryStatusBadge(item.status)}<p>启用/接入条件：${esc(item.condition)}</p></article>`).join('');return `<section class="panel"><div class="panel-head"><div><h2>技术能力接入状态</h2><p>已运行能力必须能通过接口或健康检查验证；预留能力只说明架构已留出替换点。</p></div><span class="mini-badge">${state.delivery.capabilities.length}项</span></div><div class="panel-body capability-cards">${cards}</div><div class="panel-foot"><span>现场PLC/OPC UA/Modbus接入不属于当前容器内能力，必须另行完成设备厂家联合验收。</span><span>更新来源：服务端配置</span></div></section>`;}

function renderIam(){const roles=[['系统管理员','读写','读写','读写','读写','读写','读写'],['设备管理员','读写','读写','读写','读写','只读','只读'],['设备工程师','只读','读写','读写','读写','只读','只读'],['维修技师','只读','只读','读写','只读','只读','无'],['数据管理员','只读','只读','只读','读写','读写','只读'],['审计员','只读','只读','只读','只读','只读','只读']];const mark=value=>`<span class="permission-mark ${value==='读写'?'write':value==='只读'?'read':'none'}">${value}</span>`;return `<section class="panel"><div class="panel-head"><div><h2>角色—模块权限基线</h2><p>权限矩阵用于统一设计和联调；生产环境必须由JWT/SSO身份和API网关强制执行。</p></div><label class="demo-role-select">当前Demo审计角色<select id="deliveryRoleSelect">${['系统管理员','设备管理员','设备工程师','维修技师','数据管理员','审计员'].map(role=>`<option ${role===state.delivery.demoRole?'selected':''}>${role}</option>`).join('')}</select></label></div><div class="notice-bar warning"><strong>当前未启用生产鉴权</strong><span>角色选择只会写入后续接口审计日志，不能作为安全边界；正式部署必须默认拒绝未认证请求。</span>${tag('上线阻断','severe')}</div><div class="table-wrap"><table class="data-table role-matrix"><thead><tr><th>角色</th><th>资产与测点</th><th>告警诊断</th><th>工单维保</th><th>可靠性治理</th><th>系统配置</th><th>审计导出</th></tr></thead><tbody>${roles.map(row=>`<tr><td><strong>${row[0]}</strong></td>${row.slice(1).map(mark).map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="panel-foot"><span>还需补充：场站/区域/设备数据范围、班组范围、敏感点表遮蔽和导出审批。</span><span>默认拒绝原则</span></div></section>`;}

function renderDictionaries(){const groups=[['告警等级',[['L4','紧急','可能立即导致重大安全或生产影响'],['L3','严重','需优先确认并尽快分派'],['L2','警告','需计划处置并持续观察'],['L1','提示','低风险偏差或早期变化'],['DATA','数据事件','断流、延迟、漂移或质量不合格']]],['工单状态',[['待审批','审批前','尚不能执行'],['待执行','已审批','等待班组和窗口'],['执行中','现场作业','需步骤和安全留痕'],['待复测','维修完成','等待独立验证'],['已关闭','验收通过','形成完整闭环']]],['设备状态',[['运行','在线作业','参与健康与OEE统计'],['待机','在线未作业','区分于离线'],['检修','计划维护','健康评分保留但标注维护状态'],['离线','通信中断','暂停实时评估'],['停机','业务停用','是否计入OEE需冻结口径']]],['治理状态',[['DRAFT','草稿','允许继续编辑，不参与正式推荐'],['PUBLISHED','已发布','规则已通过评审'],['DISABLED','已停用','保留历史，不再产生新事件'],['VERIFIED','已审核','知识案例可供正式检索'],['ACTIVE','有效','当前主数据有效']]]];return `<div class="dictionary-grid">${groups.map(group=>`<section class="dictionary-card"><h3>${group[0]}</h3><div class="dictionary-items">${group[1].map(item=>`<div class="dictionary-item"><code>${item[0]}</code><b>${item[1]}</b><span>${item[2]}</span></div>`).join('')}</div></section>`).join('')}</div>`;}

function renderApprovals(){const pending=WORK_ORDERS.filter(item=>item.status==='待审批');const rows=pending.map(item=>`<tr><td><strong>${esc(item.orderNo)}</strong><small>${esc(item.source)}</small></td><td><strong>${esc(item.deviceCode)} · ${esc(item.deviceName||'')}</strong></td><td>${esc(item.title)}<small>${esc(item.description)}</small></td><td>${tag(item.priority,item.priority?.includes('P1')?'severe':'warn')}</td><td>${esc(item.assignee)}</td><td>${esc(item.plannedWindow||'待确认')}</td><td><button class="table-action" data-action="advanceWork" data-id="${esc(item.orderNo)}" data-status="待执行">批准并进入待执行</button></td></tr>`).join('');return `<section class="panel"><div class="panel-head"><div><h2>待审批事项</h2><p>当前先接入工单审批；规则发布、敏感导出和模型发布审批已预留统一接口。</p></div><span class="mini-badge">${pending.length}项</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>单号 / 来源</th><th>设备</th><th>申请内容</th><th>优先级</th><th>执行班组</th><th>建议窗口</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="7"><div class="empty-state"><b>当前没有待审批工单</b></div></td></tr>'}</tbody></table></div><div class="panel-foot"><span>批准操作通过现有工单状态机执行，并自动写入接口操作审计。</span><span>生产环境需使用真实审批人身份</span></div></section>`;}

function renderAuditLogs(){const rows=state.delivery.auditLogs.map(item=>`<tr class="${item.outcome==='FAILED'?'row-alert':''}"><td>${relDate(item.occurredAt)}</td><td><strong>${esc(item.operator)}</strong><small>${esc(item.role)}</small></td><td>${tag(item.method,item.method==='DELETE'?'severe':item.method==='POST'?'info':'warn',true)}</td><td><span class="service-endpoint">${esc(item.path)}</span></td><td>${item.statusCode} · ${tag(item.outcome==='SUCCESS'?'成功':'失败',item.outcome==='SUCCESS'?'good':'severe')}</td><td>${item.durationMs} ms</td><td><span class="audit-trace">${esc(item.traceId)}</span><small>${esc(item.clientAddress)}</small></td></tr>`).join('');return `<section class="panel"><div class="panel-head"><div><h2>接口操作审计</h2><p>只记录业务写操作元数据，不记录密码、API密钥或完整请求正文。</p></div><span class="mini-badge">最近${state.delivery.auditLogs.length}条</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>时间</th><th>操作者 / 角色</th><th>方法</th><th>接口路径</th><th>结果</th><th>耗时</th><th>追踪号 / 来源</th></tr></thead><tbody>${rows||'<tr><td colspan="7">尚无写操作审计；执行一次新建、修订或状态变更后会自动产生。</td></tr>'}</tbody></table></div></section>`;}

function renderAuditPackage(){const d=state.delivery;return `<div class="grid cols-2"><section class="panel"><div class="panel-head"><div><h2>证据包内容</h2><p>点击“下载证据包”生成当前时点JSON快照。</p></div>${tag('不含密钥','good')}</div><div class="panel-body audit-package"><div><b>版本与运行环境</b><p>${esc(d.readiness?.edition||'—')}；服务${esc(d.health?.status||'—')}；配置${esc(d.status?.config?.configVersion||'—')}</p></div><div><b>业务数据规模</b><p>设备${EQUIPMENT.length}台；告警${ALARMS.length}条；工单${WORK_ORDERS.length}张；可靠性记录${state.reliability?.failureModes?.length||0}项</p></div><div><b>能力接入状态</b><p>${d.capabilities.length}项技术能力，${d.capabilities.filter(item=>item.status==='ACTIVE').length}项已运行</p></div><div><b>操作审计</b><p>最近${d.auditLogs.length}条写操作，包含追踪号与耗时</p></div><div><b>生产阻断项</b><p>${d.readiness?.productionBlockers?.length||0}项，由接收方逐项确认责任人与完成日期</p></div><div><b>安全处理</b><p>不导出配置文件原文、数据库口令、AI密钥和请求正文</p></div></div></section><section class="panel"><div class="panel-head"><h2>生产上线前必须关闭</h2><span class="mini-badge">${d.readiness?.productionBlockers?.length||0}项</span></div><div class="panel-body"><ol class="blocker-list">${(d.readiness?.productionBlockers||[]).map(item=>`<li>${esc(item)}</li>`).join('')}</ol></div></section></div>`;}

function downloadAuditPackage(){const d=state.delivery;const data={generatedAt:new Date().toISOString(),edition:d.readiness?.edition,classification:'EHM交付验收快照（不含密钥与请求正文）',runtime:{health:d.health,status:d.status},businessCounts:{devices:EQUIPMENT.length,alarms:ALARMS.length,workOrders:WORK_ORDERS.length,failureModes:state.reliability?.failureModes?.length||0,alarmRules:state.reliability?.rules?.length||0,knowledgeCases:state.reliability?.cases?.length||0},capabilities:d.capabilities,completedScope:d.readiness?.completedScope,productionBlockers:d.readiness?.productionBlockers,auditLogs:d.auditLogs};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`EHM-审计证据包-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);toast('审计证据包已生成；内容不含密钥和请求正文。');}

const baseRenderPageDelivery=renderPage;renderPage=function(){if(!DELIVERY_PAGES.has(state.page))return baseRenderPageDelivery();$('#pageView').innerHTML=renderDeliveryConsole();syncNav();$('#content').scrollTop=0;bindPageEvents();};
const baseSetPageDelivery=setPage;setPage=function(page){baseSetPageDelivery(page);if(DELIVERY_PAGES.has(page))loadDeliveryConsole();};
const baseHandleActionDelivery=handleAction;handleAction=function(event){const action=event.currentTarget.dataset.action;if(action==='reloadDelivery')return loadDeliveryConsole(true);if(action==='downloadAuditPackage')return downloadAuditPackage();return baseHandleActionDelivery(event);};
const baseBindPageEventsDelivery=bindPageEvents;bindPageEvents=function(){baseBindPageEventsDelivery();const selector=$('#deliveryRoleSelect');if(selector)selector.onchange=()=>{state.delivery.demoRole=selector.value;toast(`后续Demo写操作将以“${selector.value}”写入审计日志。`);};};
