const EHM_GOV = {
  tasks:[], handovers:[], templates:[], calibrations:[], changes:[],
  loaded:{}, loading:{}
};

function govTag(status){
  const labels={OPEN:'待处理',IN_PROGRESS:'处理中',COMPLETED:'已完成',CANCELLED:'已取消',DRAFT:'草稿',SUBMITTED:'待接班',RECEIVED:'已接班',PUBLISHED:'已发布',PASS:'合格',FAIL:'不合格',LIMITED:'受限',APPROVED:'已审批',EFFECTIVE:'已生效'};
  const cls={OPEN:'warn',IN_PROGRESS:'info',COMPLETED:'good',DRAFT:'offline',SUBMITTED:'warn',RECEIVED:'good',PUBLISHED:'good',PASS:'good',FAIL:'critical',LIMITED:'limited',APPROVED:'info',EFFECTIVE:'good'}[status]||'info';
  return tag(labels[status]||status||'—',cls,true);
}
function govDate(value,withTime=false){
  if(!value)return '—'; const d=new Date(value); if(Number.isNaN(d.getTime()))return esc(value);
  return d.toLocaleString('zh-CN',{hour12:false,year:'numeric',month:'2-digit',day:'2-digit',...(withTime?{hour:'2-digit',minute:'2-digit'}:{})}).replaceAll('/','-');
}
function govLines(value){return (value||[]).map(item=>`<li>${esc(item)}</li>`).join('')||'<li class="muted">无</li>';}
function govEnsure(key,path){
  if(EHM_GOV.loaded[key]||EHM_GOV.loading[key]||!state.backendConnected)return;
  EHM_GOV.loading[key]=true;
  queueMicrotask(async()=>{try{EHM_GOV[key]=await apiRequest(path);EHM_GOV.loaded[key]=true;updateTaskBadge();renderPage();}
    catch(error){toast('加载失败：'+error.message);}finally{EHM_GOV.loading[key]=false;}});
}
function govReload(key,path){EHM_GOV.loaded[key]=false;EHM_GOV.loading[key]=false;govEnsure(key,path);}
function updateTaskBadge(){const el=document.querySelector('[data-goto="my-tasks"] span');if(el)el.textContent=EHM_GOV.tasks.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).length;}

function renderMyTasks(){
  govEnsure('tasks','/my-tasks'); const rows=EHM_GOV.tasks.map(item=>`<tr><td><strong>${esc(item.taskNo)}</strong><small>${esc(item.taskType)} · ${esc(item.sourceType||'MANUAL')}</small></td><td>${esc(item.title)}<small>${esc(item.description||'无补充说明')}</small></td><td>${esc(item.assetCode||'—')}</td><td>${esc(item.assignee)}<small>${esc(item.team)}</small></td><td>${tag(item.priority,item.priority?.includes('P1')?'critical':item.priority?.includes('P2')?'warn':'info',true)}</td><td>${govDate(item.dueAt,true)}</td><td>${govTag(item.status)}</td><td>${!['COMPLETED','CANCELLED'].includes(item.status)?`<button class="table-action" data-action="editTask" data-id="${esc(item.taskNo)}">编辑</button><button class="table-action" data-action="completeTask" data-id="${esc(item.taskNo)}">完成</button>`:'<span class="muted">已闭环</span>'}</td></tr>`).join('');
  const open=EHM_GOV.tasks.filter(t=>t.status==='OPEN').length,inProgress=EHM_GOV.tasks.filter(t=>t.status==='IN_PROGRESS').length,done=EHM_GOV.tasks.filter(t=>t.status==='COMPLETED').length,overdue=EHM_GOV.tasks.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)&&t.dueAt&&new Date(t.dueAt)<new Date()).length;
  return `<div class="page">${pageHead('我的待办','统一收口告警、校准、点检、审批和人工任务；状态与完成时间持久化到openGauss。',`${button('刷新','refreshTasks')}${button('新建待办','newTask','primary')}`)}
  <div class="grid cols-4 mb-12">${metric('待处理',open,'项','尚未开始','warn')}${metric('处理中',inProgress,'项','责任人正在办理')}${metric('已逾期',overdue,'项','未闭环且超过截止时间','risk')}${metric('已完成',done,'项','历史留痕','good')}</div>
  <section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>编号 / 来源</th><th>待办内容</th><th>设备</th><th>责任人 / 班组</th><th>优先级</th><th>截止时间</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="8" class="empty-state">暂无待办，可点击“新建待办”。</td></tr>'}</tbody></table></div>${pager(String(EHM_GOV.tasks.length))}</section></div>`;
}

function renderShiftHandovers(){
  govEnsure('handovers','/shift-handovers'); const cards=EHM_GOV.handovers.map(item=>`<section class="panel mb-12"><div class="panel-head"><div><h2>${esc(item.handoverNo)} · ${govDate(item.shiftDate)}</h2><p>${esc(item.outgoingShift)} → ${esc(item.incomingShift)} · ${esc(item.outgoingLeader)} / ${esc(item.incomingLeader)}</p></div>${govTag(item.status)}</div><div class="panel-body"><div class="callout"><h3>交接摘要</h3><p>${esc(item.summary)}</p></div><div class="grid cols-3 mt-12"><div><h3>风险事项</h3><ul class="condition-list">${govLines(item.riskItems)}</ul></div><div><h3>未完事项</h3><ul class="condition-list">${govLines(item.unfinishedItems)}</ul></div><div><h3>设备异常</h3><ul class="condition-list">${govLines(item.equipmentExceptions)}</ul></div></div>${item.notes?`<p class="muted mt-12">补充：${esc(item.notes)}</p>`:''}</div><div class="panel-foot"><span>提交：${govDate(item.submittedAt,true)} · 接班：${govDate(item.receivedAt,true)}</span><div>${item.status==='DRAFT'?`<button class="button primary" data-action="submitHandover" data-id="${esc(item.handoverNo)}">提交交接</button>`:''}${item.status==='SUBMITTED'?`<button class="button primary" data-action="receiveHandover" data-id="${esc(item.handoverNo)}">接班确认</button>`:''}</div></div></section>`).join('');
  return `<div class="page">${pageHead('班组交接','从活动告警和未闭环工单生成草稿，交班提交、接班签认均保留时间与人员记录。',`${button('刷新','refreshHandovers')}${button('手工新建','newHandover')}${button('自动汇总生成草稿','generateHandover','primary')}`)}<div class="notice-bar"><strong>双向签认</strong><span>自动汇总仅生成草稿，交班人必须核对内容；接班确认后记录不可覆盖。</span>${tag('openGauss持久化','good')}</div>${cards||'<section class="panel"><div class="empty-state">暂无交接记录，可自动汇总生成草稿。</div></section>'}</div>`;
}

function renderDeviceTemplates(){
  govEnsure('templates','/device-templates'); const rows=EHM_GOV.templates.map(item=>`<tr><td><strong>${esc(item.templateCode)}</strong><small>修订 ${item.revision}</small></td><td>${esc(item.name)}<small>${esc(item.deviceType)}</small></td><td>${item.components?.length||0} 个部件</td><td>${item.measurementPoints?.length||0} 个测点</td><td>${esc(item.inspectionPolicy)}</td><td>${tag(item.criticality,item.criticality==='关键设备'?'critical':'info',true)}</td><td>${govTag(item.status)}</td><td>${item.status==='DRAFT'?`<button class="table-action" data-action="editTemplate" data-id="${esc(item.templateCode)}">编辑</button><button class="table-action" data-action="publishTemplate" data-id="${esc(item.templateCode)}">发布</button>`:'<span class="muted">受控版本</span>'}</td></tr>`).join('');
  return `<div class="page">${pageHead('设备模板','把同类设备的标准BOM、测点、采样范围和点检策略固化为可审批版本。',`${button('刷新','refreshTemplates')}${button('新建设备模板','newTemplate','primary')}`)}<div class="grid cols-3 mb-12">${panel('标准化建档','模板统一同类型设备的部件层级、测点编码、量程和关键性，减少重复录入。')}${panel('发布控制','草稿可编辑；发布后锁定，后续调整应新建修订，避免批量污染设备档案。')}${panel('后续实例化','模板与设备实例解耦，现场型号确认后可批量生成BOM和测点。')}</div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>模板编码</th><th>名称 / 类型</th><th>部件</th><th>测点</th><th>点检策略</th><th>关键等级</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="8" class="empty-state">暂无模板。</td></tr>'}</tbody></table></div></section></div>`;
}

function renderCalibrationRecords(){
  govEnsure('calibrations','/calibration-records'); const now=Date.now(),within30=EHM_GOV.calibrations.filter(x=>x.validUntil&&new Date(x.validUntil).getTime()<now+30*86400000).length,failed=EHM_GOV.calibrations.filter(x=>x.result!=='PASS').length;
  const rows=EHM_GOV.calibrations.map(item=>{const remain=item.validUntil?Math.ceil((new Date(item.validUntil)-Date.now())/86400000):null;return `<tr><td><strong>${esc(item.calibrationNo)}</strong><small>${esc(item.calibrationType)}</small></td><td>${esc(item.assetCode)}<small>${esc(item.pointCode||item.componentCode||'—')}</small></td><td>${esc(item.sensorCode)}</td><td>${item.beforeValue??'—'} → ${item.afterValue??'—'} ${esc(item.unit||'')}</td><td>${esc(item.tolerance??'—')}</td><td>${govTag(item.result)}</td><td>${esc(item.certificateNo||'—')}<small>${esc(item.organization)}</small></td><td>${govDate(item.calibratedAt)}<small>有效至 ${govDate(item.validUntil)}${remain!==null?` · ${remain<0?'已过期':remain+'天'}`:''}</small></td></tr>`}).join('');
  return `<div class="page">${pageHead('传感器与计量校准','校准结果、证书、有效期与测点绑定；临期或不合格记录直接暴露数据可信度风险。',`${button('刷新','refreshCalibrations')}${button('登记校准记录','newCalibration','primary')}`)}<div class="grid cols-4 mb-12">${metric('校准记录',EHM_GOV.calibrations.length,'条','全部历史')}${metric('30天内到期',within30,'只','应安排复校','warn')}${metric('受限 / 不合格',failed,'只','影响测点可信度','risk')}${metric('证书覆盖',EHM_GOV.calibrations.filter(x=>x.certificateNo).length,'条','可追溯凭证','good')}</div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>校准编号</th><th>设备 / 测点</th><th>传感器</th><th>校准前 → 后</th><th>允许误差</th><th>结论</th><th>证书 / 机构</th><th>校准 / 有效期</th></tr></thead><tbody>${rows||'<tr><td colspan="8" class="empty-state">暂无校准记录。</td></tr>'}</tbody></table></div></section></div>`;
}

function renderConfigurationChanges(){
  govEnsure('changes','/configuration-changes'); const rows=EHM_GOV.changes.map(item=>`<tr><td><strong>${esc(item.changeNo)}</strong><small>${govDate(item.requestedAt,true)}</small></td><td>${esc(item.assetCode)}<small>${esc(item.objectType)} / ${esc(item.objectCode)}</small></td><td>${esc(item.changeType)}</td><td><details><summary>查看前后快照</summary><pre class="config-snapshot">变更前：${esc(JSON.stringify(item.beforeSnapshot,null,2))}\n变更后：${esc(JSON.stringify(item.afterSnapshot,null,2))}</pre></details></td><td>${esc(item.reason)}<small>${esc(item.impactAssessment)}</small></td><td>${esc(item.applicant)}<small>审批：${esc(item.approver||'—')} · 执行：${esc(item.executor||'—')}</small></td><td>${govTag(item.status)}</td><td>${item.status==='DRAFT'?`<button class="table-action" data-action="approveChange" data-id="${esc(item.changeNo)}">审批</button>`:''}${item.status==='APPROVED'?`<button class="table-action" data-action="applyChange" data-id="${esc(item.changeNo)}">确认生效</button>`:''}${item.status==='EFFECTIVE'?'<span class="muted">不可覆盖</span>':''}</td></tr>`).join('');
  return `<div class="page">${pageHead('配置变更与数字履历','完整保存变更前后快照、影响评估、审批与执行人，形成不可覆盖的设备配置时间线。',`${button('刷新','refreshChanges')}${button('发起配置变更','newChange','primary')}`)}<div class="notice-bar"><strong>先审批、后生效</strong><span>配置变更只记录治理流程，不直接向PLC下发参数；现场执行需遵守调度、停送电和安全审批。</span>${tag('历史留痕','good')}</div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>变更编号</th><th>设备 / 对象</th><th>类型</th><th>前后快照</th><th>原因 / 影响</th><th>人员</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="8" class="empty-state">暂无配置变更。</td></tr>'}</tbody></table></div></section></div>`;
}

function handleGovernanceAction(action,buttonEl){
  const actions={refreshTasks:()=>govReload('tasks','/my-tasks'),newTask:()=>openTaskModal(),editTask:()=>openTaskModal(buttonEl.dataset.id),completeTask:()=>completeTask(buttonEl.dataset.id),refreshHandovers:()=>govReload('handovers','/shift-handovers'),newHandover:()=>openHandoverModal(),generateHandover:generateHandover,submitHandover:()=>handoverTransition(buttonEl.dataset.id,'submit'),receiveHandover:()=>handoverTransition(buttonEl.dataset.id,'receive'),refreshTemplates:()=>govReload('templates','/device-templates'),newTemplate:()=>openTemplateModal(),editTemplate:()=>openTemplateModal(buttonEl.dataset.id),publishTemplate:()=>publishTemplate(buttonEl.dataset.id),refreshCalibrations:()=>govReload('calibrations','/calibration-records'),newCalibration:openCalibrationModal,refreshChanges:()=>govReload('changes','/configuration-changes'),newChange:openChangeModal,approveChange:()=>changeTransition(buttonEl.dataset.id,'approve'),applyChange:()=>changeTransition(buttonEl.dataset.id,'apply')};
  if(!actions[action])return false; actions[action](); return true;
}

function requireBackend(){if(!state.backendConnected){toast('后端未连接，当前页面只读。');return false;}return true;}
function localInputDate(value){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function deviceOptions(selected=''){return EQUIPMENT.map(x=>`<option value="${esc(x.code)}" ${x.code===selected?'selected':''}>${esc(x.code)} ${esc(x.name)}</option>`).join('');}
function listFromText(id){return ($('#'+id)?.value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);}

function openTaskModal(no){
  if(!requireBackend())return; const item=EHM_GOV.tasks.find(x=>x.taskNo===no)||{};
  openModal('我的待办',no?'编辑待办':'新建待办',`<div class="form-grid"><div class="field"><label>任务类型</label><select id="govTaskType"><option ${item.taskType==='告警处置'?'selected':''}>告警处置</option><option ${item.taskType==='点检任务'?'selected':''}>点检任务</option><option ${item.taskType==='校准提醒'?'selected':''}>校准提醒</option><option ${item.taskType==='审批任务'?'selected':''}>审批任务</option><option>人工任务</option></select></div><div class="field"><label>设备</label><select id="govTaskAsset"><option value="">不限定设备</option>${deviceOptions(item.assetCode)}</select></div><div class="field full"><label>标题 <em>*</em></label><input id="govTaskTitle" value="${esc(item.title||'')}"/></div><div class="field full"><label>说明</label><textarea id="govTaskDescription">${esc(item.description||'')}</textarea></div><div class="field"><label>责任人</label><input id="govTaskAssignee" value="${esc(item.assignee||'闫鑫钰')}"/></div><div class="field"><label>责任班组</label><input id="govTaskTeam" value="${esc(item.team||'设备运维组')}"/></div><div class="field"><label>优先级</label><select id="govTaskPriority"><option>P1 高</option><option ${!item.priority||item.priority==='P2 中'?'selected':''}>P2 中</option><option>P3 低</option></select></div><div class="field"><label>状态</label><select id="govTaskStatus"><option value="OPEN">待处理</option><option value="IN_PROGRESS" ${item.status==='IN_PROGRESS'?'selected':''}>处理中</option></select></div><div class="field full"><label>截止时间</label><input id="govTaskDue" type="datetime-local" value="${localInputDate(item.dueAt)}"/></div></div>`,'保存',async()=>{const title=$('#govTaskTitle').value.trim();if(!title){toast('待办标题不能为空。');return false;}const payload={taskType:$('#govTaskType').value,sourceType:item.sourceType||'MANUAL',sourceId:item.sourceId||null,title,description:$('#govTaskDescription').value,assetCode:$('#govTaskAsset').value||null,assignee:$('#govTaskAssignee').value,team:$('#govTaskTeam').value,priority:$('#govTaskPriority').value,status:$('#govTaskStatus').value,dueAt:$('#govTaskDue').value?new Date($('#govTaskDue').value).toISOString():null};await apiRequest(no?'/my-tasks/'+encodeURIComponent(no):'/my-tasks',{method:no?'PUT':'POST',body:JSON.stringify(payload)});govReload('tasks','/my-tasks');toast(no?'待办已更新。':'待办已创建并持久化。');return true;});
}
async function completeTask(no){if(!requireBackend())return;try{await apiRequest('/my-tasks/'+encodeURIComponent(no)+'/complete',{method:'POST',body:JSON.stringify({operator:'闫鑫钰'})});govReload('tasks','/my-tasks');toast(no+' 已完成并保留闭环时间。');}catch(e){toast('完成失败：'+e.message);}}

function openHandoverModal(){
  if(!requireBackend())return; const today=new Date().toISOString().slice(0,10);
  openModal('班组交接','手工创建交接草稿',`<div class="form-grid"><div class="field"><label>班次日期</label><input id="govHoDate" type="date" value="${today}"/></div><div class="field"><label>交班 → 接班</label><input id="govHoShift" value="白班 → 夜班"/></div><div class="field"><label>交班负责人</label><input id="govHoOutLeader" value="白班班长"/></div><div class="field"><label>接班负责人</label><input id="govHoInLeader" value="夜班班长"/></div><div class="field full"><label>交接摘要 <em>*</em></label><textarea id="govHoSummary"></textarea></div><div class="field full"><label>风险事项（每行一项）</label><textarea id="govHoRisk"></textarea></div><div class="field full"><label>未完事项（每行一项）</label><textarea id="govHoUnfinished"></textarea></div><div class="field full"><label>设备异常（每行一项）</label><textarea id="govHoExceptions"></textarea></div></div>`,'保存草稿',async()=>{const shifts=$('#govHoShift').value.split('→');const payload={shiftDate:$('#govHoDate').value,outgoingShift:(shifts[0]||'白班').trim(),incomingShift:(shifts[1]||'夜班').trim(),outgoingLeader:$('#govHoOutLeader').value,incomingLeader:$('#govHoInLeader').value,summary:$('#govHoSummary').value,riskItems:listFromText('govHoRisk'),unfinishedItems:listFromText('govHoUnfinished'),equipmentExceptions:listFromText('govHoExceptions')};await apiRequest('/shift-handovers',{method:'POST',body:JSON.stringify(payload)});govReload('handovers','/shift-handovers');toast('交接草稿已保存。');return true;});
}
async function generateHandover(){if(!requireBackend())return;try{await apiRequest('/shift-handovers/generate',{method:'POST',body:JSON.stringify({outgoingShift:'白班',incomingShift:'夜班',outgoingLeader:'白班班长',incomingLeader:'夜班班长'})});govReload('handovers','/shift-handovers');toast('已从活动告警和工单生成交接草稿。');}catch(e){toast('生成失败：'+e.message);}}
async function handoverTransition(no,action){if(!requireBackend())return;try{await apiRequest(`/shift-handovers/${encodeURIComponent(no)}/${action}`,{method:'POST',body:JSON.stringify({operator:action==='submit'?'白班班长':'夜班班长'})});govReload('handovers','/shift-handovers');toast(action==='submit'?'交班已提交，等待接班确认。':'接班已确认，交接记录完成。');}catch(e){toast('操作失败：'+e.message);}}

function openTemplateModal(code){
  if(!requireBackend())return;const item=EHM_GOV.templates.find(x=>x.templateCode===code)||{};const c=item.components?.[0]||{},p=item.measurementPoints?.[0]||{};
  openModal('设备模板',code?'编辑模板草稿':'新建模板草稿',`<div class="form-grid"><div class="field"><label>模板编码</label><input id="govTplCode" value="${esc(item.templateCode||'')}" ${code?'disabled':''} placeholder="TPL-CRANE-V1"/></div><div class="field"><label>设备类型 <em>*</em></label><input id="govTplType" value="${esc(item.deviceType||'门吊')}"/></div><div class="field full"><label>模板名称 <em>*</em></label><input id="govTplName" value="${esc(item.name||'')}"/></div><div class="field"><label>部件编码</label><input id="govTplCompCode" value="${esc(c.componentCode||'HOIST')}"/></div><div class="field"><label>部件名称</label><input id="govTplCompName" value="${esc(c.name||'起升机构')}"/></div><div class="field"><label>测点编码</label><input id="govTplPointCode" value="${esc(p.pointCode||'VIB-DE')}"/></div><div class="field"><label>测点名称</label><input id="govTplPointName" value="${esc(p.name||'驱动端振动')}"/></div><div class="field"><label>指标 / 单位</label><input id="govTplMetric" value="${esc((p.metric||'vibration')+' / '+(p.unit||'mm/s'))}"/></div><div class="field"><label>采样频率Hz</label><input id="govTplRate" type="number" value="${p.sampleRateHz||25600}"/></div><div class="field"><label>点检策略</label><input id="govTplPolicy" value="${esc(item.inspectionPolicy||'月度点检+状态触发')}"/></div><div class="field"><label>关键等级</label><select id="govTplCritical"><option>关键设备</option><option ${item.criticality==='一般'?'selected':''}>一般</option></select></div></div>`,'保存草稿',async()=>{const metric=$('#govTplMetric').value.split('/');const payload={templateCode:code||$('#govTplCode').value,name:$('#govTplName').value,deviceType:$('#govTplType').value,inspectionPolicy:$('#govTplPolicy').value,criticality:$('#govTplCritical').value,createdBy:'设备管理员',components:[{componentCode:$('#govTplCompCode').value,name:$('#govTplCompName').value,category:'核心部件',quantity:1,critical:true}],measurementPoints:[{pointCode:$('#govTplPointCode').value,name:$('#govTplPointName').value,metric:(metric[0]||'vibration').trim(),unit:(metric[1]||'mm/s').trim(),sampleRateHz:Number($('#govTplRate').value),minValue:0,maxValue:100,critical:true}]};await apiRequest(code?'/device-templates/'+encodeURIComponent(code):'/device-templates',{method:code?'PUT':'POST',body:JSON.stringify(payload)});govReload('templates','/device-templates');toast('设备模板草稿已保存。');return true;});
}
async function publishTemplate(code){if(!requireBackend())return;try{await apiRequest('/device-templates/'+encodeURIComponent(code)+'/publish',{method:'POST',body:JSON.stringify({operator:'设备主管'})});govReload('templates','/device-templates');toast(code+' 已发布并锁定。');}catch(e){toast('发布失败：'+e.message);}}

function openCalibrationModal(){
  if(!requireBackend())return;const today=new Date(),next=new Date(Date.now()+365*86400000);
  openModal('计量校准','登记校准记录',`<div class="form-grid"><div class="field"><label>设备</label><select id="govCalAsset">${deviceOptions()}</select></div><div class="field"><label>传感器编码 <em>*</em></label><input id="govCalSensor" value="SEN-"/></div><div class="field"><label>部件编码</label><input id="govCalComp" value="HOIST"/></div><div class="field"><label>测点编码</label><input id="govCalPoint" value="VIB-DE"/></div><div class="field"><label>校准前 / 后</label><input id="govCalValues" value="7.1 / 6.9"/></div><div class="field"><label>允许误差 / 单位</label><input id="govCalTolerance" value="0.3 / mm/s"/></div><div class="field"><label>校准日期</label><input id="govCalAt" type="date" value="${today.toISOString().slice(0,10)}"/></div><div class="field"><label>有效期至</label><input id="govCalUntil" type="date" value="${next.toISOString().slice(0,10)}"/></div><div class="field"><label>结论</label><select id="govCalResult"><option value="PASS">合格</option><option value="LIMITED">受限</option><option value="FAIL">不合格</option></select></div><div class="field"><label>证书编号</label><input id="govCalCert"/></div><div class="field full"><label>备注</label><textarea id="govCalRemark"></textarea></div></div>`,'登记',async()=>{const values=$('#govCalValues').value.split('/'),tol=$('#govCalTolerance').value.split('/');const payload={assetCode:$('#govCalAsset').value,componentCode:$('#govCalComp').value,pointCode:$('#govCalPoint').value,sensorCode:$('#govCalSensor').value,calibrationType:'周期校准',beforeValue:Number(values[0]),afterValue:Number(values[1]),tolerance:Number(tol[0]),unit:(tol[1]||'').trim(),result:$('#govCalResult').value,certificateNo:$('#govCalCert').value,organization:'内部计量室',operator:'计量员',calibratedAt:new Date($('#govCalAt').value).toISOString(),validUntil:new Date($('#govCalUntil').value+'T23:59:59').toISOString(),remark:$('#govCalRemark').value};await apiRequest('/calibration-records',{method:'POST',body:JSON.stringify(payload)});govReload('calibrations','/calibration-records');toast('校准记录已登记，历史不会被覆盖。');return true;});
}

function openChangeModal(){
  if(!requireBackend())return;
  openModal('配置变更','发起受控配置变更',`<div class="risk-confirm"><strong>安全边界：</strong>这里只记录变更审批与数字履历，不会直接向PLC下发参数。</div><div class="form-grid"><div class="field"><label>设备</label><select id="govCfgAsset">${deviceOptions()}</select></div><div class="field"><label>对象类型</label><select id="govCfgType"><option>MEASUREMENT_POINT</option><option>GATEWAY</option><option>DEVICE</option><option>ALARM_RULE</option></select></div><div class="field"><label>对象编码 <em>*</em></label><input id="govCfgObject" value="VIB-DE"/></div><div class="field"><label>变更类型</label><input id="govCfgChangeType" value="采样策略变更"/></div><div class="field full"><label>变更前JSON</label><textarea id="govCfgBefore">{"sampleRateHz":12800,"windowSeconds":8}</textarea></div><div class="field full"><label>变更后JSON <em>*</em></label><textarea id="govCfgAfter">{"sampleRateHz":25600,"windowSeconds":16}</textarea></div><div class="field full"><label>变更原因 <em>*</em></label><textarea id="govCfgReason">提高故障特征分辨率</textarea></div><div class="field full"><label>影响评估</label><textarea id="govCfgImpact">评估网络、边缘缓存、时序存储和告警阈值影响；现场执行需审批。</textarea></div><div class="field"><label>回滚基线</label><input id="govCfgRollback" value="自动保留变更前快照"/></div><div class="field"><label>申请人</label><input id="govCfgApplicant" value="设备工程师"/></div></div>`,'保存草稿',async()=>{let before,after;try{before=JSON.parse($('#govCfgBefore').value||'{}');after=JSON.parse($('#govCfgAfter').value||'{}');}catch{toast('前后配置必须是合法JSON。');return false;}const payload={assetCode:$('#govCfgAsset').value,objectType:$('#govCfgType').value,objectCode:$('#govCfgObject').value,changeType:$('#govCfgChangeType').value,beforeSnapshot:before,afterSnapshot:after,reason:$('#govCfgReason').value,impactAssessment:$('#govCfgImpact').value,applicant:$('#govCfgApplicant').value,rollbackReference:$('#govCfgRollback').value};await apiRequest('/configuration-changes',{method:'POST',body:JSON.stringify(payload)});govReload('changes','/configuration-changes');toast('配置变更草稿已保存。');return true;});
}
async function changeTransition(no,action){if(!requireBackend())return;try{await apiRequest(`/configuration-changes/${encodeURIComponent(no)}/${action}`,{method:'POST',body:JSON.stringify({operator:action==='approve'?'设备主管':'设备管理员'})});govReload('changes','/configuration-changes');toast(action==='approve'?'变更已审批，等待现场执行。':'变更已确认生效，前后快照已固化。');}catch(e){toast('操作失败：'+e.message);}}
