// 维护策略/计划/点检/缺陷扩展。后端负责状态机和必检项校验，前端只提交操作意图。
const MAINTENANCE_PROGRAM_PAGES=new Set(['strategy','maintenance-plan','inspection']);
state.maintenanceProgram={assetCode:'GT-01',plans:[],tasks:[],defects:[],loading:false,error:'',requestSeq:0};

function selectedMaintenanceAsset(){const value=EQUIPMENT.find(item=>item.code===state.maintenanceProgram.assetCode)||EQUIPMENT[0];if(value)state.maintenanceProgram.assetCode=value.code;return value;}

async function loadMaintenanceProgram(showMessage=false){
  const asset=selectedMaintenanceAsset();if(!asset)return;
  const seq=++state.maintenanceProgram.requestSeq;state.maintenanceProgram.loading=true;state.maintenanceProgram.error='';
  if(MAINTENANCE_PROGRAM_PAGES.has(state.page))renderPage();
  try{
    const code=encodeURIComponent(asset.code);
    const [plans,tasks,defects]=await Promise.all([
      apiRequest(`/maintenance-plans?assetCode=${code}`),
      apiRequest(`/inspection-tasks?assetCode=${code}`),
      apiRequest(`/maintenance-defects?assetCode=${code}`)
    ]);
    if(seq!==state.maintenanceProgram.requestSeq)return;
    Object.assign(state.maintenanceProgram,{plans:plans||[],tasks:tasks||[],defects:defects||[],loading:false,error:''});
    if(MAINTENANCE_PROGRAM_PAGES.has(state.page))renderPage();
    if(showMessage)toast(`${asset.code} 的维护计划、点检和缺陷已刷新。`);
  }catch(error){if(seq!==state.maintenanceProgram.requestSeq)return;state.maintenanceProgram.loading=false;state.maintenanceProgram.error=error.message;if(MAINTENANCE_PROGRAM_PAGES.has(state.page))renderPage();if(showMessage)toast('维保数据加载失败：'+error.message);}
}

function maintenanceAssetSelector(){const asset=selectedMaintenanceAsset();return `<select class="control" id="maintenanceAssetSelect">${EQUIPMENT.map(item=>`<option value="${esc(item.code)}" ${item.code===asset?.code?'selected':''}>${esc(item.code)} · ${esc(item.name)}</option>`).join('')}</select>`;}
function maintenanceProgramTabs(){return `<div class="maintenance-tabs"><button data-goto="strategy" class="${state.page==='strategy'?'active':''}">1 维护策略</button><button data-goto="maintenance-plan" class="${state.page==='maintenance-plan'?'active':''}">2 计划与任务</button><button data-goto="inspection" class="${state.page==='inspection'?'active':''}">3 点检与缺陷</button></div>`;}
function mpDate(value){return value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—';}
function strategyLabel(value){return value==='CONDITION_BASED'?'状态触发':value==='PREDICTIVE'?'预测触发':'周期维护';}
function inspectionTone(value){return value==='已完成'?'good':value==='发现缺陷'?'severe':value==='执行中'?'warn':value==='已取消'?'offline':'info';}
function defectTone(value){return value==='WORK_ORDER_CREATED'?'good':'severe';}

function maintenanceProgramHead(){
  const title=state.page==='strategy'?'维护策略':state.page==='maintenance-plan'?'维护计划与任务':'点检执行与缺陷';
  const description=state.page==='strategy'?'定义维护周期、状态触发条件和标准检查项。':state.page==='maintenance-plan'?'从已启用计划生成可执行点检任务，避免同计划重复派单。':'逐项填写测量值和结论；不符合项自动形成缺陷，再由人工转工单。';
  return pageHead(title,description,`${maintenanceAssetSelector()}${button('刷新','reloadMaintenanceProgram')}${state.page==='strategy'?button('新建维护计划','newMaintenancePlan','primary'):''}`);
}

function maintenanceProgramPending(){const s=state.maintenanceProgram;if(s.loading)return panel('正在加载','<div class="empty-state"><b>读取计划、点检任务和缺陷…</b></div>');if(s.error)return panel('暂不可用',`<div class="callout warning"><h3>加载失败</h3><p>${esc(s.error)}</p>${button('重试','reloadMaintenanceProgram')}</div>`);return '';}

function strategyTable(){
  const rows=state.maintenanceProgram.plans.map(plan=>`<tr><td><strong>${esc(plan.name)}</strong><small>${esc(plan.planId)}</small></td><td>${esc(plan.componentCode)}</td><td>${tag(strategyLabel(plan.strategyType),plan.strategyType==='PREDICTIVE'?'purple':'info')}</td><td class="num">${plan.cycleDays}天</td><td>${esc(plan.triggerCondition)}</td><td class="num">${plan.checklistTemplate.length}项</td><td>${esc(plan.ownerTeam)}</td><td>${tag(plan.enabled?'启用':'停用',plan.enabled?'good':'offline')}</td></tr>`).join('');
  return `<section class="panel"><div class="panel-head"><div><h2>策略与标准检查项</h2><p>计划中固化检查方法和判定标准，生成任务后保留当时模板快照。</p></div><span class="mini-badge">${state.maintenanceProgram.plans.length}项</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>计划 / 编号</th><th>对象</th><th>策略</th><th>周期</th><th>触发条件</th><th>检查项</th><th>责任组</th><th>状态</th></tr></thead><tbody>${rows||'<tr><td colspan="8">尚无维护计划，请先新建。</td></tr>'}</tbody></table></div></section>`;
}

function planTable(){
  const rows=state.maintenanceProgram.plans.map(plan=>{const open=state.maintenanceProgram.tasks.find(task=>task.planId===plan.planId&&['PLANNED','IN_PROGRESS'].includes(task.status));return `<tr><td><strong>${esc(plan.name)}</strong><small>${esc(plan.planId)}</small></td><td>${tag(strategyLabel(plan.strategyType),'info')}</td><td>${mpDate(plan.nextDueAt)}</td><td>${mpDate(plan.lastGeneratedAt)}</td><td>${open?tag(open.status==='IN_PROGRESS'?'执行中':'待执行',open.status==='IN_PROGRESS'?'warn':'info'):'—'}</td><td>${open?`<span class="muted">${esc(open.taskNo)}</span>`:`<button class="table-action" data-action="generateInspectionTask" data-id="${esc(plan.planId)}">生成点检任务</button>`}</td></tr>`;}).join('');
  return `<div class="grid cols-4 mb-12">${metric('启用计划',String(state.maintenanceProgram.plans.filter(x=>x.enabled).length),'项','按设备和部件配置')}${metric('待执行任务',String(state.maintenanceProgram.tasks.filter(x=>x.status==='PLANNED').length),'项','等待班组接单','warn')}${metric('执行中',String(state.maintenanceProgram.tasks.filter(x=>x.status==='IN_PROGRESS').length),'项','必须逐项提交')}${metric('未转工单缺陷',String(state.maintenanceProgram.defects.filter(x=>x.status==='OPEN').length),'项','需要人工判断','risk')}</div><section class="panel"><div class="panel-head"><div><h2>计划排程</h2><p>同一计划只允许存在一条未完成任务，防止定时任务重复派发。</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>计划</th><th>策略</th><th>下次到期</th><th>上次生成</th><th>当前任务</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="6">没有可排程计划。</td></tr>'}</tbody></table></div></section>`;
}

function inspectionTaskTable(){
  const rows=state.maintenanceProgram.tasks.map(task=>{const failed=task.checklist.filter(item=>item.result==='FAIL').length;const action=task.status==='PLANNED'?`<button class="table-action" data-action="startInspectionTask" data-id="${esc(task.taskNo)}">开始</button>`:task.status==='IN_PROGRESS'?`<button class="table-action" data-action="submitInspectionTask" data-id="${esc(task.taskNo)}">填写结果</button>`:'<span class="muted">已提交</span>';return `<tr class="${task.status==='DEFECT_FOUND'?'row-alert':''}"><td><strong>${esc(task.taskNo)}</strong><small>${esc(task.title)}</small></td><td>${esc(task.componentCode)}</td><td>${mpDate(task.scheduledAt)}</td><td>${esc(task.assignee)}</td><td>${tag(task.statusLabel||({PLANNED:'待执行',IN_PROGRESS:'执行中',CLOSED:'已完成',DEFECT_FOUND:'发现缺陷',CANCELLED:'已取消'}[task.status]||task.status),inspectionTone(task.statusLabel||({PLANNED:'待执行',IN_PROGRESS:'执行中',CLOSED:'已完成',DEFECT_FOUND:'发现缺陷'}[task.status])))}</td><td>${task.checklist.length}项 / 异常${failed}项</td><td>${esc(task.conclusion||'—')}</td><td>${action}</td></tr>`;}).join('');
  return `<section class="panel"><div class="panel-head"><div><h2>点检任务</h2><p>先开始任务，再逐项记录测量值、PASS/FAIL和备注；必检项不能跳过。</p></div><span class="mini-badge">${state.maintenanceProgram.tasks.length}条</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>任务 / 内容</th><th>部件</th><th>计划时间</th><th>执行组</th><th>状态</th><th>完成情况</th><th>结论</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="8">尚未生成点检任务。</td></tr>'}</tbody></table></div></section>`;
}

function defectTable(){
  const rows=state.maintenanceProgram.defects.map(defect=>`<tr class="${defect.status==='OPEN'?'row-alert':''}"><td><strong>${esc(defect.defectNo)}</strong><small>${esc(defect.taskNo)}</small></td><td>${tag(defect.severity,defect.severity.includes('严重')?'severe':'warn')}</td><td><strong>${esc(defect.description)}</strong><small>${esc(defect.evidenceSummary)}</small></td><td>${esc(defect.reporter)}<small>${mpDate(defect.discoveredAt)}</small></td><td>${tag(defect.status==='OPEN'?'待处置':'已转工单',defectTone(defect.status))}</td><td>${defect.workOrderNo?`<span class="tag good">${esc(defect.workOrderNo)}</span>`:`<button class="table-action" data-action="defectToWorkOrder" data-id="${esc(defect.defectNo)}">转工单</button>`}</td></tr>`).join('');
  return `<section class="panel"><div class="panel-head"><div><h2>点检缺陷</h2><p>缺陷保留原任务和失败检查项作为依据，人工确认后进入工单审批。</p></div><span class="mini-badge">${state.maintenanceProgram.defects.length}项</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>缺陷 / 来源任务</th><th>等级</th><th>描述与依据</th><th>发现人</th><th>状态</th><th>处置</th></tr></thead><tbody>${rows||'<tr><td colspan="6">暂无点检缺陷。</td></tr>'}</tbody></table></div></section>`;
}

function renderMaintenanceProgram(){const pending=maintenanceProgramPending();const body=state.page==='strategy'?strategyTable():state.page==='maintenance-plan'?planTable():`${inspectionTaskTable()}<div class="mt-12">${defectTable()}</div>`;return `<div class="page">${maintenanceProgramHead()}${maintenanceProgramTabs()}<div class="notice-bar"><strong>业务边界</strong><span>维护策略生成点检任务；点检异常生成缺陷；缺陷需人工转工单。任何一步都不直接向PLC下发控制。</span>${tag('真实后端流程','good')}</div>${pending||body}</div>`;}

function openNewMaintenancePlan(){const asset=selectedMaintenanceAsset();openModal('维保管理','新建维护策略与计划',`<div class="form-grid"><div class="field"><label>设备</label><input value="${esc(asset.code)} · ${esc(asset.name)}" disabled/></div><div class="field"><label>部件编码</label><input id="mpComponent" value="${asset.code==='GT-01'?'GT01-GEARBOX':'设备本体'}"/></div><div class="field full"><label>计划名称</label><input id="mpName" value="${esc(asset.name)}关键部件状态点检"/></div><div class="field"><label>策略类型</label><select id="mpType"><option value="PERIODIC">周期维护</option><option value="CONDITION_BASED" selected>状态触发</option><option value="PREDICTIVE">预测触发</option></select></div><div class="field"><label>周期（天）</label><input id="mpCycle" type="number" min="1" max="3650" value="7"/></div><div class="field full"><label>触发条件</label><input id="mpTrigger" value="每7天，或关键测点达到关注阈值时人工确认后提前生成"/></div><div class="field"><label>责任班组</label><input id="mpOwner" value="${esc(asset.owner||'设备机修班')}"/></div><div class="field"><label>首次计划时间</label><input id="mpDue" type="datetime-local"/></div></div><div class="checklist-preview mt-12"><b>默认检查模板（3项）</b><span>关键参数复测：按配置上限判定</span><span>外观/紧固检查：无松动、裂纹和异常磨损</span><span>润滑/泄漏检查：无泄漏、润滑状态正常</span></div>`,'保存计划',createMaintenancePlan);}

async function createMaintenancePlan(){const asset=selectedMaintenanceAsset();const due=$('#mpDue')?.value;const prefix=asset.code.replace(/-/g,'');const payload={assetCode:asset.code,componentCode:$('#mpComponent')?.value,name:$('#mpName')?.value,strategyType:$('#mpType')?.value,cycleDays:Number($('#mpCycle')?.value),triggerCondition:$('#mpTrigger')?.value,ownerTeam:$('#mpOwner')?.value,nextDueAt:due?new Date(due).toISOString():null,checklist:[{itemId:`${prefix}-PARAM`,name:'关键参数复测',method:'规定工况采样并与配置上限比较',standard:'不超过当前测点配置上限',unit:'按测点',required:true},{itemId:`${prefix}-VISUAL`,name:'外观与紧固检查',method:'停机隔离后目视和紧固检查',standard:'无松动、裂纹和异常磨损',unit:'—',required:true},{itemId:`${prefix}-LUBE`,name:'润滑与泄漏检查',method:'目视检查，必要时采集油样',standard:'无泄漏，润滑状态正常',unit:'—',required:true}]};try{await apiRequest('/maintenance-plans',{method:'POST',body:JSON.stringify(payload)});await loadMaintenanceProgram();toast('维护策略、周期和检查模板已保存。');}catch(error){toast('计划保存失败：'+error.message);}}

function openGenerateInspection(planId){const plan=state.maintenanceProgram.plans.find(item=>item.planId===planId);if(!plan)return;openModal('维保计划','生成点检任务',`<div class="notice-bar"><strong>${esc(plan.name)}</strong><span>${esc(plan.assetCode)} · ${esc(plan.componentCode)} · ${plan.checklistTemplate.length}个检查项</span></div><div class="form-grid mt-12"><div class="field"><label>执行班组</label><input id="inspectionAssignee" value="${esc(plan.ownerTeam)}"/></div><div class="field"><label>计划执行时间</label><input id="inspectionScheduled" type="datetime-local"/></div></div>`,'生成待执行任务',()=>generateInspection(planId));}
async function generateInspection(planId){const scheduled=$('#inspectionScheduled')?.value;try{const task=await apiRequest(`/maintenance-plans/${encodeURIComponent(planId)}/inspection-tasks`,{method:'POST',body:JSON.stringify({assignee:$('#inspectionAssignee')?.value,scheduledAt:scheduled?new Date(scheduled).toISOString():null})});await loadMaintenanceProgram();toast(`已生成点检任务 ${task.taskNo}。`);}catch(error){toast('任务生成失败：'+error.message);}}

async function startInspection(taskNo){try{await apiRequest(`/inspection-tasks/${encodeURIComponent(taskNo)}/start`,{method:'PATCH',body:JSON.stringify({operator:'Demo点检员'})});await loadMaintenanceProgram();toast(`${taskNo} 已开始，必须逐项填写结果。`);}catch(error){toast('开始任务失败：'+error.message);}}

function openSubmitInspection(taskNo){const task=state.maintenanceProgram.tasks.find(item=>item.taskNo===taskNo);if(!task)return;const rows=task.checklist.map((item,index)=>`<div class="inspection-item"><div><b>${esc(item.name)}</b><small>${esc(item.method)} · 标准：${esc(item.standard)} ${item.required?'· 必检':''}</small></div><input id="inspectValue${index}" placeholder="测量值或观察结果"/><select id="inspectResult${index}"><option value="PASS">符合 PASS</option><option value="FAIL">不符合 FAIL</option>${item.required?'':'<option value="NA">不适用 NA</option>'}</select><input id="inspectRemark${index}" placeholder="备注"/></div>`).join('');openModal('点检执行',task.taskNo,`<div class="inspection-form">${rows}</div><div class="form-grid mt-12"><div class="field full"><label>点检结论</label><textarea id="inspectionConclusion">已按计划完成逐项检查，结果如上。</textarea></div><div class="field"><label>异常等级</label><select id="inspectionSeverity"><option>一般</option><option selected>严重</option><option>重大</option></select></div><div class="field"><label>执行人</label><input id="inspectionOperator" value="Demo点检员"/></div><div class="field full"><label>缺陷描述（存在FAIL时使用）</label><input id="inspectionDefectDescription" value="点检发现关键参数或现场状态不符合标准，需要进一步诊断处置"/></div></div>`,'提交点检结果',()=>submitInspection(taskNo));}

async function submitInspection(taskNo){const task=state.maintenanceProgram.tasks.find(item=>item.taskNo===taskNo);const items=task.checklist.map((item,index)=>({itemId:item.itemId,measuredValue:$(`#inspectValue${index}`)?.value,result:$(`#inspectResult${index}`)?.value,remark:$(`#inspectRemark${index}`)?.value}));const payload={items,conclusion:$('#inspectionConclusion')?.value,operator:$('#inspectionOperator')?.value,defectSeverity:$('#inspectionSeverity')?.value,defectDescription:$('#inspectionDefectDescription')?.value};try{const result=await apiRequest(`/inspection-tasks/${encodeURIComponent(taskNo)}/submit`,{method:'POST',body:JSON.stringify(payload)});await loadMaintenanceProgram();toast(result.defect?`发现异常并生成缺陷 ${result.defect.defectNo}。`:'点检全部通过，任务已完成。');}catch(error){toast('点检提交失败：'+error.message);}}

function openDefectWorkOrder(defectNo){const defect=state.maintenanceProgram.defects.find(item=>item.defectNo===defectNo);if(!defect)return;openModal('点检缺陷','转为待审批工单',`<div class="risk-confirm"><strong>来源证据：</strong>${esc(defect.evidenceSummary)}</div><div class="form-grid mt-12"><div class="field full"><label>工单主题</label><input id="defectWorkTitle" value="${esc(defect.assetName)}点检缺陷处置"/></div><div class="field"><label>责任班组</label><input id="defectWorkAssignee" value="设备机修班"/></div><div class="field"><label>建议窗口</label><input id="defectWorkWindow" value="待调度确认"/></div><div class="field"><label>操作人</label><input id="defectWorkOperator" value="Demo设备工程师"/></div></div>`,'创建待审批工单',()=>defectToWorkOrder(defectNo));}
async function defectToWorkOrder(defectNo){try{const defect=await apiRequest(`/maintenance-defects/${encodeURIComponent(defectNo)}/work-order`,{method:'POST',body:JSON.stringify({title:$('#defectWorkTitle')?.value,assignee:$('#defectWorkAssignee')?.value,plannedWindow:$('#defectWorkWindow')?.value,operator:$('#defectWorkOperator')?.value})});await loadBackendData();await loadMaintenanceProgram();toast(`缺陷已关联待审批工单 ${defect.workOrderNo}。`);}catch(error){toast('转工单失败：'+error.message);}}

const baseRenderPageMaintenanceProgram=renderPage;renderPage=function(){if(!MAINTENANCE_PROGRAM_PAGES.has(state.page))return baseRenderPageMaintenanceProgram();$('#pageView').innerHTML=renderMaintenanceProgram();syncNav();$('#content').scrollTop=0;bindPageEvents();};
const baseSetPageMaintenanceProgram=setPage;setPage=function(page){baseSetPageMaintenanceProgram(page);if(MAINTENANCE_PROGRAM_PAGES.has(page))loadMaintenanceProgram();};
const baseHandleActionMaintenanceProgram=handleAction;handleAction=function(event){const button=event.currentTarget,action=button.dataset.action;if(action==='reloadMaintenanceProgram')return loadMaintenanceProgram(true);if(action==='newMaintenancePlan')return openNewMaintenancePlan();if(action==='generateInspectionTask')return openGenerateInspection(button.dataset.id);if(action==='startInspectionTask')return startInspection(button.dataset.id);if(action==='submitInspectionTask')return openSubmitInspection(button.dataset.id);if(action==='defectToWorkOrder')return openDefectWorkOrder(button.dataset.id);return baseHandleActionMaintenanceProgram(event);};
const baseBindPageEventsMaintenanceProgram=bindPageEvents;bindPageEvents=function(){baseBindPageEventsMaintenanceProgram();const selector=$('#maintenanceAssetSelect');if(selector)selector.onchange=()=>{state.maintenanceProgram.assetCode=selector.value;state.maintenanceProgram.plans=[];state.maintenanceProgram.tasks=[];state.maintenanceProgram.defects=[];loadMaintenanceProgram();};};
