export type BusinessTone = 'success' | 'processing' | 'warning' | 'danger' | 'neutral';

export const businessCopyMap: Readonly<Record<string, string>> = Object.freeze({
  RECEIVED: '已接收',
  READY: '就绪',
  WAITING: '等待处理',
  PENDING_CONFIRM: '待确认',
  BLOCKED: '已阻断',
  AVAILABLE: '可用',
  BUSY: '忙碌',
  ASSIGNED: '已分配',
  READY_QUEUE: '待派工',
  DISPATCHED: '已派工',
  EXECUTING: '执行中',
  IN_PROGRESS: '处理中',
  ACKNOWLEDGED: '已确认',
  PENDING_REVIEW: '待复核',
  HANDLING: '处置中',
  CLOSED: '已关闭',
  LOCKED: '联锁锁定',
  OVERRIDE_PENDING: '解锁审批中',
  RESET_REQUESTED: '恢复申请中',
  RESTORED: '已恢复',
  PENDING_UPLOAD: '待上传',
  VALIDATING: '校验中',
  CONFLICT: '版本冲突',
  MERGED: '已合并',
  SUCCESS: '成功',
  FAILED: '失败',
  RECOGNITION: '识别',
  INSPECT: '检查',
  UNLOAD: '卸载',
  TRANSFER: '转运',
  STORAGE: '入库',
  LOAD: '装载',
  DEVICE_OFFLINE: '设备离线',
  DATA_CONFLICT: '数据冲突',
  INTERLOCK: '安全联锁',
  INTERLOCK_FORCE_STOP: '联锁强制停机',
  MANUAL_STOP: '人工停机',
  INTERFACE_TIMEOUT: '接口超时',
  PERSON_INTRUSION: '人员侵入',
  OFFLINE_PACKET: '离线数据包',
  SCENARIO: '模拟场景',
  TIMEOUT: '任务超时',
  INFO: '提示',
  MINOR: '一般',
  MAJOR: '重大',
  CRITICAL: '紧急',

  CONFIRMED: '已确认',
  DECOMPOSED: '已拆解',
  CANCELLED: '已取消',
  ADJUSTED: '已调整',
  FREE: '空闲',
  OCCUPIED: '占用中',
  RELEASING: '释放中',
  DRAFT: '草稿',
  COMPLETED: '已完成',
  PAUSED: '已暂停',
  PENDING: '待处理',
  REJECTED: '已拒绝',
  SKIPPED: '已跳过',
  OFFLINE: '离线',
  MAINTENANCE: '维护中',
  SUBMITTED: '已提交',
  APPROVED: '已批准',
  QUEUED: '排队中',
  CALLED: '已叫号',
  ENTERED: '已入场',
  OPERATING: '作业中',
  RELEASED: '已放行',
  EXITED: '已离场',
  NEED_FIX: '待补正',
  EXCEPTION: '异常',
  OPEN: '待处理',
  PASSED: '已通过',
  QUALITY: '质量异常',
  ESCALATED: '已升级',
  REOPENED: '已重开',
  WARN: '预警',
  PAUSE: '暂停作业',
  FORCE_STOP: '强制停机',
  TRIGGERED: '已触发',
  ACTION_ISSUED: '动作已下发',
  WAITING_RECEIPT: '等待回执',
  OVERRIDDEN: '已授权解锁',
  CACHED: '离线缓存',
  RETRY: '等待重试',
  UPLOADING: '上传中',
  RUNNING: '运行中',
  ACTIVE: '启用',
  DISABLED: '停用',
  PUBLISHED: '已发布',
  ROLLED_BACK: '已回滚',

  RECOGNITION_TASK: '识别任务',
  LOW: '低',
  MEDIUM: '中',
  HIGH: '高',
  URGENT: '紧急',
  WARNING: '预警',
  NONE: '无',
  FLY_ASH: '粉煤灰',
  STEEL: '钢材',
  CEMENT: '水泥',
  GENERAL_CARGO: '通用货物',
  TIPPER: '翻车机',
  CRANE: '起重机',
  CONVEYOR: '输送机',
  SILO: '筒仓',
  TEAM: '作业班组',
  AGV: '自动导引运输车（AGV）',
  DISPATCHER: '货场调度员',
  SHIFT_LEADER: '现场班组长',
  OPERATOR: '现场操作员',
  MAINTAINER: '设备维保人员',
  WAREHOUSE: '仓储管理员',
  GATE_GUARD: '门岗人员',
  DRIVER: '外来货车司机',
  SAFETY: '安环负责人',
  BUSINESS: '业主管理人员',
  REGULATOR: '监管人员',
  SYS_ADMIN: '系统管理员',
  INTERFACE_OPS: '接口运维人员',
  AUDITOR: '审计人员',
  BALANCED: '均衡调度',
  PRIORITY_FIRST: '优先级优先',
  RESOURCE_FIRST: '资源优先',
  SHIFT: '班次',
  DAILY: '日报',
  MONTHLY: '月报',
  CUSTOM: '自定义',
  PREVIEW_ONLY: '候选预览',
  DEMO_STABLE_MAPPING: '确定性规则映射',
  VALID: '校验通过',
  INVALID: '校验未通过',
  DUE: '时限内',
  OVERDUE: '已超时',
  OPEN_QUEUE: '待确认',
  REVIEW: '待复核',
  RESOLVED: '已解决',
  RESETTING: '恢复申请中',
  OVERRIDE: '解锁审批中',
  OVERLOAD: '超载风险',
  DEVICE_FAULT: '设备故障',
  VERSION_CONFLICT: '版本冲突',
  MANUAL_REVIEW: '人工复核',
  TOS: '生产调度管理系统（TOS）',
  PLC: '可编程逻辑控制器（PLC）',
  ECS: '设备控制系统（ECS）',
  UWB: '超宽带定位（UWB）',
  RAIL_PLAN: '铁路到发计划系统',
  'AREA-A': '一作业区',
  'AREA-B': '二作业区',
  'AREA-C': '三作业区',
  'AREA-1': '一作业区',
  'AREA-2': '二作业区',
  'AREA-3': '三作业区',
  ALL: '全部数据',
  GLOBAL: '全局数据',
  DENIED: '已拒绝',
  BUSINESS_ERROR: '业务错误',
  RECORDED: '已记录',
  IDEMPOTENT_HIT: '幂等命中',
  PLAN_CONFIRM: '计划确认',
  WORK_ORDER_DISPATCH: '工单派发',
  INTERLOCK_RECEIPT: '联锁回执',
  PLAN: '生产计划',
  WORK_ORDER: '作业工单',
  BASELINE: '基线数据',
  C03: '演示会话与权限',
  C04: '外部到发信息台账',
  C05: '生产准备建议',
  C06: '任务拆解',
  C07: '派工与执行',
  C08: '异常处置',
  C09: '安全联锁',
  C10: '离线同步',
  C11: '统计报表',
  UNKNOWN: '未知',
  'exception-handling': '异常处置',
  'safety-interlock': '安全联锁',
  'offline-sync': '离线同步',
  'dispatch-overview': '调度总览',
  'plan-entry': '外部到发信息台账',
  reports: '统计报表',
  MISSING_FIELD: '字段缺失',
  SYNCED: '已同步',
  DEGRADED: '服务降级',
  CIRCUIT_OPEN: '熔断保护',
  HEALTHY: '正常',
  UNAVAILABLE: '不可用',
  VALIDATION_MISSING_FIELD: '校验字段缺失',
  SOURCE_DATA_CONFLICT: '来源数据冲突',
  SUPPLEMENT: '人工补录',
});

const successValues = new Set([
  'RECEIVED',
  'READY',
  'AVAILABLE',
  'ASSIGNED',
  'ACKNOWLEDGED',
  'CLOSED',
  'RESTORED',
  'MERGED',
  'SUCCESS',
  'CONFIRMED',
  'DECOMPOSED',
  'COMPLETED',
  'APPROVED',
  'PASSED',
  'PUBLISHED',
  'ACTIVE',
  'VALID',
]);

const processingValues = new Set([
  'DISPATCHED',
  'EXECUTING',
  'IN_PROGRESS',
  'HANDLING',
  'VALIDATING',
  'RELEASING',
  'OCCUPIED',
  'QUEUED',
  'OPERATING',
  'TRIGGERED',
  'ACTION_ISSUED',
  'WAITING_RECEIPT',
  'UPLOADING',
  'RUNNING',
]);

const warningValues = new Set([
  'WAITING',
  'PENDING_CONFIRM',
  'BUSY',
  'READY_QUEUE',
  'PENDING_REVIEW',
  'OVERRIDE_PENDING',
  'RESET_REQUESTED',
  'PENDING_UPLOAD',
  'CONFLICT',
  'TIMEOUT',
  'MINOR',
  'MAJOR',
  'PENDING',
  'PAUSED',
  'MAINTENANCE',
  'NEED_FIX',
  'OPEN',
  'WARN',
  'CACHED',
  'RETRY',
  'DUE',
  'OVERDUE',
]);

const dangerValues = new Set([
  'BLOCKED',
  'LOCKED',
  'FAILED',
  'CRITICAL',
  'DEVICE_OFFLINE',
  'DATA_CONFLICT',
  'INTERLOCK',
  'REJECTED',
  'ESCALATED',
  'FORCE_STOP',
  'INVALID',
]);

const internalEnumPattern = /^[A-Z][A-Z0-9_]{2,}$/;

export function businessLabel(value: string | null | undefined): string {
  if (!value) return '未提供';
  const normalized = value.trim();
  const mapped = businessCopyMap[normalized];
  if (mapped) return mapped;
  return internalEnumPattern.test(normalized)
    ? '未配置展示文案'
    : normalized.replace(/\s*\bDemo\b\s*/gi, '演示');
}

export function businessJson(value: unknown): string {
  return JSON.stringify(value, (_key, item: unknown) =>
    typeof item === 'string' ? businessLabel(item) : item, 2);
}

export function businessTone(value: string | null | undefined): BusinessTone {
  if (!value) return 'neutral';
  if (successValues.has(value)) return 'success';
  if (processingValues.has(value)) return 'processing';
  if (warningValues.has(value)) return 'warning';
  if (dangerValues.has(value)) return 'danger';
  return 'neutral';
}

export function businessCode(value: string | null | undefined): string | undefined {
  return value || undefined;
}

export type IndustryTerm = 'TOS' | 'PLC' | 'ECS' | 'AGV' | 'UWB';

const industryTermLabels: Readonly<Record<IndustryTerm, string>> = {
  TOS: '生产调度管理系统（TOS）',
  PLC: '可编程逻辑控制器（PLC）',
  ECS: '设备控制系统（ECS）',
  AGV: '自动导引运输车（AGV）',
  UWB: '超宽带定位（UWB）',
};

export function industryTermLabel(value: IndustryTerm): string {
  return industryTermLabels[value];
}
