package com.mt.wms.inventory;

import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Repository
class InventoryRepository {
    private final JdbcClient jdbc;
    InventoryRepository(JdbcClient jdbc){this.jdbc=jdbc;}

    List<InventoryModels.BalanceView> balances(long companyId,long warehouseId,long ownerId){return jdbc.sql("""
        SELECT b.id,g.code AS good_code,g.name AS good_name,g.barcode,l.code AS location_code,
               b.batch_code,b.quality_type,b.supplier_code,b.product_date,b.expire_date,b.lpn,
               b.available_qty,b.allocated_qty,b.frozen_qty,
               (b.available_qty+b.allocated_qty+b.frozen_qty) AS total_qty,b.version
          FROM inv_balance b JOIN wms_good g ON g.id=b.good_id JOIN wms_location l ON l.id=b.location_id
         WHERE b.company_id=:c AND b.warehouse_id=:w AND b.owner_id=:o
           AND (b.available_qty+b.allocated_qty+b.frozen_qty)>0
         ORDER BY g.code,l.code,b.batch_code
        """).param("c",companyId).param("w",warehouseId).param("o",ownerId).query(InventoryModels.BalanceView.class).list();}

    InventoryModels.BalanceView view(long balanceId,long companyId,long warehouseId,long ownerId){return jdbc.sql("""
        SELECT b.id,g.code AS good_code,g.name AS good_name,g.barcode,l.code AS location_code,
               b.batch_code,b.quality_type,b.supplier_code,b.product_date,b.expire_date,b.lpn,
               b.available_qty,b.allocated_qty,b.frozen_qty,
               (b.available_qty+b.allocated_qty+b.frozen_qty) AS total_qty,b.version
          FROM inv_balance b JOIN wms_good g ON g.id=b.good_id JOIN wms_location l ON l.id=b.location_id
         WHERE b.id=:id AND b.company_id=:c AND b.warehouse_id=:w AND b.owner_id=:o
        """).param("id",balanceId).param("c",companyId).param("w",warehouseId).param("o",ownerId).query(InventoryModels.BalanceView.class).optional().orElseThrow(()->new IllegalArgumentException("库存不存在"));}

    Optional<BalanceRow> lock(long id,long c,long w,long o){return jdbc.sql("SELECT id,good_id,location_id,batch_code,quality_type,supplier_code,product_date,expire_date,lpn,available_qty,allocated_qty,frozen_qty,version FROM inv_balance WHERE id=:id AND company_id=:c AND warehouse_id=:w AND owner_id=:o FOR UPDATE").param("id",id).param("c",c).param("w",w).param("o",o).query(BalanceRow.class).optional();}
    Optional<BalanceRow> lockDimension(long c,long w,long o,long locationId,long goodId,String batch,String quality,String supplier,String lpn){return jdbc.sql("SELECT id,good_id,location_id,batch_code,quality_type,supplier_code,product_date,expire_date,lpn,available_qty,allocated_qty,frozen_qty,version FROM inv_balance WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND location_id=:l AND good_id=:g AND batch_code=:b AND quality_type=:q AND supplier_code=:s AND lpn=:lpn FOR UPDATE").param("c",c).param("w",w).param("o",o).param("l",locationId).param("g",goodId).param("b",batch).param("q",quality).param("s",supplier).param("lpn",lpn).query(BalanceRow.class).optional();}
    long goodId(long c,long o,String code){return jdbc.sql("SELECT id FROM wms_good WHERE company_id=:c AND owner_id=:o AND (code=:code OR barcode=:code) AND status='ENABLED'").param("c",c).param("o",o).param("code",code).query(Long.class).optional().orElseThrow(()->new IllegalArgumentException("货品不存在或已停用"));}
    long locationId(long c,long w,String code){return jdbc.sql("SELECT id FROM wms_location WHERE company_id=:c AND warehouse_id=:w AND code=:code AND status='ENABLED'").param("c",c).param("w",w).param("code",code).query(Long.class).optional().orElseThrow(()->new IllegalArgumentException("库位不存在或已停用"));}
    long createBalance(long c,long w,long o,long l,long g,String batch,String quality,String supplier,LocalDate product,LocalDate expire,String lpn){return jdbc.sql("INSERT INTO inv_balance(company_id,warehouse_id,owner_id,location_id,good_id,batch_code,quality_type,supplier_code,product_date,expire_date,lpn) VALUES(:c,:w,:o,:l,:g,:b,:q,:s,:p,:e,:lpn) RETURNING id").param("c",c).param("w",w).param("o",o).param("l",l).param("g",g).param("b",batch).param("q",quality).param("s",supplier).param("p",product).param("e",expire).param("lpn",lpn).query(Long.class).single();}
    void updateQuantities(long id,BigDecimal available,BigDecimal allocated,BigDecimal frozen){int n=jdbc.sql("UPDATE inv_balance SET available_qty=:a,allocated_qty=:al,frozen_qty=:f,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("a",available).param("al",allocated).param("f",frozen).param("id",id).update();if(n!=1)throw new IllegalArgumentException("库存更新失败");}
    boolean processed(long c,String key){return jdbc.sql("SELECT count(*) FROM inv_transaction WHERE company_id=:c AND idempotency_key IN (:key,:outKey,:inKey)").param("c",c).param("key",key).param("outKey",key+":OUT").param("inKey",key+":IN").query(Integer.class).single()>0;}
    long operation(long c,long w,long o,String code,String type,long userId,String remark){return operation(c,w,o,code,type,userId,remark,null);}
    long operation(long c,long w,long o,String code,String type,long userId,String remark,String idempotencyKey){return jdbc.sql("INSERT INTO inv_operation(company_id,warehouse_id,owner_id,operation_code,operation_type,state,operator_user_id,remark,idempotency_key,completed_at) VALUES(:c,:w,:o,:code,:type,'EXECUTED',:u,:remark,:key,CURRENT_TIMESTAMP) RETURNING id").param("c",c).param("w",w).param("o",o).param("code",code).param("type",type).param("u",userId).param("remark",remark).param("key",idempotencyKey).query(Long.class).single();}
    boolean operationProcessed(long c,String key){return jdbc.sql("SELECT count(*) FROM inv_operation WHERE company_id=:c AND idempotency_key=:key").param("c",c).param("key",key).query(Integer.class).single()>0;}
    void line(long op,long good,Long source,Long dest,long balance,BigDecimal system,BigDecimal requested,BigDecimal actual,BigDecimal diff,String batch,String quality,String remark){jdbc.sql("INSERT INTO inv_operation_line(operation_id,good_id,source_location_id,destination_location_id,balance_id,system_qty,requested_qty,actual_qty,difference_qty,batch_code,quality_type,remark) VALUES(:op,:g,:s,:d,:b,:system,:requested,:actual,:diff,:batch,:quality,:remark)").param("op",op).param("g",good).param("s",source).param("d",dest).param("b",balance).param("system",system).param("requested",requested).param("actual",actual).param("diff",diff).param("batch",batch).param("quality",quality).param("remark",remark).update();}
    void transaction(long c,long w,long o,long balance,long good,long location,String type,String operation,BigDecimal before,BigDecimal change,BigDecimal after,BigDecimal ab,BigDecimal ac,BigDecimal aa,BigDecimal fb,BigDecimal fc,BigDecimal fa,Long related,String key,long user,String remark){jdbc.sql("INSERT INTO inv_transaction(company_id,warehouse_id,owner_id,balance_id,good_id,location_id,transaction_type,operation_code,quantity_before,quantity_change,quantity_after,available_before,available_change,available_after,frozen_before,frozen_change,frozen_after,related_location_id,idempotency_key,operator_user_id,remark) VALUES(:c,:w,:o,:balance,:g,:l,:type,:op,:before,:change,:after,:ab,:ac,:aa,:fb,:fc,:fa,:related,:key,:u,:remark)").param("c",c).param("w",w).param("o",o).param("balance",balance).param("g",good).param("l",location).param("type",type).param("op",operation).param("before",before).param("change",change).param("after",after).param("ab",ab).param("ac",ac).param("aa",aa).param("fb",fb).param("fc",fc).param("fa",fa).param("related",related).param("key",key).param("u",user).param("remark",remark).update();}

    List<InventoryModels.TransactionView> transactions(long c,long w,long o){return jdbc.sql("SELECT t.id,t.transaction_type,t.operation_code,g.code AS good_code,l.code AS location_code,t.quantity_before,t.quantity_change,t.quantity_after,rl.code AS related_location_code,t.remark,u.display_name AS operator_name,t.created_at FROM inv_transaction t JOIN wms_good g ON g.id=t.good_id JOIN wms_location l ON l.id=t.location_id LEFT JOIN wms_location rl ON rl.id=t.related_location_id JOIN auth_user u ON u.id=t.operator_user_id WHERE t.company_id=:c AND t.warehouse_id=:w AND t.owner_id=:o ORDER BY t.id DESC LIMIT 200").param("c",c).param("w",w).param("o",o).query(InventoryModels.TransactionView.class).list();}
    List<InventoryModels.WarningView> warnings(long c,long w,long o){return jdbc.sql("SELECT CASE WHEN COALESCE(sum(b.available_qty+b.allocated_qty+b.frozen_qty),0)<g.min_quantity THEN 'LOW' ELSE 'HIGH' END AS level,g.code AS good_code,g.name AS good_name,COALESCE(sum(b.available_qty+b.allocated_qty+b.frozen_qty),0) AS current_qty,CASE WHEN COALESCE(sum(b.available_qty+b.allocated_qty+b.frozen_qty),0)<g.min_quantity THEN g.min_quantity ELSE g.max_quantity END AS threshold_qty FROM wms_good g LEFT JOIN inv_balance b ON b.good_id=g.id AND b.warehouse_id=:w WHERE g.company_id=:c AND g.owner_id=:o AND (g.min_quantity>0 OR g.max_quantity>0) GROUP BY g.id,g.code,g.name,g.min_quantity,g.max_quantity HAVING COALESCE(sum(b.available_qty+b.allocated_qty+b.frozen_qty),0)<g.min_quantity OR (g.max_quantity>0 AND COALESCE(sum(b.available_qty+b.allocated_qty+b.frozen_qty),0)>g.max_quantity) ORDER BY g.code").param("c",c).param("w",w).param("o",o).query(InventoryModels.WarningView.class).list();}
    BigDecimal serialTracked(long balance){return jdbc.sql("SELECT COALESCE(sum(quantity),0) FROM inv_serial WHERE balance_id=:b AND state='ACTIVE'").param("b",balance).query(BigDecimal.class).single();}
    long createSerial(long c,long w,long o,BalanceRow b,String code,BigDecimal qty,BigDecimal weight,String source){return jdbc.sql("INSERT INTO inv_serial(company_id,warehouse_id,owner_id,balance_id,good_id,location_id,serial_code,quantity,weight_kg,source) VALUES(:c,:w,:o,:b,:g,:l,:code,:qty,:weight,:source) RETURNING id").param("c",c).param("w",w).param("o",o).param("b",b.id()).param("g",b.goodId()).param("l",b.locationId()).param("code",code).param("qty",qty).param("weight",weight).param("source",source).query(Long.class).single();}
    InventoryModels.SerialView serial(long id,long c,long w,long o){return jdbc.sql("SELECT s.id,s.serial_code,g.code AS good_code,g.name AS good_name,l.code AS location_code,s.quantity,s.weight_kg,s.source,s.state,s.printed,s.created_at FROM inv_serial s JOIN wms_good g ON g.id=s.good_id JOIN wms_location l ON l.id=s.location_id WHERE s.id=:id AND s.company_id=:c AND s.warehouse_id=:w AND s.owner_id=:o").param("id",id).param("c",c).param("w",w).param("o",o).query(InventoryModels.SerialView.class).optional().orElseThrow(()->new IllegalArgumentException("标签不存在"));}
    List<InventoryModels.SerialView> serials(long c,long w,long o){return jdbc.sql("SELECT s.id,s.serial_code,g.code AS good_code,g.name AS good_name,l.code AS location_code,s.quantity,s.weight_kg,s.source,s.state,s.printed,s.created_at FROM inv_serial s JOIN wms_good g ON g.id=s.good_id JOIN wms_location l ON l.id=s.location_id WHERE s.company_id=:c AND s.warehouse_id=:w AND s.owner_id=:o ORDER BY s.id DESC LIMIT 200").param("c",c).param("w",w).param("o",o).query(InventoryModels.SerialView.class).list();}

    List<InventoryModels.ReplenishmentRuleView> replenishmentRules(long c,long w,long o){return jdbc.sql("""
        SELECT r.id,g.code AS good_code,g.name AS good_name,l.code AS location_code,r.min_qty,r.max_qty,
               COALESCE((SELECT sum(b.available_qty+b.allocated_qty+b.frozen_qty) FROM inv_balance b WHERE b.warehouse_id=r.warehouse_id AND b.owner_id=r.owner_id AND b.location_id=r.location_id AND b.good_id=r.good_id),0) AS current_qty,
               CASE WHEN COALESCE((SELECT sum(b.available_qty+b.allocated_qty+b.frozen_qty) FROM inv_balance b WHERE b.warehouse_id=r.warehouse_id AND b.owner_id=r.owner_id AND b.location_id=r.location_id AND b.good_id=r.good_id),0)<r.min_qty
                    THEN r.max_qty-COALESCE((SELECT sum(b.available_qty+b.allocated_qty+b.frozen_qty) FROM inv_balance b WHERE b.warehouse_id=r.warehouse_id AND b.owner_id=r.owner_id AND b.location_id=r.location_id AND b.good_id=r.good_id),0) ELSE 0 END AS suggested_qty,
               r.status,r.remark
          FROM inv_replenishment_rule r JOIN wms_good g ON g.id=r.good_id JOIN wms_location l ON l.id=r.location_id
         WHERE r.company_id=:c AND r.warehouse_id=:w AND r.owner_id=:o ORDER BY r.id
        """).param("c",c).param("w",w).param("o",o).query(InventoryModels.ReplenishmentRuleView.class).list();}
    long saveReplenishmentRule(Long id,long c,long w,long o,long good,long location,BigDecimal min,BigDecimal max,String status,String remark){
        if(id==null)return jdbc.sql("INSERT INTO inv_replenishment_rule(company_id,warehouse_id,owner_id,good_id,location_id,min_qty,max_qty,status,remark) VALUES(:c,:w,:o,:g,:l,:min,:max,:status,:remark) RETURNING id").param("c",c).param("w",w).param("o",o).param("g",good).param("l",location).param("min",min).param("max",max).param("status",status).param("remark",remark).query(Long.class).single();
        int n=jdbc.sql("UPDATE inv_replenishment_rule SET good_id=:g,location_id=:l,min_qty=:min,max_qty=:max,status=:status,remark=:remark,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND company_id=:c AND warehouse_id=:w AND owner_id=:o").param("g",good).param("l",location).param("min",min).param("max",max).param("status",status).param("remark",remark).param("id",id).param("c",c).param("w",w).param("o",o).update();
        if(n!=1)throw new IllegalArgumentException("补货规则不存在");return id;
    }
    InventoryModels.ReplenishmentRuleView replenishmentRuleView(long id,long c,long w,long o){return replenishmentRules(c,w,o).stream().filter(x->x.id()==id).findFirst().orElseThrow(()->new IllegalArgumentException("补货规则不存在"));}
    List<RuleRow> activeRulesForUpdate(long c,long w,long o){return jdbc.sql("SELECT id,good_id,location_id,min_qty,max_qty FROM inv_replenishment_rule WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND status='ENABLED' ORDER BY id FOR UPDATE").param("c",c).param("w",w).param("o",o).query(RuleRow.class).list();}
    BigDecimal quantityAt(long w,long o,long location,long good){return jdbc.sql("SELECT COALESCE(sum(available_qty+allocated_qty+frozen_qty),0) FROM inv_balance WHERE warehouse_id=:w AND owner_id=:o AND location_id=:l AND good_id=:g").param("w",w).param("o",o).param("l",location).param("g",good).query(BigDecimal.class).single();}
    List<BalanceRow> replenishSources(long c,long w,long o,long good,long destination){return jdbc.sql("SELECT id,good_id,location_id,batch_code,quality_type,supplier_code,product_date,expire_date,lpn,available_qty,allocated_qty,frozen_qty,version FROM inv_balance WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND good_id=:g AND location_id<>:d AND available_qty>0 ORDER BY available_qty DESC,id FOR UPDATE").param("c",c).param("w",w).param("o",o).param("g",good).param("d",destination).query(BalanceRow.class).list();}

    record BalanceRow(Long id,Long goodId,Long locationId,String batchCode,String qualityType,String supplierCode,LocalDate productDate,LocalDate expireDate,String lpn,BigDecimal availableQty,BigDecimal allocatedQty,BigDecimal frozenQty,long version){BigDecimal total(){return availableQty.add(allocatedQty).add(frozenQty);}}
    record RuleRow(Long id,Long goodId,Long locationId,BigDecimal minQty,BigDecimal maxQty){}
}
