package com.bdemo.energy.suggestion;

import com.bdemo.common.BusinessException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Service
public class SuggestionService {
    private static final DateTimeFormatter DT=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final Map<String,Set<String>> LEGAL=Map.of("pending",Set.of("dispatched","deferred","invalid_closed"),"dispatched",Set.of("executing","deferred"),"executing",Set.of("verifying","deferred"),"verifying",Set.of("valid_closed","invalid_closed"),"deferred",Set.of("pending","dispatched","executing"));
    private final JdbcTemplate jdbc;private final ObjectMapper json;private final LocalDateTime now;
    public SuggestionService(JdbcTemplate jdbc,ObjectMapper json,@Value("${b-demo.demo-now}")LocalDateTime now){this.jdbc=jdbc;this.json=json;this.now=now;}

    public Map<String,Object> list(String status,String source,String rule,String zone,String band,int page,int size){if(page<1||size<1||size>100)throw new IllegalArgumentException("分页参数无效");StringBuilder w=new StringBuilder(" WHERE 1=1");List<Object>p=new ArrayList<>();add(w,p," AND s.status=?",status);add(w,p," AND s.source_type=?",source);add(w,p," AND s.rule_code=?",rule);add(w,p," AND s.priority_band=?",band);if(!"ALL".equalsIgnoreCase(zone))add(w,p," AND a.area_code=?","AREA-"+zone.toUpperCase());Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM e_suggestion s LEFT JOIN e_area a ON a.area_id=s.area_id"+w,Integer.class,p.toArray());List<Object>q=new ArrayList<>(p);q.add(size);q.add((page-1)*size);List<Map<String,Object>>items=jdbc.queryForList("""
            SELECT s.*,a.area_code,a.area_name,e.equipment_code,e.equipment_name FROM e_suggestion s
            LEFT JOIN e_area a ON a.area_id=s.area_id LEFT JOIN e_equipment e ON e.equipment_id=s.equipment_id
            """+w+" ORDER BY s.priority_score DESC,s.suggestion_id DESC LIMIT ? OFFSET ?",q.toArray()).stream().map(this::item).toList();List<Map<String,Object>>counts=jdbc.queryForList("SELECT status,COUNT(*) count FROM e_suggestion GROUP BY status");Map<String,Object>board=new LinkedHashMap<>();for(Map<String,Object>r:counts)board.put(String.valueOf(r.get("status")),r.get("count"));return map("items",items,"total",total,"boardCounts",board,"filters",map("status",status,"sourceType",source,"ruleCode",rule,"zone",zone,"priorityBand",band,"pageNum",page,"pageSize",size));}
    public Map<String,Object> retrospective(String month,String zone,String rule){String target=month==null?now.toString().substring(0,7):month;StringBuilder w=new StringBuilder(" WHERE s.status IN ('valid_closed','invalid_closed','closed') AND DATE_FORMAT(s.closed_at,'%Y-%m')=?");List<Object>p=new ArrayList<>(List.of(target));if(!"ALL".equalsIgnoreCase(zone))add(w,p," AND a.area_code=?","AREA-"+zone.toUpperCase());add(w,p," AND s.rule_code=?",rule);List<Map<String,Object>>items=jdbc.queryForList("SELECT s.*,a.area_code,a.area_name,e.equipment_code,e.equipment_name FROM e_suggestion s LEFT JOIN e_area a ON a.area_id=s.area_id LEFT JOIN e_equipment e ON e.equipment_id=s.equipment_id"+w+" ORDER BY s.closed_at DESC",p.toArray()).stream().map(this::item).toList();return map("month",target,"items",items,"total",items.size(),"summary",map("savingValue",items.stream().mapToDouble(i->num(i.get("savingValue"))).sum(),"closedCount",items.size()));}
    public Map<String,Object> detail(long id){Map<String,Object>r=load(id);List<Map<String,Object>>flows=jdbc.queryForList("SELECT * FROM e_suggestion_flow_log WHERE suggestion_id=? ORDER BY occur_time,flow_id",id).stream().map(this::flow).toList();List<Map<String,Object>>verification=jdbc.queryForList("SELECT * FROM e_suggestion_verification WHERE suggestion_id=? ORDER BY version",id).stream().map(this::verification).toList();return map("suggestion",item(r),"sourceSnapshot",jsonObj(r.get("source_snapshot_json")),"templateSnapshot",jsonObj(r.get("template_snapshot_json")),"flows",flows,"latestVerification",verification.isEmpty()?null:verification.get(verification.size()-1),"verificationHistory",verification,"closeInfo",map("closeType",r.get("close_type"),"closeReason",r.get("close_reason"),"closedBy",r.get("closed_by"),"closedAt",format(r.get("closed_at"))),"allowedActions",actions(String.valueOf(r.get("status"))));}

    @Transactional public Map<String,Object> create(Map<String,Object>b,String user){req(b,"title","measureContent","objectType");long id=insertSuggestion(b,user,"manual",null,null,"{}");flow(id,null,"pending",user,"create",String.valueOf(b.getOrDefault("remark","人工创建")),"{}");return map("suggestion",detail(id).get("suggestion"),"created",true);}
    @Transactional public Map<String,Object> fromAlert(long eventId,Map<String,Object>b,String user){List<Map<String,Object>>events=jdbc.queryForList("SELECT * FROM e_alert_event WHERE event_id=?",eventId);if(events.isEmpty())throw new BusinessException(404,"告警事件不存在");List<Long>old=jdbc.query("SELECT suggestion_id FROM e_suggestion WHERE source_alert_id=?",(rs,n)->rs.getLong(1),eventId);if(!old.isEmpty())return map("suggestion",detail(old.get(0)).get("suggestion"),"created",false);Map<String,Object>e=events.get(0);Map<String,Object>tpl=templateFor(b.get("templateCode"),e.get("rule_code"));Map<String,Object>body=new LinkedHashMap<>(b);body.putIfAbsent("title",tpl.getOrDefault("template_name",e.get("rule_code")+" 节能建议"));body.putIfAbsent("measureContent",tpl.getOrDefault("action_content","请核查并实施节能措施"));body.put("objectType",e.get("object_type"));body.put("objectId",e.get("object_id"));body.put("areaId",e.get("area_id"));long id=insertSuggestion(body,user,"rule",eventId,e.get("rule_code"),toJson(tpl));flow(id,null,"pending",user,"create","告警转建议",toJson(map("sourceAlertId",eventId)));return map("suggestion",detail(id).get("suggestion"),"created",true);}
    @Transactional public Map<String,Object> transition(long id,Map<String,Object>b,String user){Map<String,Object>r=loadForUpdate(id);checkVersion(r,b);String from=String.valueOf(r.get("status")),to=String.valueOf(b.get("toStatus"));if(!LEGAL.getOrDefault(from,Set.of()).contains(to))throw new BusinessException(409,"非法建议迁移："+from+" -> "+to);String assigned=String.valueOf(b.getOrDefault("assignedTo",r.get("responsible_user")));boolean closed=to.endsWith("closed");jdbc.update("UPDATE e_suggestion SET status=?,responsible_user=?,close_type=?,close_reason=?,closed_by=?,closed_at=?,row_version=row_version+1,update_time=? WHERE suggestion_id=? AND row_version=?",to,assigned,closed?b.getOrDefault("closeType","valid_closed".equals(to)?"implemented":"invalid"):r.get("close_type"),closed?b.get("closeReason"):r.get("close_reason"),closed?user:null,closed?Timestamp.valueOf(now):null,Timestamp.valueOf(now),id,r.get("row_version"));flow(id,from,to,user,"transition",String.valueOf(b.getOrDefault("remark","状态流转")),toJson(b));return detail(id);}
    @Transactional public Map<String,Object> activity(long id,Map<String,Object>b,String user){Map<String,Object>r=loadForUpdate(id);checkVersion(r,b);jdbc.update("UPDATE e_suggestion SET attachments_json=?,row_version=row_version+1,update_time=? WHERE suggestion_id=?",toJson(b.getOrDefault("attachments",jsonList(r.get("attachments_json")))),Timestamp.valueOf(now),id);flow(id,String.valueOf(r.get("status")),String.valueOf(r.get("status")),user,"activity",String.valueOf(b.get("remark")),toJson(b));return detail(id);}
    @Transactional public Map<String,Object> verify(long id,Map<String,Object>b,String user){Map<String,Object>r=loadForUpdate(id);checkVersion(r,b);if(r.get("repair_at")==null||r.get("baseline_start")==null||r.get("baseline_end")==null||r.get("report_start")==null||r.get("report_end")==null)throw new BusinessException(409,"验证时间窗不完整");Integer v=jdbc.queryForObject("SELECT COALESCE(MAX(version),0)+1 FROM e_suggestion_verification WHERE suggestion_id=?",Integer.class,id);jdbc.update("INSERT INTO e_suggestion_verification(suggestion_id,version,status,repair_at,baseline_start,baseline_end,report_start,report_end,usage_comparison_json,cost_comparison_json,workload_comparison_json,quality_comparison_json,saving_value,saving_unit,saving_pct,calculation_note,formula_version,signature,generated_by,generated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,v,"completed",r.get("repair_at"),r.get("baseline_start"),r.get("baseline_end"),r.get("report_start"),r.get("report_end"),"{}","{}","{}","{}",0,r.getOrDefault("saving_unit","kWh"),0,"演示数据同步验证","R06-V1","VERIFY-"+id+"-"+v,user,Timestamp.valueOf(now));jdbc.update("UPDATE e_suggestion SET row_version=row_version+1,update_time=? WHERE suggestion_id=?",Timestamp.valueOf(now),id);flow(id,String.valueOf(r.get("status")),String.valueOf(r.get("status")),user,"verify","生成验证快照",toJson(b));return detail(id);}

    public Map<String,Object> templates(String rule,String category,String objectType,Boolean enabled){StringBuilder w=new StringBuilder(" WHERE 1=1");List<Object>p=new ArrayList<>();add(w,p," AND source_rule_code=?",rule);add(w,p," AND category=?",category);add(w,p," AND applicable_object_type=?",objectType);if(enabled!=null){w.append(" AND enabled=?");p.add(enabled?1:0);}List<Map<String,Object>>items=jdbc.queryForList("SELECT * FROM e_suggestion_template"+w+" ORDER BY template_code,version DESC",p.toArray()).stream().map(this::template).toList();return map("items",items,"total",items.size(),"filters",map("ruleCode",rule,"category",category,"objectType",objectType,"enabled",enabled));}
    @Transactional public Map<String,Object> createTemplate(Map<String,Object>b){req(b,"templateCode","templateName","category","applicableObjectType","actionContent");long id=insertTemplate(b,1);return map("template",template(first("SELECT * FROM e_suggestion_template WHERE template_id=?",id)));}
    @Transactional public Map<String,Object> updateTemplate(long id,Map<String,Object>b){Map<String,Object>old=first("SELECT * FROM e_suggestion_template WHERE template_id=?",id);if(old.isEmpty())throw new BusinessException(404,"模板不存在");Map<String,Object>merged=new LinkedHashMap<>(old);merged.putAll(b);merged.put("templateCode",old.get("template_code"));merged.put("templateName",b.getOrDefault("templateName",old.get("template_name")));merged.put("applicableObjectType",b.getOrDefault("applicableObjectType",old.get("applicable_object_type")));merged.put("actionContent",b.getOrDefault("actionContent",old.get("action_content")));merged.put("category",b.getOrDefault("category",old.get("category")));long next=insertTemplate(merged,((Number)old.get("version")).intValue()+1);return map("template",template(first("SELECT * FROM e_suggestion_template WHERE template_id=?",next)),"previousTemplateId",id);}

    private long insertSuggestion(Map<String,Object>b,String user,String source,Long alert,Object rule,String snapshot){KeyHolder k=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement p=c.prepareStatement("INSERT INTO e_suggestion(source_type,source_alert_id,source_fingerprint,source_snapshot_json,template_snapshot_json,trigger_basis,rule_code,title,measure_content,responsible_user,responsible_role,verify_start,verify_end,area_id,equipment_id,object_type,object_id,status,priority_score,priority_band,priority_formula_version,priority_factors_json,attachments_json,created_by,row_version,create_time,update_time) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'pending',70,'high','PRIORITY-V1','{}','[]',?,1,?,?)",Statement.RETURN_GENERATED_KEYS);int i=1;p.setString(i++,source);if(alert==null)p.setNull(i++,java.sql.Types.BIGINT);else p.setLong(i++,alert);p.setString(i++,alert==null?null:"ALERT-"+alert);p.setString(i++,source.equals("rule")?toJson(map("sourceAlertId",alert)):"{}");p.setString(i++,snapshot);p.setString(i++,String.valueOf(b.getOrDefault("triggerBasis","人工创建")));p.setString(i++,rule==null?null:String.valueOf(rule));p.setString(i++,String.valueOf(b.get("title")));p.setString(i++,String.valueOf(b.get("measureContent")));p.setString(i++,string(b.get("responsibleUser")));p.setString(i++,string(b.getOrDefault("responsibleRole","energy_mgr")));p.setString(i++,string(b.get("verifyStart")));p.setString(i++,string(b.get("verifyEnd")));setLong(p,i++,b.get("areaId"));setLong(p,i++,b.get("equipmentId"));p.setString(i++,String.valueOf(b.get("objectType")));setLong(p,i++,b.get("objectId"));p.setString(i++,user);p.setTimestamp(i++,Timestamp.valueOf(now));p.setTimestamp(i,Timestamp.valueOf(now));return p;},k);return k.getKey().longValue();}
    private long insertTemplate(Map<String,Object>b,int version){KeyHolder k=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement p=c.prepareStatement("INSERT INTO e_suggestion_template(template_code,template_name,category,source_rule_code,applicable_object_type,action_content,required_data,estimated_saving,cost_impact,reliability_impact,verification_method,default_implementation_difficulty,default_safety_impact,enabled,version,create_time,update_time) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);int i=1;p.setString(i++,String.valueOf(b.get("templateCode")));p.setString(i++,String.valueOf(b.get("templateName")));p.setString(i++,String.valueOf(b.get("category")));p.setString(i++,string(b.get("sourceRuleCode")));p.setString(i++,String.valueOf(b.get("applicableObjectType")));p.setString(i++,String.valueOf(b.get("actionContent")));p.setString(i++,string(b.get("requiredData")));p.setString(i++,string(b.get("estimatedSaving")));p.setString(i++,string(b.get("costImpact")));p.setString(i++,string(b.get("reliabilityImpact")));p.setString(i++,string(b.get("verificationMethod")));p.setBigDecimal(i++,decimal(b.getOrDefault("defaultImplementationDifficulty",50)));p.setBigDecimal(i++,decimal(b.getOrDefault("defaultSafetyImpact",50)));p.setInt(i++,Boolean.FALSE.equals(b.get("enabled"))?0:1);p.setInt(i++,version);p.setTimestamp(i++,Timestamp.valueOf(now));p.setTimestamp(i,Timestamp.valueOf(now));return p;},k);return k.getKey().longValue();}
    private Map<String,Object> load(long id){Map<String,Object>r=first("SELECT s.*,a.area_code,a.area_name,e.equipment_code,e.equipment_name FROM e_suggestion s LEFT JOIN e_area a ON a.area_id=s.area_id LEFT JOIN e_equipment e ON e.equipment_id=s.equipment_id WHERE s.suggestion_id=?",id);if(r.isEmpty())throw new BusinessException(404,"建议不存在");return r;}private Map<String,Object>loadForUpdate(long id){Map<String,Object>r=first("SELECT * FROM e_suggestion WHERE suggestion_id=? FOR UPDATE",id);if(r.isEmpty())throw new BusinessException(404,"建议不存在");return r;}
    private Map<String,Object> item(Map<String,Object>r){Map<String,Object>f=jsonObj(r.get("priority_factors_json"));return map("suggestionId",r.get("suggestion_id"),"title",r.get("title"),"measureContent",r.get("measure_content"),"sourceType",r.get("source_type"),"sourceFingerprint",r.get("source_fingerprint"),"sourceSummary",r.get("trigger_basis"),"ruleCode",r.get("rule_code"),"area",map("id",r.get("area_id"),"code",r.get("area_code"),"name",r.get("area_name")),"equipment",map("id",r.get("equipment_id"),"code",r.get("equipment_code"),"name",r.get("equipment_name")),"status",r.get("status"),"closeType",r.get("close_type"),"closeLabel",r.get("close_type"),"responsibleUser",r.get("responsible_user"),"responsibleRole",r.get("responsible_role"),"verifyStart",r.get("verify_start"),"verifyEnd",r.get("verify_end"),"priority",map("score",r.get("priority_score"),"band",r.get("priority_band"),"formulaVersion",r.get("priority_formula_version"),"factors",f,"weights",Map.of(),"basis",r.get("trigger_basis")),"createdAt",format(r.get("create_time")),"updatedAt",format(r.get("update_time")),"triggerBasis",r.get("trigger_basis"),"object",map("type",r.get("object_type"),"id",r.get("object_id")),"repairAt",format(r.get("repair_at")),"baselineStart",format(r.get("baseline_start")),"baselineEnd",format(r.get("baseline_end")),"reportStart",format(r.get("report_start")),"reportEnd",format(r.get("report_end")),"savingValue",r.get("saving_value"),"savingUnit",r.get("saving_unit"),"effectSummary",r.get("effect_summary"),"attachments",jsonList(r.get("attachments_json")),"deferReason",r.get("defer_reason"),"deferUntil",r.get("defer_until"),"deferredFromStatus",r.get("deferred_from_status"),"rowVersion",r.get("row_version"),"currentAlertEventId",r.get("source_alert_id"));}
    private Map<String,Object> template(Map<String,Object>r){return map("templateId",r.get("template_id"),"templateCode",r.get("template_code"),"templateName",r.get("template_name"),"category",r.get("category"),"sourceRuleCode",r.get("source_rule_code"),"applicableObjectType",r.get("applicable_object_type"),"actionContent",r.get("action_content"),"requiredData",r.get("required_data"),"estimatedSaving",r.get("estimated_saving"),"costImpact",r.get("cost_impact"),"reliabilityImpact",r.get("reliability_impact"),"verificationMethod",r.get("verification_method"),"defaultImplementationDifficulty",r.get("default_implementation_difficulty"),"defaultSafetyImpact",r.get("default_safety_impact"),"enabled",bool(r.get("enabled")),"version",r.get("version"),"createTime",format(r.get("create_time")),"updateTime",format(r.get("update_time")));}
    private Map<String,Object> flow(Map<String,Object>r){return map("flowId",r.get("flow_id"),"fromStatus",r.get("from_status"),"toStatus",r.get("to_status"),"operator",r.get("operator"),"operatorRole",r.get("operator_role"),"action",r.get("action"),"remark",r.get("remark"),"payloadSnapshot",jsonObj(r.get("payload_snapshot_json")),"occurTime",format(r.get("occur_time")));}private Map<String,Object>verification(Map<String,Object>r){Map<String,Object>m=new LinkedHashMap<>(r);m.put("verificationId",r.get("verification_id"));m.put("usageComparison",jsonObj(r.get("usage_comparison_json")));m.put("costComparison",jsonObj(r.get("cost_comparison_json")));m.put("workloadComparison",jsonObj(r.get("workload_comparison_json")));m.put("qualityComparison",jsonObj(r.get("quality_comparison_json")));return m;}
    private void flow(long id,String from,String to,String user,String action,String remark,String payload){jdbc.update("INSERT INTO e_suggestion_flow_log(suggestion_id,from_status,to_status,operator,operator_role,action,remark,payload_snapshot_json,occur_time) VALUES(?,?,?,?,?,?,?,?,?)",id,from,to,user,"energy_mgr",action,remark,payload,Timestamp.valueOf(now));}
    private Map<String,Object>templateFor(Object code,Object rule){List<Map<String,Object>>r=code!=null?jdbc.queryForList("SELECT * FROM e_suggestion_template WHERE template_code=? AND enabled=1 ORDER BY version DESC LIMIT 1",code):jdbc.queryForList("SELECT * FROM e_suggestion_template WHERE source_rule_code=? AND enabled=1 ORDER BY version DESC LIMIT 1",rule);if(r.isEmpty())throw new BusinessException(409,"没有适用的建议模板");return r.get(0);}private List<String>actions(String s){return new ArrayList<>(LEGAL.getOrDefault(s,Set.of()));}private void checkVersion(Map<String,Object>r,Map<String,Object>b){if(b.get("rowVersion")==null||((Number)b.get("rowVersion")).intValue()!=((Number)r.get("row_version")).intValue())throw new BusinessException(409,"rowVersion 已过期");}
    private Map<String,Object>first(String q,Object...p){List<Map<String,Object>>r=jdbc.queryForList(q,p);return r.isEmpty()?Map.of():r.get(0);}private void add(StringBuilder s,List<Object>p,String q,Object v){if(v!=null&&!v.toString().isBlank()){s.append(q);p.add(v);}}private void req(Map<String,Object>b,String...k){for(String x:k)if(b.get(x)==null||b.get(x).toString().isBlank())throw new IllegalArgumentException(x+" 不能为空");}private void setLong(PreparedStatement p,int i,Object v)throws java.sql.SQLException{if(v==null)p.setNull(i,java.sql.Types.BIGINT);else p.setLong(i,Long.parseLong(v.toString()));}
    private String string(Object v){return v==null?null:v.toString();}private java.math.BigDecimal decimal(Object v){return new java.math.BigDecimal(v.toString());}private boolean bool(Object v){return v instanceof Boolean b?b:v instanceof Number n&&n.intValue()!=0;}private double num(Object v){return v instanceof Number n?n.doubleValue():0;}private LocalDateTime dateTime(Object v){return v instanceof LocalDateTime l?l:((Timestamp)v).toLocalDateTime();}private String format(Object v){return v==null?null:dateTime(v).format(DT);}private Map<String,Object>jsonObj(Object v){if(v==null)return Map.of();try{return json.readValue(v.toString(),new TypeReference<>(){});}catch(Exception e){return Map.of();}}private List<Map<String,Object>>jsonList(Object v){if(v==null)return List.of();try{return json.readValue(v.toString(),new TypeReference<>(){});}catch(Exception e){return List.of();}}private String toJson(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException("JSON 序列化失败");}}private Map<String,Object>map(Object...p){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<p.length;i+=2)m.put((String)p[i],p[i+1]);return m;}
}
