CREATE TABLE wallets (
 id VARCHAR(36) PRIMARY KEY, org_id VARCHAR(80) NOT NULL, label VARCHAR(120) NOT NULL,
 msp_id VARCHAR(80) NOT NULL, key_ref VARCHAR(100) NOT NULL UNIQUE,
 certificate_pem TEXT NOT NULL, fingerprint CHAR(64) NOT NULL UNIQUE,
 subject VARCHAR(500) NOT NULL, not_after TIMESTAMP WITH TIME ZONE NOT NULL,
 state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE wallet_bindings (
 org_id VARCHAR(80) NOT NULL, source_system VARCHAR(80) NOT NULL,
 wallet_id VARCHAR(36) NOT NULL REFERENCES wallets(id), revision INTEGER NOT NULL DEFAULT 1,
 PRIMARY KEY(org_id,source_system)
);
CREATE TABLE wallet_requests (
 id VARCHAR(36) PRIMARY KEY, org_id VARCHAR(80) NOT NULL, action VARCHAR(20) NOT NULL,
 payload TEXT NOT NULL, reason VARCHAR(500) NOT NULL, proposed_by VARCHAR(80) NOT NULL,
 reviewed_by VARCHAR(80), state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 reviewed_at TIMESTAMP WITH TIME ZONE
);
ALTER TABLE events ADD COLUMN signing_required BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE events ADD COLUMN wallet_id VARCHAR(36) REFERENCES wallets(id);
ALTER TABLE events ADD COLUMN signer_fingerprint CHAR(64);
ALTER TABLE events ADD COLUMN ledger_identity TEXT;
CREATE TABLE signing_attempts (
 tx_id VARCHAR(128) PRIMARY KEY, event_id VARCHAR(36) NOT NULL REFERENCES events(id),
 wallet_id VARCHAR(36) NOT NULL REFERENCES wallets(id), fingerprint CHAR(64) NOT NULL,
 state VARCHAR(20) NOT NULL DEFAULT 'PREPARED', created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX signing_event ON signing_attempts(event_id);
