package com.bdemo.energy.report;

import com.bdemo.common.BusinessException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
public class ReportService {
    private static final Map<String,List<String>> SECTIONS=Map.of("ENERGY_DAILY",List.of("usageSection","alertSection","qualitySection"),"ENERGY_MONTHLY",List.of("usageSection","costSection","alertSection","suggestionSection","qualitySection"),"EQUIPMENT_PROFILE",List.of("usageSection","qualitySection"),"SUGGESTION_RETROSPECTIVE",List.of("suggestionSection","qualitySection"),"COST_DIFF",List.of("costSection","qualitySection"));
    private final JdbcTemplate jdbc;private final ObjectMapper json;private final LocalDateTime now;
    public ReportService(JdbcTemplate jdbc,ObjectMapper json,@Value("${b-demo.demo-now}")LocalDateTime now){this.jdbc=jdbc;this.json=json;this.now=now;}
    public Map<String,Object>templates(){String previous=now.toLocalDate().minusMonths(1).toString().substring(0,7);return map("items",SECTIONS.entrySet().stream().map(e->map("templateCode",e.getKey(),"templateVersion","v1","defaultPeriod","ENERGY_DAILY".equals(e.getKey())?now.toLocalDate().toString():previous,"sections",e.getValue())).toList(),"subscription",map("enabled",false,"priority","P2","label","报表订阅（规划中）"));}
    public Map<String,Object>preview(Map<String,Object>b){Map<String,Object>payload=assemble(b);return map("reportMeta",map("templateCode",payload.get("templateCode"),"templateVersion","v1","period",payload.get("period"),"filters",payload.get("filters"),"generatedAt",payload.get("generatedAt"),"qualitySummary",payload.get("qualitySummary"),"versionSnapshots",payload.get("versionSnapshots")),"sections",payload.get("sections"),"signature",signature(payload));}
    public ReportFile export(Map<String,Object>b){Map<String,Object>payload=assemble(b);String sig=signature(payload);return excel(payload,sig);}
    @Transactional public Map<String,Object>archive(Map<String,Object>b,String user){Map<String,Object>payload=assemble(b);String sig=signature(payload);Map<String,Object>period=cast(payload.get("period"));KeyHolder k=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement p=c.prepareStatement("INSERT INTO e_report_archive(template_code,template_version,period_start,period_end,filters_snapshot_json,payload_snapshot_json,version_snapshots_json,full_signature,generated_at,archived_by,archived_at) VALUES(?,'v1',?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);int i=1;p.setString(i++,String.valueOf(payload.get("templateCode")));p.setString(i++,String.valueOf(period.get("start")));p.setString(i++,String.valueOf(period.get("end")));p.setString(i++,toJson(payload.get("filters")));p.setString(i++,toJson(payload));p.setString(i++,toJson(payload.get("versionSnapshots")));p.setString(i++,sig);p.setTimestamp(i++,Timestamp.valueOf(now));p.setString(i++,user);p.setTimestamp(i,Timestamp.valueOf(now));return p;},k);return archive(k.getKey().longValue());}
    public Map<String,Object>archives(){return map("items",jdbc.queryForList("SELECT * FROM e_report_archive ORDER BY archive_id DESC").stream().map(this::summary).toList());}
    public Map<String,Object>archive(long id){List<Map<String,Object>>r=jdbc.queryForList("SELECT * FROM e_report_archive WHERE archive_id=?",id);if(r.isEmpty())throw new BusinessException(404,"报表归档不存在");Map<String,Object>row=r.get(0);return map("archive",summary(row),"payload",jsonObj(row.get("payload_snapshot_json")),"versionSnapshots",jsonObj(row.get("version_snapshots_json")),"fullSignature",row.get("full_signature"));}
    public ReportFile exportArchive(long id){Map<String,Object>d=archive(id);return excel(cast(d.get("payload")),String.valueOf(d.get("fullSignature")));}
    private Map<String,Object>assemble(Map<String,Object>b){String code=String.valueOf(b.get("templateCode"));if(!SECTIONS.containsKey(code))throw new IllegalArgumentException("templateCode 无效");Map<String,Object>filters=b.get("filters")instanceof Map<?,?>?cast(b.get("filters")):new LinkedHashMap<>();String energy=String.valueOf(filters.getOrDefault("energyType","electricity")),zone=String.valueOf(filters.getOrDefault("zone","ALL"));String period=String.valueOf(b.getOrDefault("period",code.equals("ENERGY_DAILY")?now.toLocalDate():now.toLocalDate().minusMonths(1).toString().substring(0,7)));LocalDate start=period.length()==10?LocalDate.parse(period):LocalDate.parse(period+"-01");LocalDate end=period.length()==10?start:start.withDayOfMonth(start.lengthOfMonth());String month=start.toString().substring(0,7);Map<String,Object>usage=first("SELECT SUM(total_value) totalValue,AVG(coverage_ratio) coverage FROM e_stat_day WHERE stat_date>=? AND stat_date<=? AND object_type='system' AND energy_type_code=?",start,end,energy);Map<String,Object>cost=first("SELECT SUM(total_cost) totalCost,MAX(cost_version) costVersion,MAX(status) reviewState FROM e_cost_record WHERE stat_month=? AND object_type='system' AND energy_type_code=? AND is_current=1",month,energy);Map<String,Object>alert=first("SELECT COUNT(*) total,SUM(status IN ('closed','false_closed')) closed FROM e_alert_event WHERE first_occur_time>=? AND first_occur_time<?",start,end.plusDays(1));Map<String,Object>sug=first("SELECT COUNT(*) total,SUM(status IN ('valid_closed','invalid_closed','closed')) closed FROM e_suggestion WHERE create_time>=? AND create_time<?",start,end.plusDays(1));Map<String,Object>sections=new LinkedHashMap<>();for(String s:SECTIONS.get(code)){switch(s){case"usageSection"->sections.put(s,map("items",List.of(usage),"total",usage.get("totalValue")));case"costSection"->sections.put(s,map("items",List.of(cost),"totalCost",cost.get("totalCost"),"reviewState",cost.get("reviewState")));case"alertSection"->sections.put(s,map("items",List.of(alert),"total",alert.get("total")));case"suggestionSection"->sections.put(s,map("items",List.of(sug),"total",sug.get("total")));case"qualitySection"->sections.put(s,map("coverage",usage.getOrDefault("coverage",1),"band","ok"));}}Map<String,Object>versions=map("formulaVersion","f-1.3","costVersion","v"+cost.getOrDefault("costVersion",1),"templateVersion","v1");return map("templateCode",code,"templateVersion","v1","period",map("start",start.toString(),"end",end.toString(),"label",period),"filters",map("zone",zone,"energyType",energy,"equipmentId",filters.get("equipmentId")),"generatedAt",now.toString(),"qualitySummary",map("coverage",usage.getOrDefault("coverage",1),"band","ok"),"versionSnapshots",versions,"sections",sections);}
    private ReportFile excel(Map<String,Object>payload,String sig){try(Workbook wb=new XSSFWorkbook();ByteArrayOutputStream out=new ByteArrayOutputStream()){Sheet sheet=wb.createSheet("能源报表");CellStyle head=wb.createCellStyle();Font font=wb.createFont();font.setBold(true);head.setFont(font);int row=0;Row title=sheet.createRow(row++);title.createCell(0).setCellValue(String.valueOf(payload.get("templateCode")));title.getCell(0).setCellStyle(head);for(Map.Entry<String,Object>e:cast(payload.get("sections")).entrySet()){Row h=sheet.createRow(row++);h.createCell(0).setCellValue(e.getKey());h.getCell(0).setCellStyle(head);Row v=sheet.createRow(row++);v.createCell(0).setCellValue(toJson(e.getValue()));}sheet.createRow(row).createCell(0).setCellValue("Signature: "+sig);sheet.setColumnWidth(0,12000);wb.write(out);return new ReportFile(String.valueOf(payload.get("templateCode"))+".xlsx",out.toByteArray(),sig);}catch(Exception e){throw new IllegalArgumentException("Excel 生成失败");}}
    private Map<String,Object>summary(Map<String,Object>r){return map("archiveId",r.get("archive_id"),"templateCode",r.get("template_code"),"templateVersion",r.get("template_version"),"periodStart",r.get("period_start"),"periodEnd",r.get("period_end"),"fullSignature",r.get("full_signature"),"generatedAt",r.get("generated_at"),"archivedBy",r.get("archived_by"),"archivedAt",r.get("archived_at"));}private String signature(Map<String,Object>p){return"REPORT-SHA256:"+Integer.toHexString(toJson(p).hashCode());}private Map<String,Object>first(String q,Object...p){List<Map<String,Object>>r=jdbc.queryForList(q,p);return r.isEmpty()?Map.of():r.get(0);}@SuppressWarnings("unchecked")private Map<String,Object>cast(Object v){return(Map<String,Object>)v;}private Map<String,Object>jsonObj(Object v){try{return json.readValue(String.valueOf(v),new TypeReference<>(){});}catch(Exception e){return Map.of();}}private String toJson(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException("JSON 序列化失败");}}private Map<String,Object>map(Object...p){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<p.length;i+=2)m.put((String)p[i],p[i+1]);return m;}public record ReportFile(String filename,byte[]content,String signature){}
}
