package com.mt.wms.stockin;

import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Repository
class StockinRepository {
    private final JdbcClient jdbc;
    StockinRepository(JdbcClient jdbc){this.jdbc=jdbc;}

    List<StockinModels.OrderSummary> orders(long c,long w,long o){return jdbc.sql("""
        SELECT x.id,x.order_code,x.external_order_code,x.inbound_type,x.source,x.state,p.code AS partner_code,p.name AS partner_name,x.planned_date,
               COALESCE(sum(l.planned_qty),0) AS planned_qty,COALESCE(sum(l.received_qty),0) AS received_qty,x.total_amount,x.created_at,x.finished_at
          FROM stockin_order x LEFT JOIN wms_partner p ON p.id=x.partner_id LEFT JOIN stockin_order_line l ON l.order_id=x.id
         WHERE x.company_id=:c AND x.warehouse_id=:w AND x.owner_id=:o
         GROUP BY x.id,x.order_code,x.external_order_code,x.inbound_type,x.source,x.state,p.code,p.name,x.planned_date,x.total_amount,x.created_at,x.finished_at
         ORDER BY x.id DESC LIMIT 200
        """).param("c",c).param("w",w).param("o",o).query(StockinModels.OrderSummary.class).list();}

    OrderHeader order(long id,long c,long w,long o){return jdbc.sql("SELECT id,order_code,external_order_code,related_order_code,inbound_type,source,state,partner_id,planned_date,total_amount,remark,created_at,finished_at FROM stockin_order WHERE id=:id AND company_id=:c AND warehouse_id=:w AND owner_id=:o").param("id",id).param("c",c).param("w",w).param("o",o).query(OrderHeader.class).optional().orElseThrow(()->new IllegalArgumentException("入库单不存在"));}
    OrderLock lockOrder(long id,long c,long w,long o){return jdbc.sql("SELECT id,order_code,state FROM stockin_order WHERE id=:id AND company_id=:c AND warehouse_id=:w AND owner_id=:o FOR UPDATE").param("id",id).param("c",c).param("w",w).param("o",o).query(OrderLock.class).optional().orElseThrow(()->new IllegalArgumentException("入库单不存在"));}
    List<StockinModels.LineView> lines(long orderId){return jdbc.sql("SELECT l.id,l.line_no,g.code AS good_code,g.name AS good_name,g.barcode,l.planned_qty,l.received_qty,(l.planned_qty-l.received_qty) AS remaining_qty,loc.code AS preferred_location_code,l.supplier_code,l.quality_type,l.product_date,l.expire_date,l.batch_code,l.unit_price,l.remark FROM stockin_order_line l JOIN wms_good g ON g.id=l.good_id LEFT JOIN wms_location loc ON loc.id=l.preferred_location_id WHERE l.order_id=:id ORDER BY l.line_no").param("id",orderId).query(StockinModels.LineView.class).list();}
    List<StockinModels.ReceiptView> receipts(long orderId,long c,long w,long o){return jdbc.sql("SELECT r.id,r.operation_code,l.line_no,g.code AS good_code,g.name AS good_name,loc.code AS location_code,r.quantity,r.batch_code,r.quality_type,r.lpn,r.serial_count,u.display_name AS operator_name,r.remark,r.created_at FROM stockin_receipt r JOIN stockin_order_line l ON l.id=r.order_line_id JOIN wms_good g ON g.id=r.good_id JOIN wms_location loc ON loc.id=r.location_id JOIN auth_user u ON u.id=r.operator_user_id WHERE r.order_id=:id AND r.company_id=:c AND r.warehouse_id=:w AND r.owner_id=:o ORDER BY r.id DESC").param("id",orderId).param("c",c).param("w",w).param("o",o).query(StockinModels.ReceiptView.class).list();}
    long lineIdByBarcode(long orderId,String barcode){return jdbc.sql("SELECT l.id FROM stockin_order_line l JOIN wms_good g ON g.id=l.good_id WHERE l.order_id=:order AND (g.barcode=:barcode OR g.code=:barcode) AND l.received_qty<l.planned_qty ORDER BY l.line_no LIMIT 1").param("order",orderId).param("barcode",barcode).query(Long.class).optional().orElseThrow(()->new IllegalArgumentException("入库单中没有该条码对应的待收明细"));}
    List<StockinModels.LocationSuggestion> locationSuggestions(long c,long w,long o,long good){return jdbc.sql("""
        SELECT l.code AS location_code,l.code AS location_name,
               CASE WHEN l.id=g.default_location_id THEN '货品默认库位'
                    WHEN EXISTS (SELECT 1 FROM inv_balance b WHERE b.warehouse_id=:w AND b.owner_id=:o AND b.good_id=:good AND b.location_id=l.id AND b.available_qty>0) THEN '相同货品已有库存'
                    WHEN l.code='STAGE' THEN '收货暂存位' ELSE '可用库位' END AS reason
          FROM wms_location l JOIN wms_good g ON g.id=:good
         WHERE l.company_id=:c AND l.warehouse_id=:w AND l.status='ENABLED'
         ORDER BY CASE WHEN l.id=g.default_location_id THEN 0
                       WHEN EXISTS (SELECT 1 FROM inv_balance b WHERE b.warehouse_id=:w AND b.owner_id=:o AND b.good_id=:good AND b.location_id=l.id AND b.available_qty>0) THEN 1
                       WHEN l.code='STAGE' THEN 2 ELSE 3 END,l.code LIMIT 20
        """).param("c",c).param("w",w).param("o",o).param("good",good).query(StockinModels.LocationSuggestion.class).list();}

    boolean createProcessed(long c,String key){return jdbc.sql("SELECT count(*) FROM stockin_order WHERE company_id=:c AND idempotency_key=:key").param("c",c).param("key",key).query(Integer.class).single()>0;}
    boolean operationProcessed(long c,String key){return jdbc.sql("SELECT count(*) FROM inv_operation WHERE company_id=:c AND idempotency_key=:key").param("c",c).param("key",key).query(Integer.class).single()>0;}
    boolean externalExists(long c,long w,long o,String external){return jdbc.sql("SELECT count(*) FROM stockin_order WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND external_order_code=:e AND state<>'CANCELLED'").param("c",c).param("w",w).param("o",o).param("e",external).query(Integer.class).single()>0;}
    Long partnerId(long c,String code){return jdbc.sql("SELECT id FROM wms_partner WHERE company_id=:c AND code=:code AND status='ENABLED'").param("c",c).param("code",code).query(Long.class).optional().orElseThrow(()->new IllegalArgumentException("合作伙伴不存在或已停用"));}
    PartnerRow partner(Long id){if(id==null)return new PartnerRow(null,null);return jdbc.sql("SELECT code,name FROM wms_partner WHERE id=:id").param("id",id).query(PartnerRow.class).optional().orElse(new PartnerRow(null,null));}
    GoodRow good(long c,long o,String code){return jdbc.sql("SELECT id,code,name,barcode,price FROM wms_good WHERE company_id=:c AND owner_id=:o AND (code=:code OR barcode=:code) AND status='ENABLED'").param("c",c).param("o",o).param("code",code).query(GoodRow.class).optional().orElseThrow(()->new IllegalArgumentException("货品不存在或已停用"));}
    long locationId(long c,long w,String code){return jdbc.sql("SELECT id FROM wms_location WHERE company_id=:c AND warehouse_id=:w AND code=:code AND status='ENABLED'").param("c",c).param("w",w).param("code",code).query(Long.class).optional().orElseThrow(()->new IllegalArgumentException("库位不存在或已停用"));}

    long createOrder(long c,long w,long o,String code,String external,String related,String type,String source,Long partner,LocalDate planned,BigDecimal amount,long user,String remark,String key){return jdbc.sql("INSERT INTO stockin_order(company_id,warehouse_id,owner_id,order_code,external_order_code,related_order_code,inbound_type,source,partner_id,planned_date,total_amount,created_by,remark,idempotency_key) VALUES(:c,:w,:o,:code,:external,:related,:type,:source,:partner,:planned,:amount,:user,:remark,:key) RETURNING id").param("c",c).param("w",w).param("o",o).param("code",code).param("external",external).param("related",related).param("type",type).param("source",source).param("partner",partner).param("planned",planned).param("amount",amount).param("user",user).param("remark",remark).param("key",key).query(Long.class).single();}
    long createLine(long order,int no,long good,BigDecimal planned,Long location,String supplier,String quality,LocalDate product,LocalDate expire,String batch,BigDecimal price,String remark){return jdbc.sql("INSERT INTO stockin_order_line(order_id,line_no,good_id,planned_qty,preferred_location_id,supplier_code,quality_type,product_date,expire_date,batch_code,unit_price,remark) VALUES(:order,:no,:good,:planned,:location,:supplier,:quality,:product,:expire,:batch,:price,:remark) RETURNING id").param("order",order).param("no",no).param("good",good).param("planned",planned).param("location",location).param("supplier",supplier).param("quality",quality).param("product",product).param("expire",expire).param("batch",batch).param("price",price).param("remark",remark).query(Long.class).single();}
    LineLock lockLine(long lineId,long orderId){return jdbc.sql("SELECT id,order_id,line_no,good_id,planned_qty,received_qty,preferred_location_id,supplier_code,quality_type,product_date,expire_date,batch_code,unit_price FROM stockin_order_line WHERE id=:id AND order_id=:order FOR UPDATE").param("id",lineId).param("order",orderId).query(LineLock.class).optional().orElseThrow(()->new IllegalArgumentException("入库单明细不存在"));}
    void addReceived(long lineId,BigDecimal quantity){int n=jdbc.sql("UPDATE stockin_order_line SET received_qty=received_qty+:q,updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("q",quantity).param("id",lineId).update();if(n!=1)throw new IllegalArgumentException("入库明细更新失败");}
    boolean allReceived(long orderId){return jdbc.sql("SELECT count(*) FROM stockin_order_line WHERE order_id=:id AND received_qty<planned_qty").param("id",orderId).query(Integer.class).single()==0;}
    void state(long orderId,String state,boolean finish){jdbc.sql("UPDATE stockin_order SET state=:state,received_at=COALESCE(received_at,CURRENT_TIMESTAMP),finished_at=CASE WHEN :finish THEN CURRENT_TIMESTAMP ELSE finished_at END,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("state",state).param("finish",finish).param("id",orderId).update();}
    void cancel(long orderId,String remark){jdbc.sql("UPDATE stockin_order SET state='CANCELLED',remark=CASE WHEN :remark IS NULL THEN remark ELSE :remark END,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("remark",remark).param("id",orderId).update();}

    long operation(long c,long w,long o,String code,long user,String remark,String key){return jdbc.sql("INSERT INTO inv_operation(company_id,warehouse_id,owner_id,operation_code,operation_type,state,operator_user_id,remark,idempotency_key,completed_at) VALUES(:c,:w,:o,:code,'STOCK_IN','EXECUTED',:u,:remark,:key,CURRENT_TIMESTAMP) RETURNING id").param("c",c).param("w",w).param("o",o).param("code",code).param("u",user).param("remark",remark).param("key",key).query(Long.class).single();}
    Optional<BalanceRow> lockBalance(long c,long w,long o,long location,long good,String batch,String quality,String supplier,String lpn){return jdbc.sql("SELECT id,available_qty,allocated_qty,frozen_qty FROM inv_balance WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND location_id=:location AND good_id=:good AND batch_code=:batch AND quality_type=:quality AND supplier_code=:supplier AND lpn=:lpn FOR UPDATE").param("c",c).param("w",w).param("o",o).param("location",location).param("good",good).param("batch",batch).param("quality",quality).param("supplier",supplier).param("lpn",lpn).query(BalanceRow.class).optional();}
    long createBalance(long c,long w,long o,long location,long good,String batch,String quality,String supplier,LocalDate product,LocalDate expire,String lpn){return jdbc.sql("INSERT INTO inv_balance(company_id,warehouse_id,owner_id,location_id,good_id,batch_code,quality_type,supplier_code,product_date,expire_date,lpn) VALUES(:c,:w,:o,:location,:good,:batch,:quality,:supplier,:product,:expire,:lpn) RETURNING id").param("c",c).param("w",w).param("o",o).param("location",location).param("good",good).param("batch",batch).param("quality",quality).param("supplier",supplier).param("product",product).param("expire",expire).param("lpn",lpn).query(Long.class).single();}
    void addInventory(long balance,BigDecimal quantity){jdbc.sql("UPDATE inv_balance SET available_qty=available_qty+:q,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("q",quantity).param("id",balance).update();}
    void operationLine(long op,long good,long location,long balance,BigDecimal before,BigDecimal qty,String batch,String quality,String remark){jdbc.sql("INSERT INTO inv_operation_line(operation_id,good_id,destination_location_id,balance_id,system_qty,requested_qty,actual_qty,difference_qty,batch_code,quality_type,remark) VALUES(:op,:good,:location,:balance,:before,:qty,:qty,0,:batch,:quality,:remark)").param("op",op).param("good",good).param("location",location).param("balance",balance).param("before",before).param("qty",qty).param("batch",batch).param("quality",quality).param("remark",remark).update();}
    void transaction(long c,long w,long o,long balance,long good,long location,String operation,BigDecimal before,BigDecimal qty,BigDecimal availableBefore,BigDecimal frozenBefore,String key,long user,String remark){jdbc.sql("INSERT INTO inv_transaction(company_id,warehouse_id,owner_id,balance_id,good_id,location_id,transaction_type,operation_code,quantity_before,quantity_change,quantity_after,available_before,available_change,available_after,frozen_before,frozen_change,frozen_after,idempotency_key,operator_user_id,remark) VALUES(:c,:w,:o,:balance,:good,:location,'STOCK_IN',:operation,:before,:qty,:after,:availableBefore,:qty,:availableAfter,:frozen,0,:frozen,:key,:user,:remark)").param("c",c).param("w",w).param("o",o).param("balance",balance).param("good",good).param("location",location).param("operation",operation).param("before",before).param("qty",qty).param("after",before.add(qty)).param("availableBefore",availableBefore).param("availableAfter",availableBefore.add(qty)).param("frozen",frozenBefore).param("key",key).param("user",user).param("remark",remark).update();}
    long receipt(long c,long w,long o,long order,long line,String operation,long balance,long good,long location,BigDecimal qty,String batch,String quality,String supplier,String lpn,int serialCount,long user,String key,String remark){return jdbc.sql("INSERT INTO stockin_receipt(company_id,warehouse_id,owner_id,order_id,order_line_id,operation_code,balance_id,good_id,location_id,quantity,batch_code,quality_type,supplier_code,lpn,serial_count,operator_user_id,idempotency_key,remark) VALUES(:c,:w,:o,:order,:line,:operation,:balance,:good,:location,:qty,:batch,:quality,:supplier,:lpn,:serialCount,:user,:key,:remark) RETURNING id").param("c",c).param("w",w).param("o",o).param("order",order).param("line",line).param("operation",operation).param("balance",balance).param("good",good).param("location",location).param("qty",qty).param("batch",batch).param("quality",quality).param("supplier",supplier).param("lpn",lpn).param("serialCount",serialCount).param("user",user).param("key",key).param("remark",remark).query(Long.class).single();}
    void serial(long c,long w,long o,long balance,long good,long location,String code,long user){jdbc.sql("INSERT INTO inv_serial(company_id,warehouse_id,owner_id,balance_id,good_id,location_id,serial_code,quantity,weight_kg,source,state,printed) VALUES(:c,:w,:o,:balance,:good,:location,:code,1,0,'STOCKIN','ACTIVE',FALSE)").param("c",c).param("w",w).param("o",o).param("balance",balance).param("good",good).param("location",location).param("code",code).update();}

    record OrderHeader(Long id,String orderCode,String externalOrderCode,String relatedOrderCode,String inboundType,String source,String state,Long partnerId,LocalDate plannedDate,BigDecimal totalAmount,String remark,java.time.OffsetDateTime createdAt,java.time.OffsetDateTime finishedAt){}
    record OrderLock(Long id,String orderCode,String state){}
    record GoodRow(Long id,String code,String name,String barcode,BigDecimal price){}
    record PartnerRow(String code,String name){}
    record LineLock(Long id,Long orderId,int lineNo,Long goodId,BigDecimal plannedQty,BigDecimal receivedQty,Long preferredLocationId,String supplierCode,String qualityType,LocalDate productDate,LocalDate expireDate,String batchCode,BigDecimal unitPrice){}
    record BalanceRow(Long id,BigDecimal availableQty,BigDecimal allocatedQty,BigDecimal frozenQty){BigDecimal total(){return availableQty.add(allocatedQty).add(frozenQty);}}
}
