"""Pure domain calculations shared by backend and deterministic datagen."""

from .cost_calculation import (
    AmbiguousTariffError,
    CostCalculationInput,
    CostCalculationResult,
    CostDiffItem,
    MissingTariffError,
    TariffSnapshot,
    build_cost_diff,
    build_cost_signature,
    calculate_cost,
)
from .report_canonical import (
    CanonicalReportPayload,
    build_report_signature,
    canonical_report_bytes,
)
from .suggestion_calculation import (
    HISTORY_VERIFICATION_VERSION,
    R06_PRIORITY_VERSION,
    R06_VERIFICATION_VERSION,
    VALID_QUALITY_CODES,
    PriorityResult,
    R06PriorityInput,
    ReadingSample,
    TariffRate,
    VerificationInput,
    VerificationResult,
    VerificationWindow,
    WindowMetrics,
    WorkloadSample,
    build_calculation_signature,
    calculate_history_verification,
    calculate_r06_priority,
    calculate_r06_verification,
    to_right_open_sample_boundary,
)

__all__ = [
    "HISTORY_VERIFICATION_VERSION",
    "R06_PRIORITY_VERSION",
    "R06_VERIFICATION_VERSION",
    "VALID_QUALITY_CODES",
    "AmbiguousTariffError",
    "CanonicalReportPayload",
    "CostCalculationInput",
    "CostCalculationResult",
    "CostDiffItem",
    "MissingTariffError",
    "PriorityResult",
    "R06PriorityInput",
    "ReadingSample",
    "TariffRate",
    "TariffSnapshot",
    "VerificationInput",
    "VerificationResult",
    "VerificationWindow",
    "WindowMetrics",
    "WorkloadSample",
    "build_calculation_signature",
    "build_cost_diff",
    "build_cost_signature",
    "build_report_signature",
    "calculate_cost",
    "calculate_history_verification",
    "calculate_r06_priority",
    "calculate_r06_verification",
    "canonical_report_bytes",
    "to_right_open_sample_boundary",
]
