package com.mt.wms.integration;

import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
class IntegrationRepository {
    private final JdbcClient jdbc;
    IntegrationRepository(JdbcClient jdbc){this.jdbc=jdbc;}
    List<IntegrationModels.TaskView> tasks(long c,long w,long o){return jdbc.sql("SELECT id,task_code,name,task_type,resource_type,state,original_file_name,processed_rows,success_rows,failure_rows,error_message,completed_at,created_at FROM async_task WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o ORDER BY id DESC LIMIT 200").param("c",c).param("w",w).param("o",o).query(IntegrationModels.TaskView.class).list();}
    long task(long c,long w,long o,String code,String name,String type,String resource,String original,String stored,long user){return jdbc.sql("INSERT INTO async_task(company_id,warehouse_id,owner_id,task_code,name,task_type,resource_type,original_file_name,stored_file_name,created_by) VALUES(:c,:w,:o,:code,:name,:type,:resource,:original,:stored,:user) RETURNING id").param("c",c).param("w",w).param("o",o).param("code",code).param("name",name).param("type",type).param("resource",resource).param("original",original).param("stored",stored).param("user",user).query(Long.class).single();}
    IntegrationModels.TaskRow task(long id){return jdbc.sql("SELECT id,company_id,warehouse_id,owner_id,created_by,task_code,task_type,resource_type,state,original_file_name,stored_file_name FROM async_task WHERE id=:id").param("id",id).query(IntegrationModels.TaskRow.class).single();}
    IntegrationModels.TaskRow task(long id,long c,long w,long o){return jdbc.sql("SELECT id,company_id,warehouse_id,owner_id,created_by,task_code,task_type,resource_type,state,original_file_name,stored_file_name FROM async_task WHERE id=:id AND company_id=:c AND warehouse_id=:w AND owner_id=:o").param("id",id).param("c",c).param("w",w).param("o",o).query(IntegrationModels.TaskRow.class).optional().orElseThrow(()->new IllegalArgumentException("任务不存在"));}
    void complete(long id,int processed,int success,int failure){jdbc.sql("UPDATE async_task SET state='COMPLETED',processed_rows=:processed,success_rows=:success,failure_rows=:failure,completed_at=CURRENT_TIMESTAMP WHERE id=:id").param("id",id).param("processed",processed).param("success",success).param("failure",failure).update();}
    void fail(long id,String error){jdbc.sql("UPDATE async_task SET state='FAILED',error_message=:error,completed_at=CURRENT_TIMESTAMP WHERE id=:id").param("id",id).param("error",error==null?"未知错误":error.substring(0,Math.min(1900,error.length()))).update();}
    List<java.util.Map<String,Object>> exportRows(String resource,long c,long w,long o){String sql=switch(resource){
        case "GOODS" -> "SELECT g.code AS 货品码,g.name AS 名称,g.barcode AS 条码,ca.code AS 货类码,g.specification AS 规格,g.unit AS 单位,g.price AS 售价,g.cost_price AS 成本价,g.status AS 状态 FROM wms_good g JOIN wms_category ca ON ca.id=g.category_id WHERE g.company_id=:c AND g.owner_id=:o ORDER BY g.code";
        case "PARTNERS" -> "SELECT code AS 合作伙伴码,name AS 名称,partner_type AS 类型,contact AS 联系人,telephone AS 电话,email AS 邮箱,address AS 地址,status AS 状态 FROM wms_partner WHERE company_id=:c ORDER BY code";
        case "INVENTORY" -> "SELECT g.code AS 货品码,g.name AS 名称,l.code AS 库位,b.batch_code AS 批次,b.quality_type AS 质量,b.available_qty AS 可用量,b.allocated_qty AS 分配量,b.frozen_qty AS 冻结量,(b.available_qty+b.allocated_qty+b.frozen_qty) AS 总量 FROM inv_balance b JOIN wms_good g ON g.id=b.good_id JOIN wms_location l ON l.id=b.location_id WHERE b.company_id=:c AND b.warehouse_id=:w AND b.owner_id=:o ORDER BY g.code,l.code";
        case "STOCKIN" -> "SELECT s.order_code AS 入库单号,s.external_order_code AS 外部单号,s.inbound_type AS 类型,s.state AS 状态,g.code AS 货品码,g.name AS 货品名称,l.planned_qty AS 计划数量,l.received_qty AS 实收数量,l.unit_price AS 单价,s.created_at AS 创建时间 FROM stockin_order s JOIN stockin_order_line l ON l.order_id=s.id JOIN wms_good g ON g.id=l.good_id WHERE s.company_id=:c AND s.warehouse_id=:w AND s.owner_id=:o ORDER BY s.id DESC,l.line_no";
        case "STOCKOUT" -> "SELECT s.order_code AS 出库单号,s.external_order_code AS 外部单号,s.outbound_type AS 类型,s.state AS 状态,g.code AS 货品码,g.name AS 货品名称,l.planned_qty AS 计划数量,l.shipped_qty AS 发运数量,l.unit_price AS 单价,s.created_at AS 创建时间 FROM stockout_order s JOIN stockout_order_line l ON l.order_id=s.id JOIN wms_good g ON g.id=l.good_id WHERE s.company_id=:c AND s.warehouse_id=:w AND s.owner_id=:o ORDER BY s.id DESC,l.line_no";
        case "FINANCE" -> "SELECT money_code AS 费用单号,related_order_code AS 关联单号,direction AS 收支方向,fee_type AS 费用类型,partner_name AS 合作伙伴,amount AS 总额,paid_amount AS 实额,bad_debt_amount AS 坏账,state AS 状态,accounting_date AS 记账日 FROM finance_money WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o ORDER BY id DESC";
        default -> throw new IllegalArgumentException("不支持的导出资源："+resource);
    };return jdbc.sql(sql).param("c",c).param("w",w).param("o",o).query().listOfRows();}

    Long category(long o,String code){return jdbc.sql("SELECT id FROM wms_category WHERE owner_id=:o AND code=:code").param("o",o).param("code",code).query(Long.class).optional().orElse(null);}
    long ensureCategory(long c,long o,String code,String name){Long id=category(o,code);if(id!=null)return id;return jdbc.sql("INSERT INTO wms_category(company_id,owner_id,code,name) VALUES(:c,:o,:code,:name) RETURNING id").param("c",c).param("o",o).param("code",code).param("name",name).query(Long.class).single();}
    void upsertGood(long c,long o,long category,String code,String name,String barcode,String spec,String unit,java.math.BigDecimal price){int n=jdbc.sql("UPDATE wms_good SET category_id=:category,name=:name,barcode=:barcode,specification=:spec,unit=:unit,price=:price,status='ENABLED',updated_at=CURRENT_TIMESTAMP WHERE owner_id=:o AND code=:code").param("category",category).param("name",name).param("barcode",barcode).param("spec",spec).param("unit",unit).param("price",price).param("o",o).param("code",code).update();if(n==0)jdbc.sql("INSERT INTO wms_good(company_id,owner_id,category_id,code,name,barcode,specification,unit,price) VALUES(:c,:o,:category,:code,:name,:barcode,:spec,:unit,:price)").param("c",c).param("o",o).param("category",category).param("code",code).param("name",name).param("barcode",barcode).param("spec",spec).param("unit",unit).param("price",price).update();}
    void upsertPartner(long c,String code,String name,String type,String contact,String phone,String email,String address){int n=jdbc.sql("UPDATE wms_partner SET name=:name,partner_type=:type,contact=:contact,telephone=:phone,email=:email,address=:address,status='ENABLED',updated_at=CURRENT_TIMESTAMP WHERE company_id=:c AND code=:code").param("c",c).param("code",code).param("name",name).param("type",type).param("contact",contact).param("phone",phone).param("email",email).param("address",address).update();if(n==0)jdbc.sql("INSERT INTO wms_partner(company_id,code,name,partner_type,contact,telephone,email,address) VALUES(:c,:code,:name,:type,:contact,:phone,:email,:address)").param("c",c).param("code",code).param("name",name).param("type",type).param("contact",contact).param("phone",phone).param("email",email).param("address",address).update();}
    long good(long o,String code){return jdbc.sql("SELECT id FROM wms_good WHERE owner_id=:o AND code=:code AND status='ENABLED'").param("o",o).param("code",code).query(Long.class).optional().orElseThrow(()->new IllegalArgumentException("货品不存在："+code));}
    Long partnerId(long c,String code){return code==null||code.isBlank()?null:jdbc.sql("SELECT id FROM wms_partner WHERE company_id=:c AND code=:code").param("c",c).param("code",code).query(Long.class).optional().orElse(null);}
    Long stage(long w){return jdbc.sql("SELECT id FROM wms_location WHERE warehouse_id=:w AND code='STAGE'").param("w",w).query(Long.class).optional().orElse(null);}
    String nextCode(String prefix,long c,long w,long o){String period=java.time.LocalDate.now().format(java.time.format.DateTimeFormatter.ofPattern("yyMM"));Seq seq=jdbc.sql("SELECT id,current_value FROM wms_business_sequence WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND prefix=:p AND period=:period FOR UPDATE").param("c",c).param("w",w).param("o",o).param("p",prefix).param("period",period).query(Seq.class).optional().orElse(null);long v;if(seq==null){v=1;jdbc.sql("INSERT INTO wms_business_sequence(company_id,warehouse_id,owner_id,prefix,period,current_value) VALUES(:c,:w,:o,:p,:period,1)").param("c",c).param("w",w).param("o",o).param("p",prefix).param("period",period).update();}else{v=seq.currentValue()+1;jdbc.sql("UPDATE wms_business_sequence SET current_value=:v,updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("v",v).param("id",seq.id()).update();}return prefix+period+"-"+String.format("%03d",v);}
    long importStockin(long c,long w,long o,String code,String external,String type,Long partner,long user,String key){return jdbc.sql("INSERT INTO stockin_order(company_id,warehouse_id,owner_id,order_code,external_order_code,inbound_type,source,state,partner_id,total_amount,created_by,idempotency_key,remark) VALUES(:c,:w,:o,:code,:external,:type,'IMPORT','DRAFT',:partner,0,:user,:key,'Excel导入') RETURNING id").param("c",c).param("w",w).param("o",o).param("code",code).param("external",external).param("type",type).param("partner",partner).param("user",user).param("key",key).query(Long.class).single();}
    void importStockinLine(long order,int no,long good,java.math.BigDecimal qty,Long stage,java.math.BigDecimal price,String batch,String supplier){jdbc.sql("INSERT INTO stockin_order_line(order_id,line_no,good_id,planned_qty,preferred_location_id,unit_price,batch_code,supplier_code) VALUES(:order,:no,:good,:qty,:stage,:price,:batch,:supplier)").param("order",order).param("no",no).param("good",good).param("qty",qty).param("stage",stage).param("price",price).param("batch",batch).param("supplier",supplier).update();}
    long importStockout(long c,long w,long o,String code,String external,String type,Long partner,long user,String key){return jdbc.sql("INSERT INTO stockout_order(company_id,warehouse_id,owner_id,order_code,external_order_code,outbound_type,source,state,partner_id,total_amount,created_by,idempotency_key,remark) VALUES(:c,:w,:o,:code,:external,:type,'IMPORT','DRAFT',:partner,0,:user,:key,'Excel导入') RETURNING id").param("c",c).param("w",w).param("o",o).param("code",code).param("external",external).param("type",type).param("partner",partner).param("user",user).param("key",key).query(Long.class).single();}
    void importStockoutLine(long order,int no,long good,java.math.BigDecimal qty,java.math.BigDecimal price,String batch,String supplier){jdbc.sql("INSERT INTO stockout_order_line(order_id,line_no,good_id,planned_qty,unit_price,batch_code,supplier_code) VALUES(:order,:no,:good,:qty,:price,:batch,:supplier)").param("order",order).param("no",no).param("good",good).param("qty",qty).param("price",price).param("batch",batch).param("supplier",supplier).update();}
    QimenConfig configByOwner(long c,long o){return jdbc.sql("SELECT id,company_id,owner_id,customer_id,app_key,app_secret,callback_url,payload_format,enabled,updated_at FROM integration_qimen_config WHERE company_id=:c AND owner_id=:o").param("c",c).param("o",o).query(QimenConfig.class).optional().orElse(null);}
    QimenConfig configByCustomer(String customer){return jdbc.sql("SELECT id,company_id,owner_id,customer_id,app_key,app_secret,callback_url,payload_format,enabled,updated_at FROM integration_qimen_config WHERE customer_id=:customer AND enabled=TRUE").param("customer",customer).query(QimenConfig.class).optional().orElse(null);}
    long saveConfig(Long id,long c,long o,String customer,String appKey,String secret,String url,String format,boolean enabled,long user){if(id==null)return jdbc.sql("INSERT INTO integration_qimen_config(company_id,owner_id,customer_id,app_key,app_secret,callback_url,payload_format,enabled,created_by,updated_by) VALUES(:c,:o,:customer,:appKey,:secret,:url,:format,:enabled,:user,:user) RETURNING id").param("c",c).param("o",o).param("customer",customer).param("appKey",appKey).param("secret",secret).param("url",url).param("format",format).param("enabled",enabled).param("user",user).query(Long.class).single();jdbc.sql("UPDATE integration_qimen_config SET customer_id=:customer,app_key=:appKey,app_secret=:secret,callback_url=:url,payload_format=:format,enabled=:enabled,updated_by=:user,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND company_id=:c AND owner_id=:o").param("id",id).param("c",c).param("o",o).param("customer",customer).param("appKey",appKey).param("secret",secret).param("url",url).param("format",format).param("enabled",enabled).param("user",user).update();return id;}
    List<IntegrationModels.QimenLogView> logs(long c,long w,long o){return jdbc.sql("SELECT id,direction,method_name,request_id,related_order_code,success,error_message,created_at FROM integration_qimen_log WHERE company_id=:c AND (warehouse_id IS NULL OR warehouse_id=:w) AND (owner_id IS NULL OR owner_id=:o) ORDER BY id DESC LIMIT 200").param("c",c).param("w",w).param("o",o).query(IntegrationModels.QimenLogView.class).list();}
    void log(Long c,Long w,Long o,String direction,String method,String requestId,String order,String request,String response,boolean success,String error){jdbc.sql("INSERT INTO integration_qimen_log(company_id,warehouse_id,owner_id,direction,method_name,request_id,related_order_code,request_body,response_body,success,error_message) VALUES(:c,:w,:o,:direction,:method,:requestId,:order,:request,:response,:success,:error)").param("c",c).param("w",w).param("o",o).param("direction",direction).param("method",method).param("requestId",requestId).param("order",order).param("request",request).param("response",response).param("success",success).param("error",error).update();}
    Scope scope(long company,String warehouseCode,long owner){return jdbc.sql("SELECT w.id AS warehouse_id,o.id AS owner_id FROM wms_warehouse w JOIN wms_owner o ON o.id=:owner WHERE w.company_id=:c AND w.code=:warehouse AND w.status='ENABLED' AND o.company_id=:c AND o.status='ENABLED'").param("owner",owner).param("c",company).param("warehouse",warehouseCode).query(Scope.class).optional().orElseThrow(()->new IllegalArgumentException("奇门仓库或货主配置不存在"));}
    String ownerCode(long owner){return jdbc.sql("SELECT code FROM wms_owner WHERE id=:id").param("id",owner).query(String.class).single();}
    long systemUser(long company){return jdbc.sql("SELECT id FROM auth_user WHERE company_id=:c AND status='ENABLED' ORDER BY id LIMIT 1").param("c",company).query(Long.class).optional().orElseThrow(()->new IllegalArgumentException("公司没有可用操作用户"));}
    java.util.Map<String,Object> inventory(long c,long w,long o,String goodCode){return jdbc.sql("SELECT :warehouse AS warehouse_code,g.code AS item_code,COALESCE(sum(b.available_qty),0) AS quantity,COALESCE(sum(b.allocated_qty+b.frozen_qty),0) AS lock_quantity FROM wms_good g LEFT JOIN inv_balance b ON b.good_id=g.id AND b.warehouse_id=:w WHERE g.company_id=:c AND g.owner_id=:o AND g.code=:code GROUP BY g.code").param("warehouse",jdbc.sql("SELECT code FROM wms_warehouse WHERE id=:w").param("w",w).query(String.class).single()).param("w",w).param("c",c).param("o",o).param("code",goodCode).query().singleRow();}
    void cancelExternal(long c,long w,long o,String external,String reason){int a=jdbc.sql("UPDATE stockin_order SET state='CANCELLED',remark=:reason,updated_at=CURRENT_TIMESTAMP WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND external_order_code=:external AND state='DRAFT'").param("c",c).param("w",w).param("o",o).param("external",external).param("reason",reason).update();int b=jdbc.sql("UPDATE stockout_order SET state='CANCELLED',remark=:reason,updated_at=CURRENT_TIMESTAMP WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND external_order_code=:external AND state='DRAFT'").param("c",c).param("w",w).param("o",o).param("external",external).param("reason",reason).update();if(a+b==0)throw new IllegalArgumentException("订单不存在或当前状态不能取消");}
    Long externalStockin(long c,long w,long o,String external){return jdbc.sql("SELECT id FROM stockin_order WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND external_order_code=:external").param("c",c).param("w",w).param("o",o).param("external",external).query(Long.class).optional().orElse(null);}
    Long externalStockout(long c,long w,long o,String external){return jdbc.sql("SELECT id FROM stockout_order WHERE company_id=:c AND warehouse_id=:w AND owner_id=:o AND external_order_code=:external").param("c",c).param("w",w).param("o",o).param("external",external).query(Long.class).optional().orElse(null);}
    java.util.Map<String,Object> confirmOrder(boolean inbound,long id,long c,long w,long o){String sql=inbound?"SELECT id,order_code,external_order_code,state,'entryorder.confirm' AS method FROM stockin_order WHERE id=:id AND company_id=:c AND warehouse_id=:w AND owner_id=:o":"SELECT id,order_code,external_order_code,state,'deliveryorder.confirm' AS method FROM stockout_order WHERE id=:id AND company_id=:c AND warehouse_id=:w AND owner_id=:o";return jdbc.sql(sql).param("id",id).param("c",c).param("w",w).param("o",o).query().singleRow();}
    record Seq(Long id,long currentValue){}
    record QimenConfig(Long id,Long companyId,Long ownerId,String customerId,String appKey,String appSecret,String callbackUrl,String payloadFormat,Boolean enabled,java.time.OffsetDateTime updatedAt){}
    record Scope(Long warehouseId,Long ownerId){}
}
