package com.mt.wms.integration;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mt.wms.auth.AuthModels;
import com.mt.wms.auth.TenantContextService;
import com.mt.wms.auth.WmsPrincipal;
import jakarta.servlet.http.HttpSession;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestClient;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service
class QimenService {
    private static final Set<String> METHODS=Set.of("singleitem.synchronize","entryorder.create","returnorder.create","stockout.create","deliveryorder.create","order.cancel","inventory.query");
    private final IntegrationRepository repository;private final TenantContextService tenants;private final ObjectMapper mapper;private final RestClient rest=RestClient.create();
    QimenService(IntegrationRepository repository,TenantContextService tenants,ObjectMapper mapper){this.repository=repository;this.tenants=tenants;this.mapper=mapper;}

    IntegrationModels.QimenConfigView config(WmsPrincipal p,HttpSession session){Scope s=scope(p,session);return view(repository.configByOwner(s.c,s.o));}
    @Transactional IntegrationModels.QimenConfigView save(IntegrationModels.QimenConfigRequest r,WmsPrincipal p,HttpSession session){Scope s=scope(p,session);String customer=req(r.customerId(),"客户ID不能为空"),appKey=text(r.appKey(),"MT-WMS"),format="XML".equalsIgnoreCase(r.payloadFormat())?"XML":"JSON";IntegrationRepository.QimenConfig old=repository.configByOwner(s.c,s.o);String secret=r.appSecret();if(secret==null||secret.isBlank()){if(old==null)throw new IllegalArgumentException("首次配置必须填写密钥");secret=old.appSecret();}repository.saveConfig(old==null?null:old.id(),s.c,s.o,customer,appKey,secret.trim(),blank(r.callbackUrl()),format,!Boolean.FALSE.equals(r.enabled()),p.userId());return view(repository.configByOwner(s.c,s.o));}
    List<IntegrationModels.QimenLogView> logs(WmsPrincipal p,HttpSession session){Scope s=scope(p,session);return repository.logs(s.c,s.w,s.o);}

    @Transactional String inbound(Map<String,String> query,String body,boolean xml){String method=query.getOrDefault("method","");String customer=query.getOrDefault("customerid","");IntegrationRepository.QimenConfig config=repository.configByCustomer(customer);if(config==null)return error("客户配置不存在");String requestId=UUID.randomUUID().toString();String response;boolean ok=false;String order=null;try{if(!METHODS.contains(method))throw new IllegalArgumentException("method not support");if(!validSign(query,xml?body:"",config.appSecret()))throw new SecurityException("sign not pass valid");JsonNode root=xml?new com.fasterxml.jackson.dataformat.xml.XmlMapper().readTree(body):mapper.readTree(body);JsonNode request=root.path("request");Result result=dispatch(method,request,config);order=result.order;response=mapper.writeValueAsString(success(result.data));ok=true;repository.log(config.companyId(),result.warehouseId,config.ownerId(),"IN",method,requestId,order,body,response,true,null);return response;}catch(Exception e){response=error(message(e));repository.log(config.companyId(),null,config.ownerId(),"IN",method,requestId,order,body,response,false,message(e));return response;}}

    @Transactional Map<String,Object> confirm(String inout,long orderId,WmsPrincipal p,HttpSession session){Scope s=scope(p,session);IntegrationRepository.QimenConfig config=repository.configByOwner(s.c,s.o);if(config==null||!Boolean.TRUE.equals(config.enabled()))throw new IllegalArgumentException("当前货主未启用奇门配置");if(config.callbackUrl()==null||config.callbackUrl().isBlank())throw new IllegalArgumentException("未配置奇门回传地址");boolean inbound=inout.equalsIgnoreCase("in");Map<String,Object> order=repository.confirmOrder(inbound,orderId,s.c,s.w,s.o);String method=String.valueOf(order.get("method"));ObjectNode payload=mapper.createObjectNode();ObjectNode request=payload.putObject("request");ObjectNode node=request.putObject(inbound?"entryOrder":"deliveryOrder");node.put(inbound?"entryOrderCode":"deliveryOrderCode",String.valueOf(order.get("external_order_code")));node.put("warehouseCode",s.warehouseCode);node.put("ownerCode",s.ownerCode);node.put("orderConfirmTime",LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));String body;try{body=mapper.writeValueAsString(payload);}catch(Exception e){throw new IllegalStateException(e);}Map<String,String> args=signArgs(method,config,"");String response;try{response=rest.post().uri(config.callbackUrl()+"?"+queryString(args)).contentType(MediaType.APPLICATION_JSON).body(body).retrieve().body(String.class);repository.log(s.c,s.w,s.o,"OUT",method,UUID.randomUUID().toString(),String.valueOf(order.get("order_code")),body,response,true,null);}catch(Exception e){repository.log(s.c,s.w,s.o,"OUT",method,UUID.randomUUID().toString(),String.valueOf(order.get("order_code")),body,null,false,message(e));throw new IllegalArgumentException("奇门回传失败："+message(e));}return Map.of("method",method,"response",response==null?"":response);}

    private Result dispatch(String method,JsonNode req,IntegrationRepository.QimenConfig config){return switch(method){case "singleitem.synchronize"->item(req,config);case "entryorder.create"->order(req,config,true,false);case "returnorder.create"->order(req,config,true,true);case "stockout.create","deliveryorder.create"->order(req,config,false,false);case "order.cancel"->cancel(req,config);case "inventory.query"->inventory(req,config);default->throw new IllegalArgumentException("method not support");};}
    private Result item(JsonNode req,IntegrationRepository.QimenConfig c){JsonNode item=req.path("item");String code=node(item,"itemCode"),ownerCode=text(node(req,"ownerCode"),repository.ownerCode(c.ownerId()));String category=text(node(item,"categoryId"),"default");long categoryId=repository.ensureCategory(c.companyId(),c.ownerId(),category,text(node(item,"categoryName"),category));repository.upsertGood(c.companyId(),c.ownerId(),categoryId,code,text(node(item,"itemName"),code),text(node(item,"barCode"),code),blank(node(item,"skuProperty")),blank(node(item,"stockUnit")),decimal(node(item,"retailPrice"),BigDecimal.ZERO));return new Result(null,null,Map.of("itemId",code));}
    private Result order(JsonNode req,IntegrationRepository.QimenConfig c,boolean inbound,boolean returns){JsonNode head=req.path(inbound?(returns?"returnOrder":"entryOrder"):"deliveryOrder");String external=node(head,inbound?(returns?"returnOrderCode":"entryOrderCode"):"deliveryOrderCode");String warehouse=text(node(head,"warehouseCode"),"default");IntegrationRepository.Scope scope=repository.scope(c.companyId(),warehouse,c.ownerId());Long existing=inbound?repository.externalStockin(c.companyId(),scope.warehouseId(),scope.ownerId(),external):repository.externalStockout(c.companyId(),scope.warehouseId(),scope.ownerId(),external);if(existing==null){String partnerCode=inbound?node(head,"supplierCode"):node(head,"customerCode");Long partner=repository.partnerId(c.companyId(),blank(partnerCode));String code=repository.nextCode(inbound?"R":"O",c.companyId(),scope.warehouseId(),scope.ownerId());long user=repository.systemUser(c.companyId());long order=inbound?repository.importStockin(c.companyId(),scope.warehouseId(),scope.ownerId(),code,external,returns?"RETURN":"CUSTOM",partner,user,"QIMEN:"+methodKey(inbound,returns)+":"+external):repository.importStockout(c.companyId(),scope.warehouseId(),scope.ownerId(),code,external,"CUSTOM",partner,user,"QIMEN:OUT:"+external);ArrayNode lines=array(req.path("orderLines"));int n=1;for(JsonNode line:lines){long good=repository.good(scope.ownerId(),node(line,"itemCode"));BigDecimal qty=decimal(node(line,"planQty"),null);if(qty==null||qty.signum()<=0)throw new IllegalArgumentException("planQty必须大于0");BigDecimal price=decimal(node(line,inbound?"purchasePrice":"actualPrice"),BigDecimal.ZERO);String batch=text(node(line,"batchCode"),"-");String supplier=text(node(line,"supplierCode"),"-");if(inbound)repository.importStockinLine(order,n++,good,qty,repository.stage(scope.warehouseId()),price,batch,supplier);else repository.importStockoutLine(order,n++,good,qty,price,batch,supplier);}}
        String key=inbound?(returns?"returnOrderId":"entryOrderId"):"deliveryOrderId";return new Result(scope.warehouseId(),external,Map.of(key,external,"createTime",LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))));}
    private Result cancel(JsonNode req,IntegrationRepository.QimenConfig c){String external=node(req,"orderCode"),warehouse=text(node(req,"warehouseCode"),"default");IntegrationRepository.Scope scope=repository.scope(c.companyId(),warehouse,c.ownerId());repository.cancelExternal(c.companyId(),scope.warehouseId(),scope.ownerId(),external,text(node(req,"cancelReason"),"奇门取消"));return new Result(scope.warehouseId(),external,Map.of());}
    private Result inventory(JsonNode req,IntegrationRepository.QimenConfig c){ArrayNode lines=array(req.path("criteriaList"));List<Map<String,Object>> items=new ArrayList<>();Long warehouseId=null;for(JsonNode line:lines){IntegrationRepository.Scope scope=repository.scope(c.companyId(),text(node(line,"warehouseCode"),"default"),c.ownerId());warehouseId=scope.warehouseId();items.add(repository.inventory(c.companyId(),scope.warehouseId(),scope.ownerId(),node(line,"itemCode")));}return new Result(warehouseId,null,Map.of("items",items));}

    private boolean validSign(Map<String,String> query,String body,String secret){String actual=query.get("sign");if(actual==null)return false;Map<String,String> copy=new TreeMap<>(query);copy.remove("sign");StringBuilder raw=new StringBuilder(secret);copy.forEach((k,v)->raw.append(k).append(v));raw.append(body);return actual.equalsIgnoreCase(md5(raw.toString()));}
    private static Map<String,String> signArgs(String method,IntegrationRepository.QimenConfig c,String body){Map<String,String> args=new TreeMap<>();args.put("method",method);args.put("format",c.payloadFormat().toLowerCase(Locale.ROOT));args.put("customerid",c.customerId());args.put("app_key",c.appKey());args.put("sign_method","md5");args.put("v","2.0");args.put("timestamp",LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));StringBuilder raw=new StringBuilder(c.appSecret());args.forEach((k,v)->raw.append(k).append(v));raw.append(body);args.put("sign",md5(raw.toString()));return args;}
    private static String queryString(Map<String,String> args){return args.entrySet().stream().map(e->java.net.URLEncoder.encode(e.getKey(),StandardCharsets.UTF_8)+"="+java.net.URLEncoder.encode(e.getValue(),StandardCharsets.UTF_8)).reduce((a,b)->a+"&"+b).orElse("");}
    private static String md5(String raw){try{byte[] b=MessageDigest.getInstance("MD5").digest(raw.getBytes(StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(b);}catch(Exception e){throw new IllegalStateException(e);}}
    private static ArrayNode array(JsonNode n){if(n.isArray())return(ArrayNode)n;JsonNode nested=n.path("orderLine");if(nested.isArray())return(ArrayNode)nested;throw new IllegalArgumentException("订单明细不能为空");}
    private static String node(JsonNode n,String key){JsonNode v=n.path(key);return v.isMissingNode()||v.isNull()?"":v.asText();}
    private static BigDecimal decimal(String v,BigDecimal fallback){try{return v==null||v.isBlank()?fallback:new BigDecimal(v);}catch(Exception e){throw new IllegalArgumentException("数值格式错误："+v);}}
    private static String req(String v,String msg){if(v==null||v.isBlank())throw new IllegalArgumentException(msg);return v.trim();}
    private static String text(String v,String fallback){return v==null||v.isBlank()?fallback:v.trim();}
    private static String blank(String v){return v==null||v.isBlank()?null:v.trim();}
    private static String message(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
    private static Map<String,Object> success(Map<String,Object> data){Map<String,Object> response=new LinkedHashMap<>();response.put("flag","success");response.put("code","0");response.put("message","ok");response.putAll(data);return Map.of("response",response);}
    private String error(String msg){try{return mapper.writeValueAsString(Map.of("error_response",Map.of("flag","failure","code","1","message",msg)));}catch(Exception e){return "{\"error_response\":{\"flag\":\"failure\"}}";}}
    private static String methodKey(boolean inbound,boolean returns){return inbound?(returns?"RETURN":"IN"):"OUT";}
    private IntegrationModels.QimenConfigView view(IntegrationRepository.QimenConfig c){return c==null?null:new IntegrationModels.QimenConfigView(c.id(),c.customerId(),c.appKey(),c.callbackUrl(),c.payloadFormat(),c.enabled(),mask(c.appSecret()),c.updatedAt());}
    private static String mask(String s){return s==null||s.isBlank()?"":(s.length()<=4?"****":"****"+s.substring(s.length()-4));}
    private Scope scope(WmsPrincipal p,HttpSession session){AuthModels.TenantView t=tenants.current(p,session);return new Scope(p.companyId(),t.currentWarehouse().id(),t.currentOwner().id(),t.currentWarehouse().code(),t.currentOwner().code());}
    private record Scope(long c,long w,long o,String warehouseCode,String ownerCode){}
    private record Result(Long warehouseId,String order,Map<String,Object> data){}
}
