package com.mt.wms.integration;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

@Service
class SpreadsheetWorker {
    private final IntegrationRepository repository; private final Path root; private final DataFormatter formatter=new DataFormatter(Locale.ROOT);
    SpreadsheetWorker(IntegrationRepository repository,@Value("${wms.files-dir:${java.io.tmpdir}/mt-wms-files}")String dir){this.repository=repository;this.root=Path.of(dir).toAbsolutePath().normalize();}

    @Async @Transactional public void exportTask(long taskId){try{IntegrationModels.TaskRow task=repository.task(taskId);List<Map<String,Object>> rows=repository.exportRows(task.resourceType(),task.companyId(),task.warehouseId(),task.ownerId());Path file=file(task.storedFileName());Files.createDirectories(root);try(Workbook wb=new XSSFWorkbook();OutputStream out=Files.newOutputStream(file)){Sheet sheet=wb.createSheet(task.resourceType());if(!rows.isEmpty()){List<String> headers=new ArrayList<>(rows.get(0).keySet());Row head=sheet.createRow(0);CellStyle style=wb.createCellStyle();Font font=wb.createFont();font.setBold(true);style.setFont(font);for(int i=0;i<headers.size();i++){Cell cell=head.createCell(i);cell.setCellValue(headers.get(i));cell.setCellStyle(style);}int rowNo=1;for(Map<String,Object> data:rows){Row row=sheet.createRow(rowNo++);for(int i=0;i<headers.size();i++)value(row.createCell(i),data.get(headers.get(i)));}for(int i=0;i<headers.size();i++)sheet.autoSizeColumn(i);}wb.write(out);}repository.complete(taskId,rows.size(),rows.size(),0);}catch(Exception e){repository.fail(taskId,message(e));}}

    @Async @Transactional public void importTask(long taskId){try{IntegrationModels.TaskRow task=repository.task(taskId);Path file=file(task.storedFileName());List<Map<String,String>> rows=read(file);switch(task.resourceType()){case "GOODS"->goods(task,rows);case "PARTNERS"->partners(task,rows);case "STOCKIN"->stockin(task,rows);case "STOCKOUT"->stockout(task,rows);default->throw new IllegalArgumentException("不支持的导入资源："+task.resourceType());}repository.complete(taskId,rows.size(),rows.size(),0);}catch(Exception e){repository.fail(taskId,message(e));}}

    void template(String resource,OutputStream out)throws Exception{List<String> headers=switch(resource){case "GOODS"->List.of("code","name","barcode","categoryCode","categoryName","specification","unit","price");case "PARTNERS"->List.of("code","name","partnerType","contact","telephone","email","address");case "STOCKIN"->List.of("externalOrderCode","inboundType","partnerCode","goodCode","quantity","unitPrice","batchCode","supplierCode");case "STOCKOUT"->List.of("externalOrderCode","outboundType","partnerCode","goodCode","quantity","unitPrice","batchCode","supplierCode");default->throw new IllegalArgumentException("不支持的导入模板："+resource);};try(Workbook wb=new XSSFWorkbook()){Sheet sheet=wb.createSheet(resource);Row row=sheet.createRow(0);for(int i=0;i<headers.size();i++){row.createCell(i).setCellValue(headers.get(i));sheet.setColumnWidth(i,5200);}wb.write(out);}}

    private void goods(IntegrationModels.TaskRow t,List<Map<String,String>> rows){for(Map<String,String> row:rows){String code=req(row,"code"),name=req(row,"name"),category=text(row,"categoryCode","default"),barcode=text(row,"barcode",code);long categoryId=repository.ensureCategory(t.companyId(),t.ownerId(),category,text(row,"categoryName",category));repository.upsertGood(t.companyId(),t.ownerId(),categoryId,code,name,barcode,text(row,"specification",null),text(row,"unit",null),number(row,"price",BigDecimal.ZERO));}}
    private void partners(IntegrationModels.TaskRow t,List<Map<String,String>> rows){for(Map<String,String> row:rows)repository.upsertPartner(t.companyId(),req(row,"code"),req(row,"name"),partnerType(text(row,"partnerType","CLIENT")),text(row,"contact",null),text(row,"telephone",null),text(row,"email",null),text(row,"address",null));}
    private void stockin(IntegrationModels.TaskRow t,List<Map<String,String>> rows){Map<String,List<Map<String,String>>> groups=group(rows,"externalOrderCode");Long stage=repository.stage(t.warehouseId());for(var entry:groups.entrySet()){Map<String,String> first=entry.getValue().get(0);String external=entry.getKey();long order=repository.importStockin(t.companyId(),t.warehouseId(),t.ownerId(),repository.nextCode("R",t.companyId(),t.warehouseId(),t.ownerId()),external,inType(text(first,"inboundType","NORMAL")),repository.partnerId(t.companyId(),text(first,"partnerCode",null)),t.createdBy(),"IMPORT:"+t.taskCode()+":"+external);int no=1;for(Map<String,String> row:entry.getValue())repository.importStockinLine(order,no++,repository.good(t.ownerId(),req(row,"goodCode")),positive(row,"quantity"),stage,number(row,"unitPrice",BigDecimal.ZERO),text(row,"batchCode","-"),text(row,"supplierCode","-"));}}
    private void stockout(IntegrationModels.TaskRow t,List<Map<String,String>> rows){Map<String,List<Map<String,String>>> groups=group(rows,"externalOrderCode");for(var entry:groups.entrySet()){Map<String,String> first=entry.getValue().get(0);String external=entry.getKey();long order=repository.importStockout(t.companyId(),t.warehouseId(),t.ownerId(),repository.nextCode("O",t.companyId(),t.warehouseId(),t.ownerId()),external,outType(text(first,"outboundType","NORMAL")),repository.partnerId(t.companyId(),text(first,"partnerCode",null)),t.createdBy(),"IMPORT:"+t.taskCode()+":"+external);int no=1;for(Map<String,String> row:entry.getValue())repository.importStockoutLine(order,no++,repository.good(t.ownerId(),req(row,"goodCode")),positive(row,"quantity"),number(row,"unitPrice",BigDecimal.ZERO),text(row,"batchCode","-"),text(row,"supplierCode","-"));}}

    private List<Map<String,String>> read(Path file)throws Exception{try(InputStream in=Files.newInputStream(file);Workbook wb=WorkbookFactory.create(in)){Sheet sheet=wb.getSheetAt(0);if(sheet.getPhysicalNumberOfRows()<1)throw new IllegalArgumentException("Excel没有表头");Row head=sheet.getRow(sheet.getFirstRowNum());List<String> headers=new ArrayList<>();for(Cell cell:head)headers.add(formatter.formatCellValue(cell).trim());List<Map<String,String>> rows=new ArrayList<>();for(int n=head.getRowNum()+1;n<=sheet.getLastRowNum();n++){Row row=sheet.getRow(n);if(row==null)continue;Map<String,String> data=new LinkedHashMap<>();boolean any=false;for(int i=0;i<headers.size();i++){String value=formatter.formatCellValue(row.getCell(i,Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).trim();data.put(headers.get(i),value);any|=!value.isBlank();}if(any)rows.add(data);}if(rows.isEmpty())throw new IllegalArgumentException("Excel没有数据行");return rows;}}
    private Path file(String name){Path p=root.resolve(name).normalize();if(!p.startsWith(root))throw new IllegalArgumentException("非法文件路径");return p;}
    Path path(String name){return file(name);}
    private static void value(Cell cell,Object v){if(v==null)return;if(v instanceof Number n)cell.setCellValue(n.doubleValue());else if(v instanceof java.time.temporal.TemporalAccessor)cell.setCellValue(v.toString());else cell.setCellValue(String.valueOf(v));}
    private static Map<String,List<Map<String,String>>> group(List<Map<String,String>> rows,String key){Map<String,List<Map<String,String>>> out=new LinkedHashMap<>();for(Map<String,String> row:rows)out.computeIfAbsent(req(row,key),x->new ArrayList<>()).add(row);return out;}
    private static String req(Map<String,String> row,String key){String v=row.get(key);if(v==null||v.isBlank())throw new IllegalArgumentException("Excel字段不能为空："+key);return v.trim();}
    private static String text(Map<String,String> row,String key,String fallback){String v=row.get(key);return v==null||v.isBlank()?fallback:v.trim();}
    private static BigDecimal number(Map<String,String> row,String key,BigDecimal fallback){String v=row.get(key);try{return v==null||v.isBlank()?fallback:new BigDecimal(v.trim());}catch(Exception e){throw new IllegalArgumentException("Excel数值格式错误："+key);}}
    private static BigDecimal positive(Map<String,String> row,String key){BigDecimal v=number(row,key,null);if(v==null||v.signum()<=0)throw new IllegalArgumentException("Excel数量必须大于0："+key);return v;}
    private static String partnerType(String v){return Set.of("CLIENT","SUPPLIER","CLIENT_SUPPLIER","EXPRESS").contains(v.toUpperCase(Locale.ROOT))?v.toUpperCase(Locale.ROOT):"CLIENT";}
    private static String inType(String v){String x=v.toUpperCase(Locale.ROOT);return Set.of("PURCHASE","RETURN","TRANSFER","CONSIGN","CUSTOM","PRODUCE","MATERIAL_RETURN","FIX","BORROW_RETURN","NORMAL","COOP_RETURN","PRODUCE_RETURN").contains(x)?x:"NORMAL";}
    private static String outType(String v){String x=v.toUpperCase(Locale.ROOT);return Set.of("SALE","PRODUCE","NORMAL","RETURN","COOP","MATERIAL_PICK","FIX","SCRAP","BORROW","TRANSFER","CONSIGN","CUSTOM").contains(x)?x:"NORMAL";}
    private static String message(Exception e){String m=e.getMessage();return (m==null||m.isBlank()?e.getClass().getSimpleName():m);}
}
