package com.bdemo.monitor;

import com.bdemo.common.AjaxResult;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

import java.lang.management.ManagementFactory;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;

@RestController @RequestMapping("/monitor") public class MonitorController{
 private final String prefix;private final JdbcTemplate jdbc;private final RedisConnectionFactory redis;public MonitorController(JdbcTemplate j,RedisConnectionFactory r,@org.springframework.beans.factory.annotation.Value("${b-demo.cache-prefix}") String p){jdbc=j;redis=r;prefix=p;}
 @GetMapping("/server") public AjaxResult server(){Runtime rt=Runtime.getRuntime();long total=rt.totalMemory()/1048576,free=rt.freeMemory()/1048576,used=total-free;double usage=total==0?0:Math.round(used*1000.0/total)/10.0;Map<String,Object>memory=map("total",total+" MB","used",used+" MB","free",free+" MB","usage",usage);return AjaxResult.success(map("cpu",map("cpuNum",rt.availableProcessors(),"used",0,"sys",0,"free",100),"mem",memory,"jvmMemory",memory,"jvm",map("name",System.getProperty("java.vm.name"),"version",System.getProperty("java.version"),"startTime",ManagementFactory.getRuntimeMXBean().getStartTime(),"runTime",ManagementFactory.getRuntimeMXBean().getUptime(),"home",System.getProperty("java.home")),"sys",map("osName",System.getProperty("os.name"),"osArch",System.getProperty("os.arch"),"computerName",hostName(),"computerIp",hostAddress(),"userDir",System.getProperty("user.dir")),"sysFiles",List.of()));}
 @GetMapping("/cache") public AjaxResult cache(){var c=redis.getConnection();try{var props=c.serverCommands().info();Map<String,Object>info=new LinkedHashMap<>();for(String name:props.stringPropertyNames())info.put(name,props.getProperty(name));return AjaxResult.success(map("info",info,"dbSize",scan(prefix+"captcha_codes:*").size(),"commandStats",List.of()));}finally{c.close();}}
 // Shared Kvrocks namespace: only EMCS keys are visible or deletable (REQ server adaptation).
 @GetMapping("/cache/getNames") public AjaxResult names(){return AjaxResult.success(List.of(map("cacheName","captcha_codes","remark","验证码")));}
 private void checkName(String name){if(!"captcha_codes".equals(name))throw new IllegalArgumentException("缓存名称无效");}
 private void checkKey(String key){if(!key.startsWith(prefix+"captcha_codes:"))throw new IllegalArgumentException("缓存键不属于 EMCS");}
 private List<String> scan(String pattern){try(var c=redis.getConnection();var cursor=c.keyCommands().scan(org.springframework.data.redis.core.ScanOptions.scanOptions().match(pattern).count(100).build())){java.util.ArrayList<String> keys=new java.util.ArrayList<>();while(cursor.hasNext())keys.add(new String(cursor.next(),java.nio.charset.StandardCharsets.UTF_8));return keys;}}
 @GetMapping("/cache/getKeys/{name}") public AjaxResult keys(@PathVariable String name){checkName(name);return AjaxResult.success(scan(prefix+name+":*"));}
 @GetMapping("/cache/getValue/{name}/{key}") public AjaxResult value(@PathVariable String name,@PathVariable String key){checkName(name);checkKey(key);try(var c=redis.getConnection()){byte[]v=c.stringCommands().get(key.getBytes(java.nio.charset.StandardCharsets.UTF_8));return AjaxResult.success(map("cacheName",name,"cacheKey",key,"cacheValue",v==null?null:new String(v,java.nio.charset.StandardCharsets.UTF_8)));}}
 @DeleteMapping("/cache/clearCacheKey/{key}") public AjaxResult clearKey(@PathVariable String key){checkKey(key);try(var c=redis.getConnection()){c.keyCommands().del(key.getBytes(java.nio.charset.StandardCharsets.UTF_8));}return AjaxResult.success();}
 @DeleteMapping("/cache/clearCacheName/{name}") public AjaxResult clearName(@PathVariable String name){checkName(name);for(String k:scan(prefix+name+":*"))clearKey(k);return AjaxResult.success();}
 @DeleteMapping("/cache/clearCacheAll") public AjaxResult clearAll(){return clearName("captcha_codes");}
 private String hostName(){try{return java.net.InetAddress.getLocalHost().getHostName();}catch(java.net.UnknownHostException e){return "unknown";}}
 private String hostAddress(){try{return java.net.InetAddress.getLocalHost().getHostAddress();}catch(java.net.UnknownHostException e){return "unknown";}}
 @GetMapping("/online/list") public AjaxResult online(){return AjaxResult.success().add("rows",List.of()).add("total",0);}@DeleteMapping("/online/{tokenId}") public AjaxResult force(@PathVariable String tokenId){return AjaxResult.success();}
 @GetMapping("/{kind:job|jobLog|logininfor|operlog}/list") public AjaxResult list(@PathVariable String kind,@RequestParam(defaultValue="1")int pageNum,@RequestParam(defaultValue="10")int pageSize){String table=switch(kind){case"job"->"sys_job";case"jobLog"->"sys_job_log";case"logininfor"->"sys_logininfor";default->"sys_oper_log";};Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM "+table,Integer.class);List<Map<String,Object>>rows=jdbc.queryForList("SELECT * FROM "+table+" ORDER BY 1 DESC LIMIT ? OFFSET ?",pageSize,(pageNum-1)*pageSize).stream().map(this::camel).toList();return AjaxResult.success().add("rows",rows).add("total",total);}
 @GetMapping("/{kind:job|jobLog}/{id}") public AjaxResult get(@PathVariable String kind,@PathVariable long id){String table=kind.equals("job")?"sys_job":"sys_job_log",col=kind.equals("job")?"job_id":"job_log_id";List<Map<String,Object>>r=jdbc.queryForList("SELECT * FROM "+table+" WHERE "+col+"=?",id);return r.isEmpty()?AjaxResult.error(404,"记录不存在"):AjaxResult.success(camel(r.get(0)));}
 @DeleteMapping("/{kind:jobLog|logininfor|operlog}/clean") public AjaxResult clean(@PathVariable String kind){String table=kind.equals("jobLog")?"sys_job_log":kind.equals("logininfor")?"sys_logininfor":"sys_oper_log";jdbc.update("DELETE FROM "+table);return AjaxResult.success();}
 private Map<String,Object>camel(Map<String,Object>r){Map<String,Object>m=new LinkedHashMap<>();r.forEach((k,v)->{StringBuilder b=new StringBuilder();boolean u=false;for(char c:k.toCharArray()){if(c=='_')u=true;else{b.append(u?Character.toUpperCase(c):c);u=false;}}m.put(b.toString(),v);});return m;}private Map<String,Object>map(Object...p){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<p.length;i+=2)m.put((String)p[i],p[i+1]);return m;}
}
