-- The image bootstrap grants SYSADMIN to GS_USERNAME; MT-WMS uses least privilege instead.
ALTER USER wms_app NOSYSADMIN;

GRANT CONNECT ON DATABASE mt_wms TO wms_app;
GRANT USAGE, CREATE ON SCHEMA public TO wms_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wms_app;
ALTER DEFAULT PRIVILEGES FOR USER omm IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wms_app;
